[package]
name = "pocketjs-esp32-core"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
pocketjs-core = { path = "../../../engine/core" }
libquickjs-sys = { path = "../vendor/libquickjs-sys" }

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
