// tools/ranger-cook/cook.ts — M1 cook skeleton (hand-written).
//
// Entry: extract → raster → pack-manifest. In M1 the extract/raster stages
// are local-evidence only (no SWF needed): stable IDs come from ids.ts,
// pixel dimensions come from an IHDR scan of the local PNGs, and the
// variant/fighter/grid payload is the M1 snapshot carried by the current
// manifests (SWF-derived extraction is M2+ work). What M1 DOES enforce:
//
// - fail-hard scope: unknown or out-of-scope linkage IDs throw
//   CookScopeError via apps/ranger/scope.ts (never invent IDs);
// - manifest validation: stable-ID grammar, on-disk PNG existence,
//   frames == cols*rows, sprites/anim grid agreement, variant sheet
//   membership (failures throw CookError);
// - determinism: sorted keys, canonical JSON, exact provenance headers —
//   two runs over the same inputs are byte-identical (fixed point).
//
// The SWF is never required: `--swf <path>` / RANGER_SWF, when present, is
// only header-checked (FWS) and never copied into the repo or outputs.
// Outputs carry the logical ref `swf:fws6:root19f`, never a local path.
//
// Usage (bun or node with type stripping):
//   cook.ts [--app <dir>] [--linkage a,b,...] [--swf <path>] [--check]

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CookScopeError,
  LINKAGE,
  validateCookScope,
} from "../../apps/ranger/scope.ts";
import { isSpriteSheetFile } from "./ids.ts";
import { resolveSwfPath } from "./scan.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..", "..");

export const GENERATED_BY = "tools/ranger-cook/cook.ts";
export const SWF_REF = "swf:fws6:root19f";
export const SHEETS_HEADER = `// auto-generated by ${GENERATED_BY} — do not edit.`;

/** Manifest failure (corrupt payload, missing PNG, grid mismatch). */
export class CookError extends Error {
  constructor(message: string) {
    super(`ranger cook: ${message}`);
    this.name = "CookError";
  }
}

// --- PNG IHDR scan (no dependencies) ---

const PNG_SIG = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

export interface PngSize {
  w: number;
  h: number;
}

/** Read w/h from a PNG IHDR. Throws CookError on non-PNG/short files. */
export function readPngSize(path: string): PngSize {
  let buf: Buffer;
  try {
    buf = readFileSync(path) as Buffer;
  } catch {
    throw new CookError(`missing PNG ${path}`);
  }
  if (buf.length < 33) throw new CookError(`truncated PNG ${path}`);
  for (let i = 0; i < PNG_SIG.length; i++) {
    if (buf[i] !== PNG_SIG[i]) throw new CookError(`not a PNG ${path}`);
  }
  const w = buf.readUInt32BE(16);
  const h = buf.readUInt32BE(20);
  if (!(w > 0 && h > 0)) throw new CookError(`bad IHDR ${path}`);
  return { w, h };
}

// --- Canonical JSON (sorted object keys, arrays untouched) ---

function isPlainObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

export function sortKeysDeep(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeysDeep);
  if (isPlainObject(value)) {
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(value).sort()) out[k] = sortKeysDeep(value[k]);
    return out;
  }
  return value;
}

export interface Provenance {
  _generatedBy: string;
  _swfRef: string;
  _doNotEdit: boolean;
}

export function provenance(): Provenance {
  return { _generatedBy: GENERATED_BY, _swfRef: SWF_REF, _doNotEdit: true };
}

/** Canonical manifest text: provenance header first, then sorted body. */
export function emitManifestJson(body: Record<string, unknown>): string {
  return `${JSON.stringify({ ...provenance(), ...(sortKeysDeep(body) as Record<string, unknown>) })}\n`;
}

/** Strip provenance keys from a prior manifest (tolerates their absence). */
export function stripProvenance<T>(doc: Record<string, unknown>): T {
  const { _generatedBy: _g, _swfRef: _s, _doNotEdit: _d, ...rest } = doc;
  void _g;
  void _s;
  void _d;
  return rest as T;
}

// --- Manifest shapes (build-compatible records, §4.3 + tools/build.ts) ---

export interface SheetMeta {
  cellW: number;
  cellH: number;
  cols: number;
  rows: number;
  frames: number;
}
export interface VFrame {
  sheet: string;
  cell: number;
  ox: number;
  oy: number;
  w: number;
  h: number;
}
export interface Variant {
  ax: number;
  ay: number;
  frames: VFrame[];
}
export interface Fighter {
  labels: [number, string][];
  frames: unknown[][];
}
export interface SpriteMeta {
  cols: number;
  rows: number;
  frames: number;
  step: number;
  psm?: number;
}
export interface ImageMeta {
  psm?: number;
  linear?: boolean;
  w?: number;
  h?: number;
  src?: string;
}

// --- Generation (pure: inputs -> output texts) ---

export interface CookInputs {
  linkageIds: readonly string[];
  sheets: Record<string, SheetMeta>;
  variants: Record<string, Variant>;
  fighters: Record<string, Fighter>;
  images: Record<string, ImageMeta>;
  /** Prior sprite meta (step/psm evidence, carried; grids must agree). */
  priorSprites: Record<string, SpriteMeta>;
  /** Measured PNG sizes for every referenced file. */
  pngSizes: Record<string, PngSize>;
}

export interface CookOutputs {
  animJson: string;
  imagesJson: string;
  spritesJson: string;
  sheetsTs: string;
}

function assertInt(v: unknown, what: string): asserts v is number {
  if (typeof v !== "number" || !Number.isInteger(v)) {
    throw new CookError(`not an int: ${what}`);
  }
}

export function generateManifests(inputs: CookInputs): CookOutputs {
  // 1. Fail-hard scope gate: unknown/out-of-scope linkage IDs throw.
  validateCookScope(inputs.linkageIds);

  // 2. Sheets: stable-ID grammar + grid invariant.
  const sheetNames = Object.keys(inputs.sheets);
  if (sheetNames.length === 0) throw new CookError("no sheets");
  for (const name of sheetNames) {
    if (!isSpriteSheetFile(name)) {
      throw new CookError(`unknown sheet ID form: ${name}`);
    }
    if (!inputs.pngSizes[name]) throw new CookError(`sheet PNG missing: ${name}`);
    const g = inputs.sheets[name];
    assertInt(g.cellW, `${name}.cellW`);
    assertInt(g.cellH, `${name}.cellH`);
    assertInt(g.cols, `${name}.cols`);
    assertInt(g.rows, `${name}.rows`);
    assertInt(g.frames, `${name}.frames`);
    if (g.cellW <= 0 || g.cellH <= 0 || g.cols <= 0 || g.rows <= 0) {
      throw new CookError(`bad grid: ${name}`);
    }
    if (g.frames !== g.cols * g.rows) {
      throw new CookError(`frames != cols*rows: ${name}`);
    }
  }

  // 3. Variants: every frame cell must name a known sheet.
  for (const [id, v] of Object.entries(inputs.variants)) {
    if (!/^v?\d+$/.test(id)) throw new CookError(`unknown variant ID form: ${id}`);
    for (const f of v.frames) {
      if (!inputs.sheets[f.sheet]) throw new CookError(`variant ${id} refs unknown sheet ${f.sheet}`);
      assertInt(f.cell, `${id}.cell`);
      if (f.w <= 0 || f.h <= 0) throw new CookError(`bad cell rect: ${id}`);
    }
  }

  // 4. Sprites: exact key-set agreement with sheets (build reads records).
  // Grids come from sheets; step/psm evidence is carried from the prior
  // sprites.json (defaults step 2 = §4.4 core auto-cycle cadence).
  const priorKeys = new Set(Object.keys(inputs.priorSprites));
  if (priorKeys.size !== sheetNames.length || sheetNames.some((n) => !priorKeys.has(n))) {
    throw new CookError("sprites.json keys disagree with anim.json sheets");
  }
  const sprites: Record<string, SpriteMeta> = {};
  for (const name of sheetNames) {
    const g = inputs.sheets[name];
    const prior = inputs.priorSprites[name];
    if (prior.cols !== g.cols || prior.rows !== g.rows || prior.frames !== g.frames) {
      throw new CookError(`sprite grid disagrees with sheet: ${name}`);
    }
    assertInt(prior.step, `${name}.step`);
    if (prior.step <= 0) throw new CookError(`bad step: ${name}`);
    sprites[name] = { cols: g.cols, rows: g.rows, frames: g.frames, step: prior.step, psm: prior.psm ?? 2 };
  }

  // 5. Images: referenced PNGs must exist; dims come from the IHDR scan.
  const images: Record<string, ImageMeta> = {};
  for (const [name, meta] of Object.entries(inputs.images)) {
    const size = inputs.pngSizes[name];
    if (!size) throw new CookError(`image PNG missing: ${name}`);
    images[name] = { ...meta, w: size.w, h: size.h, src: name };
  }

  // 6. sheets.ts: exact header + sorted names.
  const sorted = [...sheetNames].sort();
  const sheetsTs =
    `${SHEETS_HEADER}\n` +
    `export const SHEET_NAMES = [\n` +
    sorted.map((n) => `  "${n}",\n`).join("") +
    `] as const;\n`;

  return {
    animJson: emitManifestJson({
      variants: inputs.variants,
      sheets: inputs.sheets,
      fighters: inputs.fighters,
    }),
    imagesJson: emitManifestJson(images),
    spritesJson: emitManifestJson(sprites),
    sheetsTs,
  };
}

// --- App-dir driver (reads prior manifests + PNGs, writes canonical) ---

export interface CookSummary {
  appDir: string;
  linkageIds: string[];
  sheets: number;
  variants: number;
  fighters: number;
  images: number;
  bytes: Record<string, number>;
}

function readJson(path: string): Record<string, unknown> {
  return JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
}

export function cookAppDir(
  appDir: string,
  linkageIds: readonly string[] = Object.keys(LINKAGE),
  write = true,
): { outputs: CookOutputs; summary: CookSummary } {
  const priorAnim = stripProvenance<{
    variants?: Record<string, Variant>;
    sheets?: Record<string, SheetMeta>;
    fighters?: Record<string, Fighter>;
  }>(readJson(join(appDir, "anim.json")));
  const priorImages = stripProvenance<Record<string, ImageMeta>>(
    readJson(join(appDir, "images.json")),
  );
  const priorSprites = stripProvenance<Record<string, SpriteMeta>>(
    readJson(join(appDir, "sprites.json")),
  );
  if (!priorAnim.sheets || !priorAnim.variants || !priorAnim.fighters) {
    throw new CookError("anim.json needs variants/sheets/fighters");
  }

  // PNG sizes for every referenced file (sheets + images).
  const pngSizes: Record<string, PngSize> = {};
  const want = new Set([...Object.keys(priorAnim.sheets), ...Object.keys(priorImages)]);
  for (const name of want) {
    pngSizes[name] = readPngSize(join(appDir, name));
  }

  const outputs = generateManifests({
    linkageIds,
    sheets: priorAnim.sheets,
    variants: priorAnim.variants,
    fighters: priorAnim.fighters,
    images: priorImages,
    priorSprites,
    pngSizes,
  });

  const files: Record<string, string> = {
    "anim.json": outputs.animJson,
    "images.json": outputs.imagesJson,
    "sprites.json": outputs.spritesJson,
    "sheets.ts": outputs.sheetsTs,
  };
  const bytes: Record<string, number> = {};
  if (write) {
    for (const [name, text] of Object.entries(files)) {
      writeFileSync(join(appDir, name), text);
      bytes[name] = Buffer.byteLength(text);
    }
  } else {
    for (const [name, text] of Object.entries(files)) bytes[name] = Buffer.byteLength(text);
  }
  return {
    outputs,
    summary: {
      appDir,
      linkageIds: [...linkageIds],
      sheets: Object.keys(priorAnim.sheets).length,
      variants: Object.keys(priorAnim.variants).length,
      fighters: Object.keys(priorAnim.fighters).length,
      images: Object.keys(priorImages).length,
      bytes,
    },
  };
}

/** Optional SWF presence check: FWS magic only, never copied or read past. */
export function checkSwfPath(swfPath: string | null): void {
  if (swfPath === null) return;
  const buf = readFileSync(swfPath);
  if (buf.length < 3 || buf[0] !== 0x46 || buf[1] !== 0x57 || buf[2] !== 0x53) {
    throw new CookError(`not an FWS SWF: ${swfPath}`);
  }
}

export function main(argv: string[] = process.argv.slice(2)): CookSummary {
  let appDir = resolve(REPO, "apps/ranger");
  let linkageIds: readonly string[] = Object.keys(LINKAGE);
  let check = false;
  let swfPath: string | null = null;
  try {
    swfPath = resolveSwfPath(process.env, argv);
  } catch {
    swfPath = null;
  }
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--app" && i + 1 < argv.length) appDir = resolve(REPO, argv[++i]);
    else if (a === "--linkage" && i + 1 < argv.length) linkageIds = argv[++i].split(",");
    else if (a === "--check") check = true;
  }
  checkSwfPath(swfPath);
  if (check) {
    const before: Record<string, string> = {};
    for (const n of ["anim.json", "images.json", "sprites.json", "sheets.ts"]) {
      before[n] = readFileSync(join(appDir, n), "utf8");
    }
    const { outputs } = cookAppDir(appDir, linkageIds, false);
    const after = [outputs.animJson, outputs.imagesJson, outputs.spritesJson, outputs.sheetsTs];
    ["anim.json", "images.json", "sprites.json", "sheets.ts"].forEach((n, i) => {
      if (before[n] !== after[i]) throw new CookError(`--check: ${n} differs; run cook`);
    });
    return cookAppDir(appDir, linkageIds, false).summary;
  }
  return cookAppDir(appDir, linkageIds, true).summary;
}

const invokedAsMain =
  typeof (import.meta as { main?: boolean }).main === "boolean"
    ? (import.meta as { main?: boolean }).main === true
    : process.argv[1] !== undefined &&
      resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedAsMain) {
  const summary = main();
  console.log(JSON.stringify(summary, null, 2));
}

export { CookScopeError };
