// AUTO-GENERATED by demos/gallery/gen-assets.ts — the gallery's shader-baked
// animated cover atlases. Names are FULL string literals so scripts/build.ts
// collects them; sprites.json marks them as sprite atlases so each is baked
// into the pak as a ui:sprite.<name> entry (a plain .ts, NOT *.generated.ts,
// so the pass-1 walker scans it).

export const FRAME_SIZE = 64;
export const GALLERY_PAGES = 4;
export const TILES_PER_PAGE = 6;

export const TILE_SRCS: string[] = [
  "tile-00.png",
  "tile-01.png",
  "tile-02.png",
  "tile-03.png",
  "tile-04.png",
  "tile-05.png",
  "tile-06.png",
  "tile-07.png",
  "tile-08.png",
  "tile-09.png",
  "tile-10.png",
  "tile-11.png",
  "tile-12.png",
  "tile-13.png",
  "tile-14.png",
  "tile-15.png",
  "tile-16.png",
  "tile-17.png",
  "tile-18.png",
  "tile-19.png",
  "tile-20.png",
  "tile-21.png",
  "tile-22.png",
  "tile-23.png",
];
