// vapor/compiler/esp32.ts — package a generated Pocket Vapor app as a
// classic-ESP32 application image.
//
// The generated ESP-IDF project is intentionally retained next to the
// firmware. Besides making the build reproducible, this gives the hardware
// scripts a stable project/build directory for `idf.py flash` and monitoring.

import { existsSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { mkdir, unlink } from "node:fs/promises";
import { homedir } from "node:os";
import { admitBoard, boardDefinitions, loadBoard, type VaporBoard } from "./boards.ts";
import { VAPOR_TARGETS, type CompiledApp } from "./compile.ts";

const RUNTIME = resolve(import.meta.dir, "..", "runtime");
const IDF_VERSION = "v6.0.2";
export const DEFAULT_BOARD = "meowbit";

function cmakeString(value: string): string {
  return `"${value.replaceAll("\\", "/").replaceAll('"', '\\"')}"`;
}

async function requireFile(path: string, description: string): Promise<void> {
  if (!(await Bun.file(path).exists())) {
    throw new Error(`${description} not found: ${path}`);
  }
}

async function runIdf(
  idfPath: string,
  idfToolsPath: string,
  args: string[],
): Promise<void> {
  // export.sh wires the matching Python virtualenv and Xtensa toolchain into
  // PATH. Positional arguments keep paths/data out of the shell program.
  const configuredShell = process.env.SHELL;
  const shell =
    configuredShell &&
    existsSync(configuredShell) &&
    (basename(configuredShell) === "bash" || basename(configuredShell) === "zsh")
      ? configuredShell
      : Bun.which("zsh") ?? Bun.which("bash");
  if (!shell) throw new Error("ESP-IDF requires bash or zsh to source export.sh");
  const child = Bun.spawn(
    [
      shell,
      "-lc",
      'source "$1/export.sh" && shift && exec idf.py "$@"',
      "pocket-vapor-idf",
      idfPath,
      ...args,
    ],
    {
      env: {
        ...process.env,
        IDF_PATH: idfPath,
        IDF_TOOLS_PATH: idfToolsPath,
      },
      stdout: "inherit",
      stderr: "inherit",
    },
  );
  const exitCode = await child.exited;
  if (exitCode !== 0) {
    throw new Error(`ESP-IDF command failed (${exitCode}): idf.py ${args.join(" ")}`);
  }
}

export interface EspIdfEnvironment {
  idfPath: string;
  idfToolsPath: string;
}

function firstDirectory(
  explicit: string | undefined,
  candidates: string[],
  marker: string,
): string {
  if (explicit) return resolve(explicit);
  return (
    candidates
      .map((candidate) => resolve(candidate))
      .find((candidate) => existsSync(join(candidate, marker))) ??
    resolve(candidates[0])
  );
}

/** Locate an explicit, cached, or standard ESP-IDF installation. */
export function resolveEspIdfEnvironment(): EspIdfEnvironment {
  const home = homedir();
  return {
    idfPath: firstDirectory(
      process.env.IDF_PATH,
      [
        join(home, "Library", "Caches", "esp-idf", IDF_VERSION),
        join(home, "esp", "esp-idf"),
      ],
      "export.sh",
    ),
    idfToolsPath: firstDirectory(
      process.env.IDF_TOOLS_PATH,
      [
        join(home, "Library", "Caches", "espressif"),
        join(home, ".espressif"),
      ],
      "python_env",
    ),
  };
}

/** Run a command in the matching ESP-IDF environment used by the builder. */
export async function runEspIdf(args: string[]): Promise<void> {
  const { idfPath, idfToolsPath } = resolveEspIdfEnvironment();
  await requireFile(join(idfPath, "export.sh"), "ESP-IDF export script");
  await runIdf(idfPath, idfToolsPath, args);
}

function mainCmake(debugStateBytes: number, buildId: string, board: VaporBoard): string {
  const target = VAPOR_TARGETS.esp32;
  const sources = [
    join(RUNTIME, "vapor_core.c"),
    join(RUNTIME, "esp32", "vapor_esp32.c"),
    "gen_app.c",
  ];
  const definitions = [
    `VP_GRID_W=${target.width}`,
    `VP_GRID_H=${target.height}`,
    `VP_STR_CAP=${target.strCap}`,
    `VP_VIEW_CAP=${target.poolCap}`,
    `VP_DEBUG_STATE_BYTES=${debugStateBytes}`,
    `VP_BUILD_ID=\\"${buildId}\\"`,
    ...boardDefinitions(board),
  ];

  return [
    "# GENERATED by vapor/compiler/esp32.ts. DO NOT EDIT.",
    "idf_component_register(",
    "  SRCS",
    ...sources.map((source) => `    ${cmakeString(source)}`),
    `  INCLUDE_DIRS ${cmakeString(RUNTIME)}`,
    "  REQUIRES esp_driver_gpio esp_driver_spi esp_driver_uart esp_timer vfs",
    ")",
    "",
    "target_compile_definitions(${COMPONENT_LIB} PRIVATE",
    ...definitions.map((definition) => `  ${definition}`),
    ")",
    "",
  ].join("\n");
}

export interface Esp32BuildResult {
  romBytes: number;
  projectDir: string;
  buildDir: string;
  buildId: string;
}

/** Identity of the generated app plus every source/config input flashed.
 * The board contributes exactly its derived definitions, so a board file
 * refactor that keeps the definitions byte-identical keeps the id. */
export async function esp32BuildId(app: CompiledApp, board: VaporBoard): Promise<string> {
  const hasher = new Bun.CryptoHasher("sha256");
  hasher.update(`${IDF_VERSION}\n${JSON.stringify(boardDefinitions(board))}\n${app.c}\n`);
  for (const path of [
    join(RUNTIME, "vapor.h"),
    join(RUNTIME, "vapor_core.c"),
    join(RUNTIME, "esp32", "vapor_esp32.c"),
    join(RUNTIME, "esp32", "sdkconfig.defaults"),
  ]) {
    hasher.update(await Bun.file(path).arrayBuffer());
  }
  return hasher.digest("hex").slice(0, 16);
}

export async function buildEsp32Firmware(
  app: CompiledApp,
  outFirmware: string,
  board: VaporBoard = loadBoard(DEFAULT_BOARD),
): Promise<Esp32BuildResult> {
  const target = VAPOR_TARGETS.esp32;
  const refusals = admitBoard({ buttonsUsed: [] }, board, target).filter((i) => i.severity === "error");
  if (refusals.length > 0) {
    throw new Error(`board ${board.board} cannot host the ${target.width}x${target.height} grid:\n${refusals.map((i) => `${i.code} ${i.message}`).join("\n")}`);
  }
  const output = resolve(outFirmware);
  const outputDir = dirname(output);
  const projectDir = join(outputDir, "gen-esp32");
  const mainDir = join(projectDir, "main");
  const buildDir = join(projectDir, "build");
  const buildId = await esp32BuildId(app, board);
  const debugStateEnd = Math.max(
    1,
    ...app.debugSlots.map((slot) => slot.offset + slot.size),
  );
  // app_debug_state returns a 4-byte-aligned length even when its last slot
  // is a string; include that tail padding in the runtime-owned buffer.
  const debugStateBytes = (debugStateEnd + 3) & ~3;

  await requireFile(join(RUNTIME, "esp32", "sdkconfig.defaults"), "ESP32 sdkconfig defaults");

  await mkdir(mainDir, { recursive: true });
  await Bun.write(join(mainDir, "gen_app.c"), app.c);
  await Bun.write(join(mainDir, "CMakeLists.txt"), mainCmake(debugStateBytes, buildId, board));
  await Bun.write(
    join(projectDir, "CMakeLists.txt"),
    [
      "# GENERATED by vapor/compiler/esp32.ts. DO NOT EDIT.",
      "cmake_minimum_required(VERSION 3.22)",
      "include($ENV{IDF_PATH}/tools/cmake/project.cmake)",
      "idf_build_set_property(MINIMAL_BUILD ON)",
      "project(pocket_vapor)",
      "",
    ].join("\n"),
  );
  await Bun.write(
    join(projectDir, "sdkconfig.defaults"),
    Bun.file(join(RUNTIME, "esp32", "sdkconfig.defaults")),
  );
  // sdkconfig is generated state, not an input. Removing it makes changes to
  // sdkconfig.defaults deterministic while preserving the compiler cache.
  try {
    await unlink(join(projectDir, "sdkconfig"));
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error;
  }

  // Keep the public artifact app-only. A raw merged image fills the address
  // gaps between bootloader, partition table, and app with 0xff, so writing
  // it at offset zero would erase the ESP32's NVS/PHY partitions. The flash
  // command below remains IDF's partition-aware segmented operation.
  await runEspIdf([
    "-C",
    projectDir,
    "-B",
    buildDir,
    "build",
  ]);

  const appImage = join(buildDir, "pocket_vapor.bin");
  await requireFile(appImage, "ESP32 application image");
  await Bun.write(output, Bun.file(appImage));
  const firmware = Bun.file(output);
  await requireFile(output, "ESP32 application image");
  if (firmware.size === 0 || firmware.size > 4 * 1024 * 1024 - 0x10000) {
    throw new Error(`invalid ESP32 application image size ${firmware.size}: ${output}`);
  }
  return {
    romBytes: firmware.size,
    projectDir,
    buildDir,
    buildId,
  };
}
