// vapor/compiler/esp32.ts — package a generated Pocket Vapor app as an
// ESP-IDF application image.
//
// The generated ESP-IDF project is intentionally retained next to the
// firmware. Besides making the build reproducible, this gives the hardware
// scripts a stable project/build directory for `idf.py flash` and monitoring.

import { existsSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { mkdir, unlink } from "node:fs/promises";
import { homedir } from "node:os";
import { admitBoard, boardDefinitions, loadBoard, type VaporBoard } from "./boards.ts";
import { VAPOR_TARGETS, type CompiledApp } from "./compile.ts";

const RUNTIME = resolve(import.meta.dir, "..", "runtime");
export const DEFAULT_BOARD = "meowbit";
export const ESP32P4_DEPENDENCY_LOCK = join(RUNTIME, "esp32p4", "dependencies.lock");
export const ESP32P4_WAVESHARE_REFERENCE_COMMIT = "c39554b3299f86403cd36820f6fa4767c84ef5f1";
export const ESP32P4_WAVESHARE_BSP_VERSION = "1.0.4";
export const ESP32P4_WAVESHARE_BSP_COMMIT = "83cf66c7effd60394c7d2f6eff39b93f2bcf3664";
export const ESP32P4_LVGL_PORT_VERSION = "2.7.2";
export const ESP32P4_LVGL_PORT_RGB565_SWAPPED_COMMIT =
  "327344fee53d0110828bf185f0d9eb1f684e5c80";

const IDF_RELEASES = {
  esp32: { version: "v6.0.2", cacheKey: "v6.0.2" },
  esp32p4: { version: "v5.5.4", cacheKey: "v5.5.4" },
} as const;

export function esp32IdfVersion(board: VaporBoard): "v5.5.4" | "v6.0.2" {
  return IDF_RELEASES[board.chip].version;
}

const ESP32P4_WAVESHARE_COMPONENT = {
  name: "waveshare/esp32_p4_wifi6_touch_lcd_7b",
  version: ESP32P4_WAVESHARE_BSP_VERSION,
} as const;

/** Keep each non-default board's generated project away from the MeowBit
 * project, sdkconfig cache, and managed-component lockfile. */
export function esp32ProjectName(board: VaporBoard): string {
  return board.board === DEFAULT_BOARD ? "gen-esp32" : `gen-esp32-${board.board}`;
}

/** Preserve the existing MeowBit artifact name while preventing another
 * board's firmware or receipt from overwriting it. */
export function esp32ArtifactStem(board: VaporBoard): string {
  return board.board === DEFAULT_BOARD ? "esp32" : `esp32-${board.board}`;
}

function runtimeName(board: VaporBoard): "esp32" | "esp32p4" {
  return board.chip;
}

function flashBytes(board: VaporBoard): number {
  return board.chip === "esp32p4" ? 32 * 1024 * 1024 : 4 * 1024 * 1024;
}

function componentManifest(board: VaporBoard): string | undefined {
  if (board.chip !== "esp32p4") return undefined;
  const component = ESP32P4_WAVESHARE_COMPONENT;
  return [
    "# GENERATED by vapor/compiler/esp32.ts. DO NOT EDIT.",
    "# Hardware reference:",
    `# https://github.com/waveshareteam/ESP32-P4-WIFI6-Touch-LCD-7B/tree/${ESP32P4_WAVESHARE_REFERENCE_COMMIT}/examples/ESP-IDF/10_lvgl_demo_v9`,
    `# BSP v${ESP32P4_WAVESHARE_BSP_VERSION} source commit: ${ESP32P4_WAVESHARE_BSP_COMMIT}`,
    `# esp_lvgl_port post-v${ESP32P4_LVGL_PORT_VERSION} RGB565 API change: ${ESP32P4_LVGL_PORT_RGB565_SWAPPED_COMMIT}`,
    "dependencies:",
    `  ${component.name}: "${component.version}"`,
    // 2.8.0 added LV_COLOR_FORMAT_RGB565_SWAPPED without guarding it for
    // LVGL 9.2, while 2.7.2 includes the LVGL 9.2 software-rotation fixes.
    `  espressif/esp_lvgl_port: "${ESP32P4_LVGL_PORT_VERSION}"`,
    // The official LVGL 9 example owns this application-level constraint;
    // the BSP itself intentionally supports both LVGL 8 and 9.
    '  lvgl/lvgl: "9.2.*"',
    "",
  ].join("\n");
}

function cmakeString(value: string): string {
  return `"${value.replaceAll("\\", "/").replaceAll('"', '\\"')}"`;
}

async function requireFile(path: string, description: string): Promise<void> {
  if (!(await Bun.file(path).exists())) {
    throw new Error(`${description} not found: ${path}`);
  }
}

async function runIdf(
  idfPath: string,
  idfToolsPath: string,
  args: string[],
): Promise<void> {
  // export.sh wires the matching Python virtualenv and Xtensa toolchain into
  // PATH. Positional arguments keep paths/data out of the shell program.
  const configuredShell = process.env.SHELL;
  const shell =
    configuredShell &&
    existsSync(configuredShell) &&
    (basename(configuredShell) === "bash" || basename(configuredShell) === "zsh")
      ? configuredShell
      : Bun.which("zsh") ?? Bun.which("bash");
  if (!shell) throw new Error("ESP-IDF requires bash or zsh to source export.sh");
  const child = Bun.spawn(
    [
      shell,
      "-lc",
      'source "$1/export.sh" && shift && exec idf.py "$@"',
      "pocket-vapor-idf",
      idfPath,
      ...args,
    ],
    {
      env: {
        ...process.env,
        IDF_PATH: idfPath,
        IDF_TOOLS_PATH: idfToolsPath,
      },
      stdout: "inherit",
      stderr: "inherit",
    },
  );
  const exitCode = await child.exited;
  if (exitCode !== 0) {
    throw new Error(`ESP-IDF command failed (${exitCode}): idf.py ${args.join(" ")}`);
  }
}

export interface EspIdfEnvironment {
  idfPath: string;
  idfToolsPath: string;
  idfVersion: "v5.5.4" | "v6.0.2";
}

function firstDirectory(
  explicit: string | undefined,
  candidates: string[],
  marker: string,
): string {
  if (explicit) return resolve(explicit);
  return (
    candidates
      .map((candidate) => resolve(candidate))
      .find((candidate) => existsSync(join(candidate, marker))) ??
    resolve(candidates[0])
  );
}

/** Locate the board's explicit, cached, or standard ESP-IDF installation. */
export function resolveEspIdfEnvironment(
  board: VaporBoard = loadBoard(DEFAULT_BOARD),
): EspIdfEnvironment {
  const home = homedir();
  const release = IDF_RELEASES[board.chip];
  return {
    idfPath: firstDirectory(
      process.env.IDF_PATH,
      [
        join(home, "Library", "Caches", "esp-idf", release.cacheKey),
        join(home, "esp", "esp-idf"),
      ],
      "export.sh",
    ),
    idfToolsPath: firstDirectory(
      process.env.IDF_TOOLS_PATH,
      [
        join(home, "Library", "Caches", "espressif"),
        join(home, ".espressif"),
      ],
      "python_env",
    ),
    idfVersion: release.version,
  };
}

async function requireMatchingIdfRelease(environment: EspIdfEnvironment): Promise<void> {
  const versionFile = join(environment.idfPath, "tools", "cmake", "version.cmake");
  await requireFile(versionFile, `${environment.idfVersion} ESP-IDF version metadata`);
  const source = await Bun.file(versionFile).text();
  const part = (name: "MAJOR" | "MINOR" | "PATCH"): string | undefined =>
    source.match(new RegExp(`set\\(IDF_VERSION_${name}\\s+([0-9]+)\\)`))?.[1];
  const actual = `v${part("MAJOR")}.${part("MINOR")}.${part("PATCH")}`;
  if (actual !== environment.idfVersion) {
    throw new Error(
      `ESP-IDF release mismatch: ${environment.idfPath} is ${actual}, but this board requires ${environment.idfVersion}`,
    );
  }
}

/** Run a command in the matching ESP-IDF environment used by the builder. */
export async function runEspIdf(
  args: string[],
  environment: EspIdfEnvironment = resolveEspIdfEnvironment(),
): Promise<void> {
  const { idfPath, idfToolsPath } = environment;
  await requireFile(join(idfPath, "export.sh"), "ESP-IDF export script");
  await runIdf(idfPath, idfToolsPath, args);
}

function mainCmake(debugStateBytes: number, buildId: string, board: VaporBoard): string {
  const target = VAPOR_TARGETS.esp32;
  const runtime = runtimeName(board);
  const sources = [
    join(RUNTIME, "vapor_core.c"),
    join(RUNTIME, runtime, `vapor_${runtime}.c`),
    "gen_app.c",
  ];
  const definitions = [
    `VP_GRID_W=${target.width}`,
    `VP_GRID_H=${target.height}`,
    `VP_STR_CAP=${target.strCap}`,
    `VP_VIEW_CAP=${target.poolCap}`,
    `VP_DEBUG_STATE_BYTES=${debugStateBytes}`,
    `VP_BUILD_ID=\\"${buildId}\\"`,
    ...boardDefinitions(board),
  ];

  const requirements = board.chip === "esp32p4"
    ? "waveshare__esp32_p4_wifi6_touch_lcd_7b esp_driver_uart esp_timer vfs"
    : "esp_driver_gpio esp_driver_spi esp_driver_uart esp_timer vfs";

  return [
    "# GENERATED by vapor/compiler/esp32.ts. DO NOT EDIT.",
    "idf_component_register(",
    "  SRCS",
    ...sources.map((source) => `    ${cmakeString(source)}`),
    `  INCLUDE_DIRS ${cmakeString(RUNTIME)}`,
    `  REQUIRES ${requirements}`,
    ")",
    "",
    "target_compile_definitions(${COMPONENT_LIB} PRIVATE",
    ...definitions.map((definition) => `  ${definition}`),
    ")",
    "",
  ].join("\n");
}

export interface Esp32BuildResult {
  romBytes: number;
  projectDir: string;
  buildDir: string;
  buildId: string;
  idfEnvironment: EspIdfEnvironment;
}

/** Identity of the generated app plus every source/config input flashed.
 * The board contributes exactly its derived definitions, so a board file
 * refactor that keeps the definitions byte-identical keeps the id. */
export async function esp32BuildId(app: CompiledApp, board: VaporBoard): Promise<string> {
  const hasher = new Bun.CryptoHasher("sha256");
  const runtime = runtimeName(board);
  const idfVersion = IDF_RELEASES[board.chip].version;
  hasher.update(`${idfVersion}\n${JSON.stringify(boardDefinitions(board))}\n`);
  const manifest = componentManifest(board);
  // Classic ESP32 boards had no component manifest in their historical hash
  // preimage. Do not insert an empty-manifest newline and invalidate receipts.
  if (manifest) hasher.update(`${manifest}\n`);
  hasher.update(`${app.c}\n`);
  const inputs = [
    join(RUNTIME, "vapor.h"),
    join(RUNTIME, "vapor_core.c"),
    join(RUNTIME, runtime, `vapor_${runtime}.c`),
    join(RUNTIME, runtime, "sdkconfig.defaults"),
  ];
  if (board.chip === "esp32p4") inputs.push(ESP32P4_DEPENDENCY_LOCK);
  for (const path of inputs) {
    hasher.update(await Bun.file(path).arrayBuffer());
  }
  return hasher.digest("hex").slice(0, 16);
}

export async function buildEsp32Firmware(
  app: CompiledApp,
  outFirmware: string,
  board: VaporBoard = loadBoard(DEFAULT_BOARD),
): Promise<Esp32BuildResult> {
  const target = VAPOR_TARGETS.esp32;
  const refusals = admitBoard({ buttonsUsed: app.buttonsUsed }, board, target).filter(
    (issue) => issue.severity === "error",
  );
  if (refusals.length > 0) {
    throw new Error(`board ${board.board} cannot host the ${target.width}x${target.height} grid:\n${refusals.map((i) => `${i.code} ${i.message}`).join("\n")}`);
  }
  const output = resolve(outFirmware);
  const outputDir = dirname(output);
  const runtime = runtimeName(board);
  const projectDir = join(outputDir, esp32ProjectName(board));
  const mainDir = join(projectDir, "main");
  const buildDir = join(projectDir, "build");
  const idfEnvironment = resolveEspIdfEnvironment(board);
  const buildId = await esp32BuildId(app, board);
  const debugStateEnd = Math.max(
    1,
    ...app.debugSlots.map((slot) => slot.offset + slot.size),
  );
  // app_debug_state returns a 4-byte-aligned length even when its last slot
  // is a string; include that tail padding in the runtime-owned buffer.
  const debugStateBytes = (debugStateEnd + 3) & ~3;

  await requireFile(join(RUNTIME, runtime, "sdkconfig.defaults"), `${board.chip} sdkconfig defaults`);
  if (board.chip === "esp32p4") {
    await requireFile(ESP32P4_DEPENDENCY_LOCK, "ESP32-P4 managed-component lock");
  }

  await mkdir(mainDir, { recursive: true });
  await Bun.write(join(mainDir, "gen_app.c"), app.c);
  await Bun.write(join(mainDir, "CMakeLists.txt"), mainCmake(debugStateBytes, buildId, board));
  const manifest = componentManifest(board);
  if (manifest) await Bun.write(join(mainDir, "idf_component.yml"), manifest);
  if (board.chip === "esp32p4") {
    await Bun.write(join(projectDir, "dependencies.lock"), Bun.file(ESP32P4_DEPENDENCY_LOCK));
  }
  await Bun.write(
    join(projectDir, "CMakeLists.txt"),
    [
      "# GENERATED by vapor/compiler/esp32.ts. DO NOT EDIT.",
      "cmake_minimum_required(VERSION 3.22)",
      ...(board.chip === "esp32p4" ? ['set(IDF_TARGET "esp32p4")'] : []),
      "include($ENV{IDF_PATH}/tools/cmake/project.cmake)",
      "idf_build_set_property(MINIMAL_BUILD ON)",
      "project(pocket_vapor)",
      "",
    ].join("\n"),
  );
  await Bun.write(
    join(projectDir, "sdkconfig.defaults"),
    Bun.file(join(RUNTIME, runtime, "sdkconfig.defaults")),
  );
  // sdkconfig is generated state, not an input. Removing it makes changes to
  // sdkconfig.defaults deterministic while preserving the compiler cache.
  try {
    await unlink(join(projectDir, "sdkconfig"));
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error;
  }

  // Keep the public artifact app-only. A raw merged image fills the address
  // gaps between bootloader, partition table, and app with 0xff, so writing
  // it at offset zero would erase the ESP32's NVS/PHY partitions. The flash
  // command below remains IDF's partition-aware segmented operation.
  await requireFile(
    join(idfEnvironment.idfPath, "export.sh"),
    `${idfEnvironment.idfVersion} ESP-IDF export script`,
  );
  await requireMatchingIdfRelease(idfEnvironment);
  await runIdf(idfEnvironment.idfPath, idfEnvironment.idfToolsPath, [
    "-C", projectDir, "-B", buildDir, "build",
  ]);
  if (board.chip === "esp32p4") {
    const generatedLock = await Bun.file(join(projectDir, "dependencies.lock")).text();
    const pinnedLock = await Bun.file(ESP32P4_DEPENDENCY_LOCK).text();
    if (generatedLock !== pinnedLock) {
      throw new Error(
        `ESP-IDF changed the pinned component lock; review and update ${ESP32P4_DEPENDENCY_LOCK}`,
      );
    }
  }

  const appImage = join(buildDir, "pocket_vapor.bin");
  await requireFile(appImage, "ESP32 application image");
  await Bun.write(output, Bun.file(appImage));
  const firmware = Bun.file(output);
  await requireFile(output, "ESP32 application image");
  const maxAppBytes = flashBytes(board) - 0x10000;
  if (firmware.size === 0 || firmware.size > maxAppBytes) {
    throw new Error(
      `invalid ${board.chip} application image size ${firmware.size} (limit ${maxAppBytes}): ${output}`,
    );
  }
  return {
    romBytes: firmware.size,
    projectDir,
    buildDir,
    buildId,
    idfEnvironment,
  };
}
