export {
  pushButtonHandlerBlock,
  onFrame,
  onButtonPress,
  onAxisDelta,
  createSpriteAnimation,
  analogX,
  analogY,
  analogRaw,
  rightAnalogRaw,
  rightAnalogX,
  rightAnalogY,
  type ButtonPressOptions,
  type AxisDeltaOptions,
  type SpriteAnimationOptions,
} from "./frame-vue-vapor.ts";
