// GENERATED — do not edit; run `bun contracts/spec/gen-rust.ts`.
export type * from "./numeric-vue-vapor.ts";
export type StyleClass = string & { readonly __style?: true };
import type { i32, f32, f64, Color, u32 } from "./numeric-vue-vapor.ts";
export type VaporPlainNumber = number & { readonly __type?: never; readonly __newtype?: never };
export type VaporNumericResult<T extends number> = T extends VaporPlainNumber ? number : T;
export declare function len<T>(value: string | readonly T[]): i32;
export declare function trunc(value: f32 | f64): i32;
export declare function floor(value: f32 | f64): i32;
export declare function ceil(value: f32 | f64): i32;
export declare function round(value: f32 | f64): i32;
export declare function idiv<T extends number>(value: T, other: NoInfer<T> | VaporPlainNumber): VaporNumericResult<T>;
export declare function imod<T extends number>(value: T, other: NoInfer<T> | VaporPlainNumber): VaporNumericResult<T>;
export declare function min<T extends number>(value: T, other: NoInfer<T> | VaporPlainNumber): VaporNumericResult<T>;
export declare function max<T extends number>(value: T, other: NoInfer<T> | VaporPlainNumber): VaporNumericResult<T>;
export declare function abs<T extends number>(value: T): VaporNumericResult<T>;
export declare function clamp<T extends number>(value: T, other: NoInfer<T> | VaporPlainNumber, upper: NoInfer<T> | VaporPlainNumber): VaporNumericResult<T>;
export declare function fixed(value: f32 | f64, digits: i32): string;
export declare function __colorBits(value: Color): u32;
export declare function __colorText(value: Color | undefined, missing?: string): string;
