[package]
name = "pocket-vue-sfc-lab"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
pocket_vapor = { path = "../../engine/crates/pocket-vapor" }

[features]
default = []
std = ["pocket_vapor/std"]

[profile.dev]
overflow-checks = false

[profile.release]
overflow-checks = false
