// tests/ranger-scope.test.ts — M0 scope acceptance (SWF-less).
//
// Asserts the M0 deliverables from docs/SWF_TYPESCRIPT_REWRITE_RULES.md §10:
// evidence-based scene scope (IN_SCOPE / OUT_OF_SCOPE), draft LINKAGE /
// ALLOWED_KEYS, the four inventories (ClipActions+handlers / Key-call sites
// / external / sounds), the c/d/e execution-order decision, AND the
// contract acceptance that out-of-scope attachMovie IDs make the COOK FAIL
// (assertCookLinkage/validateCookScope throw; the runtime resolveLinkage
// fail-soft gate stays separate) — all against the checked-in compact facts
// in apps/ranger/m0-inventory.json (generated by tools/ranger-cook/scan.ts
// from RANGER_SWF; facts/IDs/counts only).
// This test never needs the SWF: `bun test tests/ranger-scope.test.ts`.
import { describe, expect, test } from "bun:test";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  ALLOWED_KEYS,
  CookScopeError,
  EXECUTION_ORDER,
  IN_SCOPE,
  IN_SCOPE_SOUNDS,
  LINKAGE,
  LINKAGE_EVIDENCE,
  OUT_OF_SCOPE,
  OUT_OF_SCOPE_IDS,
  ROOT_FRAMES,
  SOUND_SCOPE_RATIONALE,
  STAGE_BG_ABGR,
  STAGE_FPS,
  STAGE_H,
  STAGE_W,
  allowedKeyMisses,
  assertCookLinkage,
  isAllowedKey,
  resolveLinkage,
  unknownLinkageHits,
  validateCookScope,
} from "../apps/ranger/scope.ts";
import { resolveSwfPath } from "../tools/ranger-cook/scan.ts";
import { CLIP_EVENT_NAMES } from "../tools/ranger-cook/scan.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (rel: string): string => readFileSync(join(ROOT, rel), "utf8");

interface Inventory {
  _generatedBy: string;
  _swfRef: string;
  _doNotEdit: boolean;
  header: { stageW: number; stageH: number; frameRate: number; rootFrames: number; background: string | null };
  tagCounts: Record<string, number>;
  doAbc: number;
  rootLabels: { frame: number; name: string }[];
  exportAssets: { name: string; charId: number; exports: number }[];
  exportTotals: { rows: number; uniqueNames: number };
  sounds: { id: number; formatName: string; rateHz: number; bits: number; channels: number; samples: number; dataBytes: number }[];
  soundScope: {
    reachableSounds: number[];
    uncertainSounds: number[];
    inScopeSounds: number[];
    literalSpawnRefs: { emitterName: string; spawnerLoc: string }[];
    staticPlacedEmitters: string[];
    emitterHostCount: number;
    triggerTotal: number;
    rationale: string;
  };
  startSoundTriggers: { soundId: number; n: number; syncStop: number }[];
  buttonSoundRefs: number[];
  streamHeads: { count: number; nonEmpty: number };
  bitmaps: { id: number; tag: string; format: number; w: number; h: number }[];
  placeObject2: { count: number; named: number; withClipActions: number };
  placementSummary: { edges: number; containers: number; rootPlacedChars: number[]; graphHash: string };
  clipActionsWidth: number;
  clipEvents: { flag: string; name: string; n: number }[];
  clipKeyCodes: number[];
  clipUncertain: string[];
  buttons2: { count: number; condBlocks: number; condKeyPress: number[]; noAction: number };
  actionScopes: {
    doActionTags: number; doInitActionTags: number;
    doActionRecordsInclEnd: number; doActionRecordsExclEnd: number;
    doInitActionRecordsInclEnd: number; doInitActionRecordsExclEnd: number;
    clipActionRecordsInclEnd: number; clipActionRecordsExclEnd: number;
    buttonCondRecordsInclEnd: number; buttonCondRecordsExclEnd: number;
    endTerminators: number; totalRecordsInclEnd: number; totalRecordsExclEnd: number;
  };
  contractBaselineApprox: number;
  baselineNote: string;
  functionNames: Record<string, number>;
  attachMovieCooccurrence: { id: string; blocks: number }[];
  attachDynamicPossible: boolean;
  attachMovieStatic: { id: string; n: number }[];
  attachMovieDynamicSites: { loc: string; kind: string }[];
  opHistAllSourcesTop: Record<string, number>;
  handlers: Record<string, number>;
  keyInventory: {
    totalCallMethodSites: number; totalCallFunctionSites: number; totalNewMethodSites: number;
    otherCalls: number; resolvedIsDown: number; resolvedGetCode: number;
    isDownArgLiterals: { code: number; n: number }[];
    isDownArgVars: { name: string; n: number }[];
    getCodeArgKinds: { kind: string; n: number }[];
    unresolved: { loc: string; kind: string; method: string; reason: string }[];
  };
  pushIntUniverseTop: { code: number; n: number }[];
  pushIntUniverseNote: string;
  methodCallsTop: { method: string; kind: string; n: number; sigs: Record<string, number> }[];
  methodCallDistinct: number;
  pushDoubles: { distinct: number; nonFinite: number; top: { v: number; n: number }[] };
  clipSignals: Record<string, Record<string, number>>;
  keySlotSignals: Record<string, number>;
  memberNames: string[];
  external: { getUrls: { url: string; target: string; n: number }[]; getUrl2Count: number; apiHits: Record<string, number> };
  soundRefs: Record<string, number>;
  stringCount: number;
  stringHash: string;
  uncertainty: string[];
}

const inv = JSON.parse(read("apps/ranger/m0-inventory.json")) as Inventory;
const exportByName = new Map(inv.exportAssets.map((a) => [a.name, a]));

/** null when git is unavailable (env without git): caller skips the check. */
function git(args: string[]): string | null {
  try {
    return execFileSync("git", args, { cwd: ROOT, encoding: "utf8" });
  } catch (e) {
    if ((e as { code?: string }).code === "ENOENT") return null;
    throw e;
  }
}

describe("ranger M0 scene scope", () => {
  test("IN_SCOPE is exactly the four ported phases", () => {
    expect([...IN_SCOPE]).toEqual(["title", "fight", "clear", "over"]);
  });

  test("OUT_OF_SCOPE is a documented, disjoint skip list incl. sound emitters", () => {
    expect(OUT_OF_SCOPE.length).toBeGreaterThan(0);
    expect(new Set(OUT_OF_SCOPE).size).toBe(OUT_OF_SCOPE.length);
    for (const s of OUT_OF_SCOPE) {
      expect(s.length).toBeGreaterThan(0);
      expect((IN_SCOPE as readonly string[]).includes(s)).toBe(false);
    }
    expect((OUT_OF_SCOPE as readonly string[]).includes("sound-emitters")).toBe(true);
  });

  test("stage constants match the measured SWF header", () => {
    expect(STAGE_W).toBe(inv.header.stageW);
    expect(STAGE_H).toBe(inv.header.stageH);
    expect(STAGE_FPS).toBe(inv.header.frameRate);
    expect(ROOT_FRAMES).toBe(inv.header.rootFrames);
    expect(STAGE_W).toBe(600);
    expect(STAGE_H).toBe(330);
    expect(STAGE_FPS).toBe(24);
    expect(ROOT_FRAMES).toBe(19);
    expect(inv.header.background).toBe("#003399");
    expect(STAGE_BG_ABGR).toBe(0xff993300);
  });
});

describe("ranger M0 LINKAGE draft (positional evidence)", () => {
  test("every LINKAGE entry is an observed export with a matching v<charId>", () => {
    expect(Object.keys(LINKAGE).length).toBe(20);
    for (const [id, variant] of Object.entries(LINKAGE)) {
      expect(variant).toMatch(/^v\d+$/);
      const exp = exportByName.get(id);
      expect(exp).toBeDefined();
      expect(variant).toBe(`v${exp!.charId}`);
    }
  });

  test("LINKAGE evidence classes are complete and honest", () => {
    expect(Object.keys(LINKAGE_EVIDENCE).sort()).toEqual(Object.keys(LINKAGE).sort());
    const staticIds = new Set(inv.attachMovieStatic.map((a) => a.id));
    for (const [id, cls] of Object.entries(LINKAGE_EVIDENCE)) {
      expect(["S", "P", "F"]).toContain(cls);
      if (cls === "S") expect(staticIds.has(id)).toBe(true);
    }
    // (P)laced entries have root placement evidence (not spawn claims).
    for (const id of Object.entries(LINKAGE_EVIDENCE).filter(([, c]) => c === "P").map(([k]) => k)) {
      expect(inv.placementSummary.rootPlacedChars.includes(exportByName.get(id)!.charId)).toBe(true);
    }
    // (F)amily entries are exactly the documented zero-static-evidence set.
    const fams = Object.entries(LINKAGE_EVIDENCE).filter(([, c]) => c === "F").map(([k]) => k).sort();
    expect(fams).toEqual(["ef_hit2", "ef_hit3", "ef_hit4", "ef_hit5", "ef_hit6", "tobi1"]);
    // No sound emitter hides in the spawn table.
    for (const id of Object.keys(LINKAGE)) {
      expect(id.startsWith("se_")).toBe(false);
    }
  });

  test("OUT_OF_SCOPE_IDS are real exports outside LINKAGE, incl. all 42 se_*", () => {
    expect(OUT_OF_SCOPE_IDS.length).toBeGreaterThan(0);
    for (const id of OUT_OF_SCOPE_IDS) {
      expect(exportByName.has(id)).toBe(true);
      expect(LINKAGE[id]).toBeUndefined();
    }
    const seIds = (OUT_OF_SCOPE_IDS as readonly string[]).filter((id) => id.startsWith("se_"));
    expect(seIds.length).toBe(42);
    expect(seIds.includes("se_101")).toBe(true);
  });

  test("every positional static spawn is classified in- or out-of-scope", () => {
    expect(inv.attachMovieStatic.length).toBeGreaterThan(0);
    const out = new Set<string>(OUT_OF_SCOPE_IDS);
    for (const ref of inv.attachMovieStatic) {
      expect(LINKAGE[ref.id] !== undefined || out.has(ref.id)).toBe(true);
    }
    // Spot pins from positional evidence: slice FX spawnable, stage
    // containers and story emitters rejected.
    expect(LINKAGE["ef_hit12"]).toBe("v1171");
    expect(LINKAGE["tobi1"]).toBe("v185");
    expect(LINKAGE["toujouS10"]).toBeUndefined();
    expect(LINKAGE["se_101"]).toBeUndefined();
    expect(out.has("toujouS10")).toBe(true);
    expect(out.has("se_101")).toBe(true);
  });

  test("dynamic-linkage sites are listed exhaustively, never silently classified", () => {
    expect(inv.attachMovieDynamicSites.length).toBe(21);
    expect(inv.attachDynamicPossible).toBe(true);
    for (const s of inv.attachMovieDynamicSites) {
      expect(s.loc.length).toBeGreaterThan(0);
      expect(["callMethod", "callFunction"]).toContain(s.kind);
    }
  });
});

describe("ranger M0 cook scope gate (fail-hard) vs runtime gate (fail-soft)", () => {
  test("cook gate passes every in-scope LINKAGE id", () => {
    for (const id of Object.keys(LINKAGE)) {
      expect(assertCookLinkage(id)).toBe(LINKAGE[id]);
    }
    validateCookScope(Object.keys(LINKAGE));
    validateCookScope([]);
  });

  test("cook gate FAILS on every out-of-scope id (M0 acceptance)", () => {
    for (const id of OUT_OF_SCOPE_IDS) {
      let err: unknown = null;
      try {
        assertCookLinkage(id);
      } catch (e) {
        err = e;
      }
      expect(err instanceof CookScopeError).toBe(true);
      expect((err as CookScopeError).scopeClass).toBe("out-of-scope");
      expect((err as CookScopeError).linkageId).toBe(id);
    }
  });

  test("cook gate FAILS on unknown ids and on observed mixed ref sets", () => {
    let unknown: unknown = null;
    try {
      assertCookLinkage("__not_a_linkage__");
    } catch (e) {
      unknown = e;
    }
    expect(unknown instanceof CookScopeError).toBe(true);
    expect((unknown as CookScopeError).scopeClass).toBe("unknown");
    // The observed positional static set contains out-of-scope spawns
    // (event/maku/toujou...), so cooking it raw must fail; cooking the
    // in-scope projection must pass.
    const observed = inv.attachMovieStatic.map((a) => a.id);
    expect(observed.includes("maku")).toBe(true);
    let mixed: unknown = null;
    try {
      validateCookScope(observed);
    } catch (e) {
      mixed = e;
    }
    expect(mixed instanceof CookScopeError).toBe(true);
    validateCookScope(observed.filter((id) => LINKAGE[id] !== undefined));
  });

  test("runtime gate stays fail-soft (undefined + counter, no throw)", () => {
    expect(Object.keys(unknownLinkageHits).length).toBe(0);
    for (const id of Object.keys(LINKAGE)) {
      expect(resolveLinkage(id)).toBe(LINKAGE[id]);
    }
    expect(resolveLinkage("toujouS10")).toBeUndefined();
    expect(resolveLinkage("__not_a_linkage__")).toBeUndefined();
    expect(unknownLinkageHits["toujouS10"]).toBe(1);
    expect(unknownLinkageHits["__not_a_linkage__"]).toBe(1);
  });
});

describe("ranger M0 ALLOWED_KEYS draft", () => {
  test("ALLOWED_KEYS equals the observed instance-name set (sorted, unique)", () => {
    const names = [...inv.memberNames].sort();
    expect([...ALLOWED_KEYS]).toEqual(names);
    expect(new Set(ALLOWED_KEYS).size).toBe(ALLOWED_KEYS.length);
    expect(ALLOWED_KEYS.length).toBeGreaterThan(0);
  });

  test("key gate allows observed slots and counts misses", () => {
    expect(isAllowedKey("kage")).toBe(true);
    expect(isAllowedKey("hpb")).toBe(true);
    expect(isAllowedKey("hit1")).toBe(true);
    expect(isAllowedKey("__proto__")).toBe(false);
    expect(isAllowedKey("constructor")).toBe(false);
    expect(allowedKeyMisses["__proto__"]).toBe(1);
    expect(allowedKeyMisses["constructor"]).toBe(1);
  });
});

describe("ranger M0 inventories", () => {
  test("(a) ClipActions/event handlers: precise SWF names, widths, no assigned handlers", () => {
    // Full ClipEventFlags map pinned independently (spec 1<<0..1<<18):
    // observed 0x800 is Release, not ReleaseOutside.
    expect(CLIP_EVENT_NAMES).toEqual({
      0x1: "Load",
      0x2: "EnterFrame",
      0x4: "Unload",
      0x8: "MouseMove",
      0x10: "MouseDown",
      0x20: "MouseUp",
      0x40: "KeyDown",
      0x80: "KeyUp",
      0x100: "Data",
      0x200: "Initialize",
      0x400: "Press",
      0x800: "Release",
      0x1000: "ReleaseOutside",
      0x2000: "RollOver",
      0x4000: "RollOut",
      0x8000: "DragOver",
      0x10000: "DragOut",
      0x20000: "KeyPress",
      0x40000: "Construct",
    });
    expect(inv.clipActionsWidth).toBe(32);
    expect(inv.clipKeyCodes).toEqual([]);
    expect(inv.clipUncertain).toEqual([]);
    expect(inv.clipEvents).toEqual([
      { flag: "0x1", name: "Load", n: 41 },
      { flag: "0x2", name: "EnterFrame", n: 50 },
      { flag: "0x10", name: "MouseDown", n: 26 },
      { flag: "0x40", name: "KeyDown", n: 18 },
      { flag: "0x800", name: "Release", n: 2 },
    ]);
    // Per-frame loop carries the input/collision polling.
    expect(inv.clipSignals["0x2:EnterFrame"]["_parent"]).toBeGreaterThan(0);
    // Key-config variables live in the keydown class.
    for (const k of ["keyL", "keyR", "keyU", "keyD", "key1", "key2", "key3"]) {
      expect(inv.keySlotSignals[k] ?? 0).toBeGreaterThan(0);
    }
    expect(inv.handlers).toEqual({});
    expect(Object.keys(inv.functionNames).length).toBe(16);
    expect(inv.functionNames["yarare"]).toBe(1);
    expect(inv.functionNames["damage"]).toBe(1);
    // Buttons carry no actions (decorative only).
    expect(inv.buttons2.count).toBe(2);
    expect(inv.buttons2.condBlocks).toBe(0);
    expect(inv.buttons2.noAction).toBe(2);
    expect(inv.actionScopes.doInitActionTags).toBe(0);
    expect(inv.actionScopes.doInitActionRecordsExclEnd).toBe(0);
  });

  test("(b) Key inventory: exhaustive decoded call sites, 7 remappable slots, zero literals", () => {
    const k = inv.keyInventory;
    // Exhaustiveness identity: no call site silently dropped.
    expect(k.totalCallMethodSites).toBe(2607);
    expect(k.totalCallFunctionSites).toBe(6);
    expect(k.totalNewMethodSites).toBe(0);
    expect(k.otherCalls + k.resolvedIsDown + k.resolvedGetCode + k.unresolved.length).toBe(
      k.totalCallMethodSites + k.totalCallFunctionSites + k.totalNewMethodSites,
    );
    expect(k.resolvedIsDown).toBe(54);
    expect(k.resolvedGetCode).toBe(1);
    expect(k.unresolved).toEqual([]);
    // All isDown args are remappable _root.key* property vars — exactly the
    // 7 slots, zero hardcoded literals. No default button mapping invented.
    expect(k.isDownArgLiterals).toEqual([]);
    const slots = new Set(k.isDownArgVars.map((v) => v.name));
    expect([...slots].sort()).toEqual([
      "var(_root).key1",
      "var(_root).key2",
      "var(_root).key3",
      "var(_root).keyD",
      "var(_root).keyL",
      "var(_root).keyR",
      "var(_root).keyU",
    ]);
    expect(k.isDownArgVars.reduce((a, v) => a + v.n, 0)).toBe(54);
    expect(k.getCodeArgKinds).toEqual([{ kind: "arity-0", n: 1 }]);
    // Raw Push-int universe is labeled as NOT arguments (field rename sticks).
    expect(inv.pushIntUniverseNote.length).toBeGreaterThan(0);
    expect((inv as unknown as Record<string, unknown>)["keyCandidates"]).toBeUndefined();
    expect((inv as unknown as Record<string, unknown>)["isDownCandidates"]).toBeUndefined();
    expect((inv as unknown as Record<string, unknown>)["keyCodesTop"]).toBeUndefined();
  });

  test("(c) external interactions: U-1 absent", () => {
    expect(inv.external.getUrls).toEqual([]);
    expect(inv.external.getUrl2Count).toBe(0);
    expect(inv.external.apiHits).toEqual({});
    expect(inv.opHistAllSourcesTop["GetURL"] ?? 0).toBe(0);
    expect(inv.opHistAllSourcesTop["GetURL2"] ?? 0).toBe(0);
  });

  test("(d) sounds: 36 embedded MP3s, trigger-covered, 1 reachable / 35 uncertain / 0 in scope", () => {
    expect(inv.sounds.length).toBe(36);
    for (const s of inv.sounds) {
      expect(s.formatName).toBe("MP3");
      expect(s.rateHz).toBe(11025);
      expect(s.bits).toBe(16);
      expect(s.channels).toBe(1);
    }
    expect(inv.soundScope.triggerTotal).toBe(43);
    expect(inv.soundScope.emitterHostCount).toBe(36);
    const triggered = new Map(inv.startSoundTriggers.map((t) => [t.soundId, t.n]));
    expect([...triggered.values()].reduce((a, b) => a + b, 0)).toBe(43);
    for (const s of inv.sounds) {
      expect(triggered.get(s.id) ?? 0).toBeGreaterThan(0);
    }
    // Reachability, not trigger-coverage, decides scope.
    expect(inv.soundScope.reachableSounds).toEqual([198]);
    expect(inv.soundScope.uncertainSounds.length).toBe(35);
    expect(inv.soundScope.inScopeSounds).toEqual([]);
    expect(inv.soundScope.literalSpawnRefs).toEqual([
      { emitterName: "se_101", spawnerLoc: "tag#72602:DoAction@root:f15" },
    ]);
    expect(inv.soundScope.staticPlacedEmitters).toEqual([]);
    expect(inv.soundScope.rationale).toBe(SOUND_SCOPE_RATIONALE);
    expect([...IN_SCOPE_SOUNDS]).toEqual([]);
    expect(inv.buttonSoundRefs).toEqual([]);
    expect(inv.streamHeads).toEqual({ count: 622, nonEmpty: 0 });
    expect(inv.tagCounts["SoundStreamBlock"] ?? 0).toBe(0);
    expect(inv.soundRefs).toEqual({});
  });

  test("action scopes: 100,512 baseline is DoAction excl. End; totals are wider scopes", () => {
    const a = inv.actionScopes;
    expect(a.doActionTags).toBe(1551);
    expect(a.doActionRecordsExclEnd).toBe(100512);
    expect(a.doActionRecordsExclEnd).toBe(inv.contractBaselineApprox);
    // Part identities (independent of the generator's aggregate).
    expect(
      a.doActionRecordsExclEnd + a.doInitActionRecordsExclEnd +
      a.clipActionRecordsExclEnd + a.buttonCondRecordsExclEnd,
    ).toBe(a.totalRecordsExclEnd);
    expect(
      a.doActionRecordsInclEnd + a.doInitActionRecordsInclEnd +
      a.clipActionRecordsInclEnd + a.buttonCondRecordsInclEnd,
    ).toBe(a.totalRecordsInclEnd);
    expect(a.totalRecordsInclEnd - a.totalRecordsExclEnd).toBe(a.endTerminators);
    expect(a.endTerminators).toBe(1688);
    // Op histogram End framing cross-checks the terminator count.
    expect(inv.opHistAllSourcesTop["End"]).toBe(a.endTerminators);
    expect(a.clipActionRecordsExclEnd).toBe(10559);
    expect(a.buttonCondRecordsExclEnd).toBe(0);
    expect(inv.baselineNote.length).toBeGreaterThan(0);
  });

  test("tag census matches the M0 baseline", () => {
    expect(inv._swfRef).toBe("swf:fws6:root19f");
    expect(inv.doAbc).toBe(0);
    expect(inv.rootLabels).toEqual([]);
    expect(inv.tagCounts["DefineSprite"]).toBe(621);
    expect(inv.tagCounts["ShowFrame"]).toBe(10680);
    expect(inv.tagCounts["PlaceObject2"]).toBe(55100);
    expect(inv.tagCounts["RemoveObject2"]).toBe(2513);
    expect(inv.tagCounts["DoAction"]).toBe(1551);
    expect(inv.tagCounts["DefineSound"]).toBe(36);
    expect(inv.tagCounts["StartSound"]).toBe(43);
    expect(inv.placeObject2).toEqual({ count: 55100, named: 760, withClipActions: 86 });
    // Opcode histogram is fully decoded (only End framing stays structural).
    for (const k of Object.keys(inv.opHistAllSourcesTop)) {
      expect(k.startsWith("op_")).toBe(false);
    }
    expect(inv.opHistAllSourcesTop["Push"]).toBeGreaterThan(0);
    expect(inv.opHistAllSourcesTop["SetMember"]).toBeGreaterThan(0);
    // Bitwise vs boolean opcode names cannot collide: 0x60 is BitAnd
    // (observed once), boolean And/Or at 0x10/0x11 are unobserved here —
    // a rename regression would flip these two pins.
    expect(inv.opHistAllSourcesTop["BitAnd"]).toBe(1);
    expect(inv.opHistAllSourcesTop["And"] ?? 0).toBe(0);
    expect(inv.opHistAllSourcesTop["Or"] ?? 0).toBe(0);
  });

  test("method survey: numeric gotos, hitTest modes, word-swapped doubles", () => {
    const byName = new Map(inv.methodCallsTop.filter((m) => m.kind === "callMethod").map((m) => [m.method, m]));
    // All 72 gotoAndPlay + 695/701 gotoAndStop use literal frame numbers —
    // no label navigation anywhere (FrameLabels are pose markers, M1 note).
    expect(byName.get("gotoAndPlay")!.sigs).toEqual({ "literal-int#1": 72 });
    expect(byName.get("gotoAndStop")!.sigs["literal-int#1"]).toBe(695);
    // hitTest bound mode (single target var) vs shape mode (3-arg).
    expect(byName.get("hitTest")!.sigs).toEqual({
      "property-var#1": 47,
      "unknown,property-var,property-var#3": 18,
    });
    expect(byName.get("attachMovie")!.n).toBe(150);
    expect(inv.methodCallDistinct).toBeGreaterThan(0);
    // SWF doubles are word-swapped: rad/deg factors decode exactly, and no
    // non-finite value leaks through.
    expect(inv.pushDoubles.nonFinite).toBe(0);
    const vals = new Map(inv.pushDoubles.top.map((d) => [d.v, d.n]));
    expect(vals.get(57.29577951308232)).toBe(33);
    expect(vals.get(0.017453292519943295)).toBe(51);
  });
});

describe("ranger M0 c/d/e execution-order decision", () => {
  test("order is concrete b/d/c/e with evidence and a recorded deviation", () => {
    expect([...EXECUTION_ORDER.order]).toEqual([
      "b-display",
      "d-clip-enterframe",
      "c-frame-scripts",
      "e-finalize",
    ]);
    expect(EXECUTION_ORDER.pollingSignalsInEnterFrame.length).toBeGreaterThan(0);
    expect(EXECUTION_ORDER.reactionVerbsInFrameScripts.length).toBeGreaterThan(0);
    expect(EXECUTION_ORDER.deviation.length).toBeGreaterThan(0);
    // Evidence anchors: polling decoded in clip land, reactions in scripts.
    expect(inv.keyInventory.resolvedIsDown).toBeGreaterThan(0);
    expect((inv.methodCallsTop.find((m) => m.method === "gotoAndStop")?.n ?? 0)).toBeGreaterThan(0);
  });
});

describe("ranger M0 metadata hygiene", () => {
  test("compact inventory carries facts/IDs/counts, never decompiler source", () => {
    expect(inv._generatedBy).toBe("tools/ranger-cook/scan.ts");
    expect(inv._doNotEdit).toBe(true);
    expect(inv.uncertainty.length).toBeGreaterThan(0);
    expect(inv.exportTotals).toEqual({ rows: 482, uniqueNames: 132 });
    expect(inv.exportAssets.length).toBe(132);
    expect(new Set(inv.exportAssets.map((a) => a.name)).size).toBe(132);
    expect(inv.stringHash).toMatch(/^[0-9a-f]{8}$/);
    expect(inv.placementSummary.graphHash).toMatch(/^[0-9a-f]{8}$/);
    const raw = read("apps/ranger/m0-inventory.json");
    expect(raw.length).toBeLessThan(96 * 1024);
    const walk = (v: unknown): void => {
      if (typeof v === "string") expect(v.includes("\n")).toBe(false);
      else if (Array.isArray(v)) v.forEach(walk);
      else if (v !== null && typeof v === "object") Object.values(v).forEach(walk);
    };
    walk(inv);
    // Bare-hex event buckets are gone (defect 6 field rename sticks).
    expect(raw.includes('"ev_0x')).toBe(false);
  });

  test("no hardcoded operator SWF paths in M0 sources", () => {
    for (const rel of [
      "tools/ranger-cook/scan.ts",
      "apps/ranger/scope.ts",
      "apps/ranger/m0-inventory.json",
    ]) {
      const src = read(rel);
      expect(src.includes("RANGER_SWF") && rel.endsWith(".json")).toBe(false);
      expect(/[A-Za-z]:\\/.test(src)).toBe(false);
      expect(src.includes("/Users/")).toBe(false);
      expect(src.includes("/home/")).toBe(false);
      // A real ".swf" file reference (not the `swf:` evidence-ref scheme or
      // the `_swfRef`/`swfRef` metadata field names).
      expect(/\.swf\b/.test(src)).toBe(false);
    }
  });

  test("AVM1 tools only: no RABCDAsm, no spawned/child tooling, no new deps", () => {
    const scan = read("tools/ranger-cook/scan.ts");
    expect(scan.toLowerCase().includes("rabcdasm")).toBe(false);
    expect(scan.includes("child_process")).toBe(false);
    expect(scan.includes("spawnSync")).toBe(false);
    expect(scan.includes("spawn(")).toBe(false);
    expect(scan.includes("execFile")).toBe(false);
    const pkg = JSON.parse(read("package.json")) as {
      dependencies: Record<string, string>;
      devDependencies: Record<string, string>;
    };
    for (const dep of ["ffdec", "rabcdasm", "swftools", "ffmpeg"]) {
      expect(pkg.dependencies[dep]).toBeUndefined();
      expect(pkg.devDependencies[dep]).toBeUndefined();
    }
  });

  test("pre-existing ranger assets are intact (no deletes/rewrites)", () => {
    for (const rel of [
      "apps/ranger/pocket.json",
      "apps/ranger/main.tsx",
      "apps/ranger/battle.tsx",
      "apps/ranger/anim.json",
      "apps/ranger/images.json",
      "apps/ranger/sprites.json",
      "apps/ranger/sheets.ts",
      "apps/ranger/bg.png",
      "apps/ranger/p_hpb.png",
      "apps/ranger/e_hpb.png",
      "apps/ranger/v185.png",
      "apps/ranger/v328.png",
    ]) {
      expect(existsSync(join(ROOT, rel))).toBe(true);
    }
  });
});

describe("ranger M0 cook path wiring", () => {
  test("SWF path comes from RANGER_SWF or an argument, never a literal", () => {
    expect(resolveSwfPath({ RANGER_SWF: "/op/in.swf" }, [])).toBe("/op/in.swf");
    expect(resolveSwfPath({}, ["--swf", "/op/arg.swf"])).toBe("/op/arg.swf");
    expect(resolveSwfPath({}, ["/op/pos.swf"])).toBe("/op/pos.swf");
    expect(resolveSwfPath({ RANGER_SWF: "/op/in.swf" }, ["--swf", "/op/arg.swf"])).toBe(
      "/op/arg.swf",
    );
    let threw = false;
    try {
      resolveSwfPath({}, []);
    } catch {
      threw = true;
    }
    expect(threw).toBe(true);
  });
});

describe("ranger M0 ignore boundaries", () => {
  test(".gitignore has narrow cook rules and no repo-global dump rules", () => {
    const ignore = read(".gitignore");
    for (const rule of [
      "tools/ranger-cook/out/**",
      "tools/ranger-cook/in/**",
      "/ffdec-out/",
      "/tools/ranger-cook/**/*.xfl",
    ]) {
      expect(ignore.includes(rule)).toBe(true);
    }
    const lines = ignore.split("\n").map((l) => l.trim());
    // Repo-global dump rules are banned: raw SWF / derived-dump ignores
    // must stay local-only (scoped to cook paths).
    for (const banned of ["*.xfl", "*.swf", "*.mp3"]) {
      expect(lines.includes(banned)).toBe(false);
    }
  });

  test("cook output is git-ignored", () => {
    let out: string | null = null;
    try {
      out = execFileSync("git", ["check-ignore", "-v", "tools/ranger-cook/out/scan.json"], {
        cwd: ROOT,
        encoding: "utf8",
      });
    } catch (e) {
      if ((e as { code?: string }).code === "ENOENT") return;
      if ((e as { status?: number }).status === 1) {
        throw new Error("tools/ranger-cook/out/ is not git-ignored");
      }
      throw e;
    }
    expect(out).not.toBeNull();
  });

  test("no raw SWF or derived dumps inside tracked app paths", () => {
    const skip = new Set(["node_modules", ".git", "dist", ".cache", ".deps", ".pocket-build", "out", "in"]);
    const bad: string[] = [];
    const walkDir = (dir: string): void => {
      for (const name of readdirSync(dir)) {
        if (skip.has(name)) continue;
        const p = join(dir, name);
        if (statSync(p).isDirectory()) {
          if (dir === ROOT && name === "tools") {
            // tools/ may hold ignored cook output; still walk for *.swf.
          }
          walkDir(p);
        } else if (/\.swf$/i.test(name)) {
          bad.push(p);
        }
      }
    };
    for (const d of ["apps", "tools", "tests"]) walkDir(join(ROOT, d));
    for (const name of readdirSync(ROOT)) {
      if (/\.swf$/i.test(name)) bad.push(join(ROOT, name));
    }
    expect(bad).toEqual([]);
    const tracked = git(["ls-files", "*.swf", "*.xfl"]);
    if (tracked === null) return; // no git in this env — fs walk above still ran
    expect(tracked.trim()).toBe("");
  });
});
