import { describe, expect, test } from "bun:test";
import { readFile } from "node:fs/promises";

const root = new URL("../hosts/wm6/vs2005/", import.meta.url);

describe("Windows Mobile 6 VS2005 projects", () => {
  test("uses the Professional SDK ARMV4I smart-device platform", async () => {
    const [solution, project, resource] = await Promise.all([
      readFile(new URL("PocketJS.WM6.sln", root), "utf8"),
      readFile(new URL("PocketJS.WM6.Probe.vcproj", root), "utf8"),
      readFile(new URL("resources/probe.rc", root), "utf8"),
    ]);

    expect(solution).toContain("Microsoft Visual Studio Solution File, Format Version 9.00");
    expect(solution).toContain("Windows Mobile 6 Professional SDK (ARMV4I)");
    expect(project).toContain('Version="8.00"');
    expect(project).toContain('Name="Windows Mobile 6 Professional SDK (ARMV4I)"');
    expect(project).toContain("/subsystem:windowsce,5.02");
    expect(project).toContain("aygshell.lib coredll.lib");
    expect(project.match(/DisableSpecificWarnings="4201"/g)).toHaveLength(2);
    expect(project.match(/TargetMachine="0"/g)).toHaveLength(2);
    expect(project).not.toContain('TargetMachine="1"');
    expect(
      project.match(
        /RemoteDirectory="%CSIDL_PROGRAM_FILES%\\PocketJS\.WM6\.Probe"/g,
      ),
    ).toHaveLength(2);
    expect(
      project.match(
        /RemoteExecutable="%CSIDL_PROGRAM_FILES%\\PocketJS\.WM6\.Probe\\PocketJS\.WM6\.Probe\.exe"/g,
      ),
    ).toHaveLength(2);
    expect(project).not.toContain("Windows Mobile 6 Standard SDK");
    expect(project).toContain('RelativePath=".\\resources\\probe.rc"');
    expect(resource).toMatch(/\bHI_RES_AWARE\s+CEUX\s+\{\s*1\s*\}/);
  });

  test("keeps the probe compatible with the VC8 compiler", async () => {
    const source = await readFile(new URL("src/main.cpp", root), "utf8");

    expect(source).toContain("int WINAPI WinMain");
    expect(source).toContain("SHFullScreen");
    expect(source).toContain("WM_LBUTTONDOWN");
    expect(source).toContain("WM_KEYDOWN");
    expect(source).toContain("CreateCompatibleBitmap");
    expect(source).toContain("CreateFontIndirect");
    expect(source).not.toMatch(/\bCreateFont\s*\(/);
    expect(source).not.toContain("lstrcpyn");
    expect(source).not.toMatch(/\b(auto|nullptr|constexpr|override)\b/);
  });

  test("includes a separate VC8 Pocket Vapor AOT application", async () => {
    const [solution, project, host, generated] = await Promise.all([
      readFile(new URL("PocketJS.WM6.sln", root), "utf8"),
      readFile(new URL("PocketJS.WM6.Vapor.vcproj", root), "utf8"),
      readFile(new URL("src/vapor_main.c", root), "utf8"),
      readFile(new URL("generated/todo.gba.c", root), "utf8"),
    ]);

    expect(solution).toContain('"PocketJS.WM6.Vapor"');
    expect(solution).toContain("{970E99AC-1918-451D-A515-9C23D9C3AC65}");
    expect(project).toContain('Version="8.00"');
    expect(project).toContain('Name="Windows Mobile 6 Professional SDK (ARMV4I)"');
    expect(project).toContain('RelativePath=".\\src\\vapor_main.c"');
    expect(project).toContain('RelativePath=".\\generated\\todo.gba.c"');
    expect(project).toContain(
      'RelativePath="..\\..\\..\\vapor\\runtime\\vapor_core.c"',
    );
    expect(project.match(/DisableSpecificWarnings="4201;4819"/g)).toHaveLength(2);
    expect(project.match(/inline=__inline/g)).toHaveLength(2);
    expect(project.match(/TargetMachine="0"/g)).toHaveLength(2);
    expect(
      project.match(
        /RemoteExecutable="%CSIDL_PROGRAM_FILES%\\PocketJS\.WM6\.Vapor\\PocketJS\.WM6\.Vapor\.exe"/g,
      ),
    ).toHaveLength(2);

    expect(host).toContain("app_init()");
    expect(host).toContain("app_on_button(button)");
    expect(host).toContain("ExtTextOut");
    expect(host).toContain("WM_LBUTTONUP");
    expect(generated).toContain(
      "GENERATED by vapor/compiler/compile.ts. DO NOT EDIT.",
    );
    expect(generated).toContain("const char vp_app_title[] = \"VAPOR TODO\"");
  });
});
