import { describe, expect, test } from "bun:test";
import { readFile } from "node:fs/promises";

const root = new URL("../hosts/wm6/vs2005/", import.meta.url);

describe("Windows Mobile 6 VS2005 projects", () => {
  test("uses the Professional SDK ARMV4I smart-device platform", async () => {
    const [solution, project, resource] = await Promise.all([
      readFile(new URL("PocketJS.WM6.sln", root), "utf8"),
      readFile(new URL("PocketJS.WM6.Probe.vcproj", root), "utf8"),
      readFile(new URL("resources/probe.rc", root), "utf8"),
    ]);

    expect(solution).toContain("Microsoft Visual Studio Solution File, Format Version 9.00");
    expect(solution).toContain("Windows Mobile 6 Professional SDK (ARMV4I)");
    expect(project).toContain('Version="8.00"');
    expect(project).toContain('Name="Windows Mobile 6 Professional SDK (ARMV4I)"');
    expect(project).toContain("/subsystem:windowsce,5.02");
    expect(project).toContain("aygshell.lib coredll.lib");
    expect(project.match(/DisableSpecificWarnings="4201"/g)).toHaveLength(2);
    expect(project.match(/TargetMachine="0"/g)).toHaveLength(2);
    expect(project).not.toContain('TargetMachine="1"');
    expect(
      project.match(
        /RemoteDirectory="%CSIDL_PROGRAM_FILES%\\PocketJS\.WM6\.Probe"/g,
      ),
    ).toHaveLength(2);
    expect(
      project.match(
        /RemoteExecutable="%CSIDL_PROGRAM_FILES%\\PocketJS\.WM6\.Probe\\PocketJS\.WM6\.Probe\.exe"/g,
      ),
    ).toHaveLength(2);
    expect(project).not.toContain("Windows Mobile 6 Standard SDK");
    expect(project).toContain('RelativePath=".\\resources\\probe.rc"');
    expect(resource).toMatch(/\bHI_RES_AWARE\s+CEUX\s+\{\s*1\s*\}/);
  });

  test("keeps the probe compatible with the VC8 compiler", async () => {
    const source = await readFile(new URL("src/main.cpp", root), "utf8");

    expect(source).toContain("int WINAPI WinMain");
    expect(source).toContain("SHFullScreen");
    expect(source).toContain("WM_LBUTTONDOWN");
    expect(source).toContain("WM_KEYDOWN");
    expect(source).toContain("CreateCompatibleBitmap");
    expect(source).toContain("CreateFontIndirect");
    expect(source).not.toMatch(/\bCreateFont\s*\(/);
    expect(source).not.toContain("lstrcpyn");
    expect(source).not.toMatch(/\b(auto|nullptr|constexpr|override)\b/);
  });

  test("includes a separate VC8 Pocket Vapor AOT application", async () => {
    const [solution, project, host, generated, runtime] = await Promise.all([
      readFile(new URL("PocketJS.WM6.sln", root), "utf8"),
      readFile(new URL("PocketJS.WM6.Vapor.vcproj", root), "utf8"),
      readFile(new URL("src/vapor_main.c", root), "utf8"),
      readFile(new URL("generated/todo.gba.c", root), "utf8"),
      readFile(new URL("runtime/vapor_core.c", root), "utf8"),
    ]);

    expect(solution).toContain('"PocketJS.WM6.Vapor"');
    expect(solution).toContain("{970E99AC-1918-451D-A515-9C23D9C3AC65}");
    expect(project).toContain('Version="8.00"');
    expect(project).toContain('Name="Windows Mobile 6 Professional SDK (ARMV4I)"');
    expect(project).toContain('RelativePath=".\\src\\vapor_main.c"');
    expect(project).toContain('RelativePath=".\\generated\\todo.gba.c"');
    expect(project).toContain(
      'RelativePath=".\\runtime\\vapor_core.c"',
    );
    expect(project.match(/AdditionalIncludeDirectories="\.\\runtime"/g)).toHaveLength(
      2,
    );
    expect(
      project.match(/DisableSpecificWarnings="4201;4115;4214;4819"/g),
    ).toHaveLength(2);
    expect(project.match(/inline=__inline/g)).toHaveLength(2);
    expect(project.match(/TargetMachine="0"/g)).toHaveLength(2);
    expect(
      project.match(
        /RemoteExecutable="%CSIDL_PROGRAM_FILES%\\PocketJS\.WM6\.Vapor\\PocketJS\.WM6\.Vapor\.exe"/g,
      ),
    ).toHaveLength(2);

    expect(host).toContain("app_init()");
    expect(host).toContain("app_on_button(button)");
    expect(host).toContain("ExtTextOut");
    expect(host).toContain("WM_LBUTTONUP");
    expect(generated).toContain(
      "GENERATED by vapor/compiler/compile.ts. DO NOT EDIT.",
    );
    expect(generated).toContain("const char vp_app_title[] = \"VAPOR TODO\"");
    expect(runtime).toContain("void vp_row_clear");
  });

  test("includes a pinned CeGCC QuickJS ARM/WinCE probe", async () => {
    const quickjsRoot = new URL("../hosts/wm6/quickjs/", import.meta.url);
    const [solution, project, build, runtimeBuild, cardsBuild, patch, probe,
      runtime, abi, cards, math, executable, dll] =
      await Promise.all([
        readFile(new URL("PocketJS.WM6.sln", root), "utf8"),
        readFile(new URL("PocketJS.WM6.QuickJS.vcproj", root), "utf8"),
        readFile(new URL("build-probe.sh", quickjsRoot), "utf8"),
        readFile(new URL("build-runtime.sh", quickjsRoot), "utf8"),
        readFile(new URL("build-cards.sh", quickjsRoot), "utf8"),
        readFile(new URL("patches/quickjs-wm6.patch", quickjsRoot), "utf8"),
        readFile(new URL("src/probe.c", quickjsRoot), "utf8"),
        readFile(new URL("src/runtime_dll.c", quickjsRoot), "utf8"),
        readFile(new URL("runtime/wm6_quickjs_abi.h", root), "utf8"),
        readFile(new URL("prebuilt/PocketJS.WM6.Cards.js", root), "utf8"),
        readFile(new URL("src/wm6_math.c", quickjsRoot), "utf8"),
        readFile(
          new URL("prebuilt/PocketJS.WM6.QuickJS.Probe.exe", root),
        ),
        readFile(new URL("prebuilt/PocketJS.WM6.QuickJS.dll", root)),
      ]);

    expect(solution).toContain('"PocketJS.WM6.QuickJS"');
    expect(solution).toContain("{AA37CB32-6044-4A78-A3A5-1F58080498C8}");
    expect(project).toContain('Version="8.00"');
    expect(project).toContain(
      'PocketJS.WM6.QuickJS.dll|$(SolutionDir)prebuilt|%CSIDL_PROGRAM_FILES%\\PocketJS.WM6.QuickJS|0',
    );
    expect(project.match(/TargetMachine="0"/g)).toHaveLength(2);
    expect(
      project.match(
        /RemoteExecutable="%CSIDL_PROGRAM_FILES%\\PocketJS\.WM6\.QuickJS\\PocketJS\.WM6\.QuickJS\.Host\.exe"/g,
      ),
    ).toHaveLength(2);

    expect(build).toContain(
      'quickjs_rev="0fc946fb670c0c29bc0135f510bcb0f595415a61"',
    );
    expect(build).toContain("-march=armv4t");
    expect(build).not.toContain("-march=armv5");
    expect(build).toContain("-msoft-float");
    expect(build).toContain("-D_WIN32_WCE=0x0502");
    expect(runtimeBuild).toContain("-shared");
    expect(runtimeBuild).toContain("-static-libgcc");
    expect(cardsBuild).toContain("dist/cards-main.js");
    expect(patch).toContain("#undef CONFIG_ATOMICS");
    expect(patch).toContain("#elif defined(_WIN32_WCE)");
    expect(probe).toContain("JS_SetMemoryLimit(runtime, 8u * 1024u * 1024u)");
    expect(probe).toContain("JS_SetMaxStackSize(runtime, 256u * 1024u)");
    expect(probe).toContain("JS_Eval(context");
    expect(probe).toContain("JS_NewCFunction(context, probe_print");
    expect(probe).toContain("JS_ExecutePendingJob(runtime");
    expect(probe).toContain("cycle < 100");
    expect(probe).toContain("QuickJS 6,10,16,26");
    expect(math).toContain("double fmax");
    expect(math).toContain("double fmin");
    expect(abi).toContain("#define WM6_QJS_ABI_VERSION 1u");
    expect(runtime).toContain("wm6_qjs_create");
    expect(runtime).toContain("wm6_qjs_eval");
    expect(runtime).toContain("wm6_qjs_drain_jobs");
    expect(cards).toContain("PocketJS Cards (real bundle)");
    expect(cards).toContain("Feature Cards");
    expect(cards).toContain("Flexbox via Taffy");

    expect(executable.subarray(0, 2).toString("ascii")).toBe("MZ");
    const peOffset = executable.readUInt32LE(0x3c);
    expect(executable.subarray(peOffset, peOffset + 4).toString("binary")).toBe(
      "PE\u0000\u0000",
    );
    expect(executable.readUInt16LE(peOffset + 4)).toBe(0x01c0);
    expect(executable.readUInt16LE(peOffset + 24 + 68)).toBe(9);
    expect(dll.subarray(0, 2).toString("ascii")).toBe("MZ");
    const dllPeOffset = dll.readUInt32LE(0x3c);
    expect(dll.readUInt16LE(dllPeOffset + 4)).toBe(0x01c0);
    expect(dll.readUInt16LE(dllPeOffset + 22) & 0x2000).toBe(0x2000);
  });
});
