#!/usr/bin/env bun
// static/compiler/bake-font.ts — one-shot: convert the public-domain font8x8
// bitmap font (Daniel Hepper / Marcel Sondaar / IBM VGA, public domain) into
// compiler/font.gen.ts. Checked-in output; rerun only to change the font.
//
//   bun static/compiler/bake-font.ts <path/to/font8x8_basic.h>

const src = await Bun.file(process.argv[2]).text();

// font8x8_basic covers U+0000..U+007F; each glyph is 8 bytes, LSB = leftmost
// pixel. We keep 0x20..0x7E (the 95 FONT_GLYPHS) and re-pack as MSB-left so
// downstream encoders read bits naturally.
const m = src.match(/font8x8_basic\[128\]\[8\]\s*=\s*\{([\s\S]*?)\};/);
if (!m) throw new Error("font8x8_basic table not found");
const rows = [...m[1].matchAll(/\{([^}]*)\}/g)].map((g) =>
  g[1]
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)
    .map((s) => Number(s)),
);
if (rows.length !== 128) throw new Error(`expected 128 glyphs, got ${rows.length}`);

const flip = (b: number): number => {
  let r = 0;
  for (let i = 0; i < 8; i++) if (b & (1 << i)) r |= 0x80 >> i;
  return r;
};

const glyphs: number[][] = [];
for (let c = 0x20; c <= 0x7e; c++) {
  glyphs.push(rows[c].map(flip));
}

const lines: string[] = [];
lines.push("// static/compiler/font.gen.ts — GENERATED by bake-font.ts. DO NOT EDIT.");
lines.push("//");
lines.push("// 95 ASCII glyphs (0x20..0x7E), 8 bytes each, MSB = leftmost pixel.");
lines.push("// Source: font8x8 by Daniel Hepper (public domain), based on");
lines.push("// Marcel Sondaar / IBM public-domain VGA fonts.");
lines.push("export const FONT8: readonly (readonly number[])[] = [");
for (let i = 0; i < glyphs.length; i++) {
  const ch = String.fromCharCode(0x20 + i);
  const bytes = glyphs[i].map((b) => "0x" + b.toString(16).padStart(2, "0")).join(", ");
  lines.push(`  [${bytes}], // ${JSON.stringify(ch)}`);
}
lines.push("];");

const out = new URL("./font.gen.ts", import.meta.url).pathname;
await Bun.write(out, lines.join("\n") + "\n");
console.log(`wrote ${out} (${glyphs.length} glyphs)`);
