// @generated by contracts/spec/gen-rust.ts from contracts/spec/relay.ts.
// Do not edit by hand: run `bun run gen` and commit. tests/contract.ts
// byte-compares this file against the generator on every run.

pub mod relay {
    pub const VERSION: u8 = 1;
    pub const MAGIC: [u8; 4] = [80, 82, 76, 89];
    pub const MAGIC_TEXT: &str = "PRLY";

    pub mod frame {
        pub const MAJOR: u32 = 1;
        pub const MINOR: u32 = 0;
        pub const HEADER_BYTES: u32 = 48;
        pub const LENGTH_PREFIX_BYTES: u32 = 4;
        pub const HEADER_BODY_BYTES: u32 = 44;
    }
    pub mod header {
        /// frameBytes: offset 0, width 4
        pub const FRAME_BYTES_OFFSET: usize = 0;
        pub const FRAME_BYTES_WIDTH: usize = 4;
        /// magic: offset 4, width 4
        pub const MAGIC_OFFSET: usize = 4;
        pub const MAGIC_WIDTH: usize = 4;
        /// major: offset 8, width 1
        pub const MAJOR_OFFSET: usize = 8;
        pub const MAJOR_WIDTH: usize = 1;
        /// minor: offset 9, width 1
        pub const MINOR_OFFSET: usize = 9;
        pub const MINOR_WIDTH: usize = 1;
        /// type: offset 10, width 1
        pub const TYPE_OFFSET: usize = 10;
        pub const TYPE_WIDTH: usize = 1;
        /// flags: offset 11, width 1
        pub const FLAGS_OFFSET: usize = 11;
        pub const FLAGS_WIDTH: usize = 1;
        /// headerBytes: offset 12, width 2
        pub const HEADER_BYTES_OFFSET: usize = 12;
        pub const HEADER_BYTES_WIDTH: usize = 2;
        /// codec: offset 14, width 2
        pub const CODEC_OFFSET: usize = 14;
        pub const CODEC_WIDTH: usize = 2;
        /// session: offset 16, width 8
        pub const SESSION_OFFSET: usize = 16;
        pub const SESSION_WIDTH: usize = 8;
        /// seq: offset 24, width 4
        pub const SEQ_OFFSET: usize = 24;
        pub const SEQ_WIDTH: usize = 4;
        /// stream: offset 28, width 4
        pub const STREAM_OFFSET: usize = 28;
        pub const STREAM_WIDTH: usize = 4;
        /// correlation: offset 32, width 4
        pub const CORRELATION_OFFSET: usize = 32;
        pub const CORRELATION_WIDTH: usize = 4;
        /// metaBytes: offset 36, width 4
        pub const META_BYTES_OFFSET: usize = 36;
        pub const META_BYTES_WIDTH: usize = 4;
        /// dataBytes: offset 40, width 4
        pub const DATA_BYTES_OFFSET: usize = 40;
        pub const DATA_BYTES_WIDTH: usize = 4;
        /// reserved: offset 44, width 4
        pub const RESERVED_OFFSET: usize = 44;
        pub const RESERVED_WIDTH: usize = 4;
    }
    pub mod type_ {
        pub const REQUEST: u8 = 1;
        pub const RESPONSE: u8 = 2;
        pub const PUSH: u8 = 3;
        pub const CANCEL: u8 = 4;
        pub const INVALIDATE: u8 = 5;
    }
    pub mod frame_error {
        pub const SHORT_HEADER: &str = "SHORT_HEADER";
        pub const BAD_PREFIX: &str = "BAD_PREFIX";
        pub const BAD_MAGIC: &str = "BAD_MAGIC";
        pub const BAD_VERSION: &str = "BAD_VERSION";
        pub const BAD_TYPE: &str = "BAD_TYPE";
        pub const BAD_FLAGS: &str = "BAD_FLAGS";
        pub const BAD_HEADER_SIZE: &str = "BAD_HEADER_SIZE";
        pub const BAD_RESERVED: &str = "BAD_RESERVED";
        pub const BAD_LENGTH: &str = "BAD_LENGTH";
        pub const TRUNCATED: &str = "TRUNCATED";
        pub const WIRE_TOO_LARGE: &str = "WIRE_TOO_LARGE";
        pub const META_TOO_LARGE: &str = "META_TOO_LARGE";
        pub const BAD_CODEC: &str = "BAD_CODEC";
        pub const BAD_SESSION: &str = "BAD_SESSION";
        pub const BAD_SEQ: &str = "BAD_SEQ";
        pub const BAD_CORRELATION: &str = "BAD_CORRELATION";
        pub const BAD_METADATA: &str = "BAD_METADATA";
        pub const BAD_ENVELOPE: &str = "BAD_ENVELOPE";
    }
    pub mod error {
        pub const UNSUPPORTED: &str = "UNSUPPORTED";
        pub const INVALID: &str = "INVALID";
        pub const UNAUTHORIZED: &str = "UNAUTHORIZED";
        pub const BUSY: &str = "BUSY";
        pub const TOO_LARGE: &str = "TOO_LARGE";
        pub const STALE_BASE: &str = "STALE_BASE";
        pub const NOT_FOUND: &str = "NOT_FOUND";
        pub const CANCELLED: &str = "CANCELLED";
        pub const DEADLINE: &str = "DEADLINE";
        pub const OUTCOME_UNKNOWN: &str = "OUTCOME_UNKNOWN";
        pub const RESYNC_REQUIRED: &str = "RESYNC_REQUIRED";
    }
    pub mod status {
        pub const OK: &str = "ok";
        pub const ACCEPTED: &str = "accepted";
        pub const ERROR: &str = "error";
    }
    pub mod effect {
        pub const NONE: &str = "none";
        pub const COMMITTED: &str = "committed";
        pub const UNKNOWN: &str = "unknown";
    }
    pub mod op {
        pub const HELLO: &str = "relay.hello";
        pub const READY: &str = "relay.ready";
        pub const OPEN: &str = "relay.open";
        pub const CLOSE: &str = "relay.close";
        pub const PING: &str = "relay.ping";
        pub const CREDIT: &str = "relay.credit";
        pub const RESET: &str = "relay.reset";
        pub const RESOURCE_GET: &str = "resource.get";
        pub const RESOURCE_SUBSCRIBE: &str = "resource.subscribe";
        pub const RESOURCE_RELEASE: &str = "resource.release";
        pub const RESOURCE_UNSUBSCRIBE: &str = "resource.unsubscribe";
        pub const REQUEST_CANCEL: &str = "request.cancel";
        pub const RESOURCE_INVALIDATE: &str = "resource.invalidate";
        pub const CACHE_EVICT: &str = "cache.evict";
        pub const OPERATION_STATUS: &str = "operation.status";
        pub const OPERATION_EPOCH: &str = "operation.epoch";
    }
    pub mod codec {
        pub const NONE: u16 = 0;
        pub const JSON: u16 = 1;
        pub const R5G6B5LE: u16 = 257;
        pub const PMH1: u16 = 258;
        pub const COVERAGE2_LSB: u16 = 259;
        pub const INDEXED8_ABGR: u16 = 260;
        pub const FONT3: u16 = 513;
        pub const OPAQUE_BYTES: u16 = 769;
        pub const EXTENSION_MIN: u16 = 32768;
        pub const EXTENSION_MAX: u16 = 65535;
    }
    pub mod kind {
        pub const TILE: u8 = 1;
        pub const TEXTURE: u8 = 2;
        pub const GLYPH_RUN: u8 = 3;
        pub const TEXT_LAYOUT: u8 = 4;
        pub const MEDIA_CHUNK: u8 = 5;
        pub const TERMINAL_CELLS: u8 = 6;
        pub const FILE: u8 = 7;
        pub const EVENT: u8 = 8;
    }
    pub mod delivery {
        pub const RELIABLE_DELTA: &str = "reliable-delta";
        pub const LATEST_SNAPSHOT: &str = "latest-snapshot";
    }
    pub mod invalidate_scope {
        pub const REVISION: &str = "revision";
        pub const KEY: &str = "key";
        pub const NAMESPACE: &str = "namespace";
    }
    pub mod evict_reason {
        pub const BUDGET: &str = "budget";
        pub const VIEW_CLOSE: &str = "view-close";
    }
    pub mod resource {
        pub const NS_MAX_BYTES: u32 = 128;
        pub const KEY_MAX_BYTES: u32 = 256;
        pub const REVISION_MAX_BYTES: u32 = 128;
        pub const RENDITION_MAX_BYTES: u32 = 128;
    }
    pub mod handshake {
        pub const NONCE_BYTES: u32 = 16;
        pub const SESSION_HEX_LENGTH: u32 = 16;
        pub const APP_MAX_BYTES: u32 = 64;
        pub const NAMESPACE_MAX_BYTES: u32 = 128;
        pub const VERSIONS_MAX: u32 = 8;
        pub const PROFILES_MAX: u32 = 16;
        pub const PROFILE_NAME_MAX_BYTES: u32 = 64;
        pub const TRANSPORT_MAX_BYTES: u32 = 64;
    }
    pub mod limits {
        pub const BOOTSTRAP_MAX_WIRE_BYTES: u32 = 4096;
        pub const CONTROL_MAX_WIRE_BYTES: u32 = 4096;
        pub const CONTROL_WINDOW_FRAMES: u32 = 8;
        pub const CONTROL_WINDOW_BYTES: u32 = 32768;
        pub const SIDEBAND_SLOTS: u32 = 2;
        pub const SIDEBAND_SLOT_BYTES: u32 = 256;
        pub const SIDEBAND_CREDIT_TABLE: u32 = 9;
        pub const MAX_PENDING: u32 = 8;
        pub const BULK_MAX_WIRE_BYTES: u32 = 65536;
        pub const BULK_MAX_META_BYTES: u32 = 2048;
        pub const BULK_WINDOW_FRAMES: u32 = 2;
        pub const BULK_WINDOW_BYTES: u32 = 131072;
        pub const BULK_MAX_ASSEMBLIES: u32 = 2;
        pub const DEFAULT_MAX_WIRE_BYTES: u32 = 65536;
        pub const DEFAULT_MAX_META_BYTES: u32 = 2048;
        pub const MAX_BULK_ATTACHMENTS: u32 = 1;
        pub const MAX_STREAMS: u32 = 8;
        pub const PING_INTERVAL_MS: u32 = 2000;
        pub const STALL_MS: u32 = 15000;
        pub const RETRY_MS: u32 = 1500;
        pub const JSON_MAX_DEPTH: u32 = 16;
        pub const OP_MAX_LENGTH: u32 = 64;
        pub const ERROR_MESSAGE_MAX_BYTES: u32 = 160;
        pub const CANCEL_REASON_MAX_BYTES: u32 = 64;
        pub const DEPENDS_MAX: u32 = 8;
    }
    pub const OP_PATTERN: &str = "^[a-z][a-z0-9_.-]{0,63}$";
}
