/* static/test/harness/mgba_runner.c — headless GBA/GB scenario driver on
 * libmgba (Homebrew). One binary serves both consoles: mCoreFind picks the
 * core from the ROM.
 *
 *   mgba_runner <rom> <scenario.txt>
 *
 * Scenario: one command per line (machine-generated by test/e2e.ts):
 *   A <frames>                       advance
 *   P <keymask-hex> <hold> <release> press keys, run hold frames, release,
 *                                    run release frames
 *   R <name> <addr-hex> <size>       read 1/2/4 bytes little-endian
 *   S <path>                         screenshot (PPM P6)
 * Output: one JSON object on stdout: {"ok":true,"reads":{...}}.
 * The key mask uses the PS_KEY_* bit order, which matches mGBA's GBA_KEY
 * order for the low 8 bits on both cores.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <mgba/core/core.h>
#include <mgba/core/config.h>

static struct mCore *core;
static uint32_t *videoBuffer;
static unsigned vw, vh;

static void run_frames(int n) {
  int i;
  for (i = 0; i < n; i++) core->runFrame(core);
}

static void screenshot(const char *path) {
  FILE *f = fopen(path, "wb");
  unsigned x, y;
  if (!f) return;
  fprintf(f, "P6\n%u %u\n255\n", vw, vh);
  for (y = 0; y < vh; y++) {
    for (x = 0; x < vw; x++) {
      uint32_t p = videoBuffer[y * vw + x];
      unsigned char rgb[3];
      rgb[0] = p & 0xff;
      rgb[1] = (p >> 8) & 0xff;
      rgb[2] = (p >> 16) & 0xff;
      fwrite(rgb, 1, 3, f);
    }
  }
  fclose(f);
}

int main(int argc, char **argv) {
  FILE *sc;
  char line[1024];
  int first_read = 1;

  if (argc != 3) {
    fprintf(stderr, "usage: mgba_runner <rom> <scenario.txt>\n");
    return 2;
  }

  core = mCoreFind(argv[1]);
  if (!core) {
    printf("{\"ok\":false,\"error\":\"no core for rom\"}\n");
    return 1;
  }
  core->init(core);
  mCoreConfigInit(&core->config, "mgba_runner");
  mCoreConfigSetDefaultValue(&core->config, "idleOptimization", "ignore");
  core->loadConfig(core, &core->config);

  core->desiredVideoDimensions(core, &vw, &vh);
  videoBuffer = malloc((size_t)vw * vh * 4);
  core->setVideoBuffer(core, (color_t *)videoBuffer, vw);
  core->setAudioBufferSize(core, 0x4000);

  if (!mCoreLoadFile(core, argv[1])) {
    printf("{\"ok\":false,\"error\":\"rom load failed\"}\n");
    return 1;
  }
  core->reset(core);

  sc = fopen(argv[2], "r");
  if (!sc) {
    printf("{\"ok\":false,\"error\":\"scenario open failed\"}\n");
    return 1;
  }

  printf("{\"ok\":true,\"reads\":{");
  while (fgets(line, sizeof line, sc)) {
    char op = line[0];
    if (op == 'A') {
      int n = 0;
      sscanf(line + 1, "%d", &n);
      run_frames(n);
    } else if (op == 'P') {
      unsigned mask = 0;
      int hold = 0, release = 0;
      sscanf(line + 1, "%x %d %d", &mask, &hold, &release);
      core->setKeys(core, mask);
      run_frames(hold);
      core->setKeys(core, 0);
      run_frames(release);
    } else if (op == 'R') {
      char name[256];
      unsigned addr = 0;
      int size = 1;
      uint32_t v = 0;
      sscanf(line + 1, "%255s %x %d", name, &addr, &size);
      v = core->busRead8(core, addr);
      if (size >= 2) v |= (uint32_t)core->busRead8(core, addr + 1) << 8;
      if (size == 4) {
        v |= (uint32_t)core->busRead8(core, addr + 2) << 16;
        v |= (uint32_t)core->busRead8(core, addr + 3) << 24;
      }
      printf("%s\"%s\":%u", first_read ? "" : ",", name, v);
      first_read = 0;
    } else if (op == 'S') {
      char path[512];
      sscanf(line + 1, "%511s", path);
      screenshot(path);
    }
  }
  printf("}}\n");
  fclose(sc);
  core->deinit(core);
  return 0;
}
