// Generated by tools/esp-idf-contracts.ts from contracts/spec/idf-native.ts. Do not edit.
#![no_std]
use core::ffi::c_void;
pub const MAX_DAMAGE_REGIONS: usize = 8;

pub type FillFn = unsafe extern "C" fn(*mut c_void, *mut u16, usize, u32, u32, NativeRect, u16) -> bool;

pub type BlendFn = unsafe extern "C" fn(*mut c_void, *mut u16, usize, u32, u32, *const u8, usize, NativeRect, u8, u8, u8, u8) -> bool;

pub type SrmFn = unsafe extern "C" fn(*mut c_void, *mut u16, usize, u32, u32, *const u8, usize, u32, u32, NativeRect, NativeRect, u32, bool, bool) -> bool;

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct NativeUiConfig {
    pub struct_size: usize,
    pub logical_width: u32,
    pub logical_height: u32,
    pub raster_density: u32,
    pub tick_hz: u32,
}
const _: () = {
    let p32 = core::mem::size_of::<usize>() == 4;
    assert!(core::mem::size_of::<NativeUiConfig>() == if p32 { 20 } else { 24 });
    assert!(core::mem::align_of::<NativeUiConfig>() == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeUiConfig, struct_size) == if p32 { 0 } else { 0 });
    assert!(core::mem::offset_of!(NativeUiConfig, logical_width) == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeUiConfig, logical_height) == if p32 { 8 } else { 12 });
    assert!(core::mem::offset_of!(NativeUiConfig, raster_density) == if p32 { 12 } else { 16 });
    assert!(core::mem::offset_of!(NativeUiConfig, tick_hz) == if p32 { 16 } else { 20 });
};

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct NativeAsset {
    pub struct_size: usize,
    pub kind: u32,
    pub data: *const u8,
    pub size: usize,
}
const _: () = {
    let p32 = core::mem::size_of::<usize>() == 4;
    assert!(core::mem::size_of::<NativeAsset>() == if p32 { 16 } else { 32 });
    assert!(core::mem::align_of::<NativeAsset>() == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeAsset, struct_size) == if p32 { 0 } else { 0 });
    assert!(core::mem::offset_of!(NativeAsset, kind) == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeAsset, data) == if p32 { 8 } else { 16 });
    assert!(core::mem::offset_of!(NativeAsset, size) == if p32 { 12 } else { 24 });
};

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct NativeFrameView {
    pub struct_size: usize,
    pub epoch: u64,
    pub raster_revision: u64,
    pub logical_width: u32,
    pub logical_height: u32,
    pub raster_density: u32,
    pub draw_words: *const u32,
    pub draw_word_count: usize,
    pub private_core: *mut c_void,
}
const _: () = {
    let p32 = core::mem::size_of::<usize>() == 4;
    assert!(core::mem::size_of::<NativeFrameView>() == if p32 { 48 } else { 64 });
    assert!(core::mem::align_of::<NativeFrameView>() == if p32 { 8 } else { 8 });
    assert!(core::mem::offset_of!(NativeFrameView, struct_size) == if p32 { 0 } else { 0 });
    assert!(core::mem::offset_of!(NativeFrameView, epoch) == if p32 { 8 } else { 8 });
    assert!(core::mem::offset_of!(NativeFrameView, raster_revision) == if p32 { 16 } else { 16 });
    assert!(core::mem::offset_of!(NativeFrameView, logical_width) == if p32 { 24 } else { 24 });
    assert!(core::mem::offset_of!(NativeFrameView, logical_height) == if p32 { 28 } else { 28 });
    assert!(core::mem::offset_of!(NativeFrameView, raster_density) == if p32 { 32 } else { 32 });
    assert!(core::mem::offset_of!(NativeFrameView, draw_words) == if p32 { 36 } else { 40 });
    assert!(core::mem::offset_of!(NativeFrameView, draw_word_count) == if p32 { 40 } else { 48 });
    assert!(core::mem::offset_of!(NativeFrameView, private_core) == if p32 { 44 } else { 56 });
};

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct NativeTextureView {
    pub struct_size: usize,
    pub pixels: *const u8,
    pub pixel_bytes: usize,
    pub width: u32,
    pub height: u32,
    pub psm: u32,
    pub palette: *const u8,
    pub palette_bytes: usize,
    pub revision: u64,
    pub linear: bool,
}
const _: () = {
    let p32 = core::mem::size_of::<usize>() == 4;
    assert!(core::mem::size_of::<NativeTextureView>() == if p32 { 48 } else { 72 });
    assert!(core::mem::align_of::<NativeTextureView>() == if p32 { 8 } else { 8 });
    assert!(core::mem::offset_of!(NativeTextureView, struct_size) == if p32 { 0 } else { 0 });
    assert!(core::mem::offset_of!(NativeTextureView, pixels) == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeTextureView, pixel_bytes) == if p32 { 8 } else { 16 });
    assert!(core::mem::offset_of!(NativeTextureView, width) == if p32 { 12 } else { 24 });
    assert!(core::mem::offset_of!(NativeTextureView, height) == if p32 { 16 } else { 28 });
    assert!(core::mem::offset_of!(NativeTextureView, psm) == if p32 { 20 } else { 32 });
    assert!(core::mem::offset_of!(NativeTextureView, palette) == if p32 { 24 } else { 40 });
    assert!(core::mem::offset_of!(NativeTextureView, palette_bytes) == if p32 { 28 } else { 48 });
    assert!(core::mem::offset_of!(NativeTextureView, revision) == if p32 { 32 } else { 56 });
    assert!(core::mem::offset_of!(NativeTextureView, linear) == if p32 { 40 } else { 64 });
};

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct NativeFontView {
    pub struct_size: usize,
    pub bitmap: *const u8,
    pub bitmap_bytes: usize,
    pub cell_width: u32,
    pub cell_height: u32,
    pub raster_density: u32,
    pub glyph_count: u32,
}
const _: () = {
    let p32 = core::mem::size_of::<usize>() == 4;
    assert!(core::mem::size_of::<NativeFontView>() == if p32 { 28 } else { 40 });
    assert!(core::mem::align_of::<NativeFontView>() == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeFontView, struct_size) == if p32 { 0 } else { 0 });
    assert!(core::mem::offset_of!(NativeFontView, bitmap) == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeFontView, bitmap_bytes) == if p32 { 8 } else { 16 });
    assert!(core::mem::offset_of!(NativeFontView, cell_width) == if p32 { 12 } else { 24 });
    assert!(core::mem::offset_of!(NativeFontView, cell_height) == if p32 { 16 } else { 28 });
    assert!(core::mem::offset_of!(NativeFontView, raster_density) == if p32 { 20 } else { 32 });
    assert!(core::mem::offset_of!(NativeFontView, glyph_count) == if p32 { 24 } else { 36 });
};

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct NativeRendererConfig {
    pub struct_size: usize,
    pub scale: u32,
    pub min_fill_pixels: u32,
    pub min_blend_pixels: u32,
    pub min_srm_pixels: u32,
}
const _: () = {
    let p32 = core::mem::size_of::<usize>() == 4;
    assert!(core::mem::size_of::<NativeRendererConfig>() == if p32 { 20 } else { 24 });
    assert!(core::mem::align_of::<NativeRendererConfig>() == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeRendererConfig, struct_size) == if p32 { 0 } else { 0 });
    assert!(core::mem::offset_of!(NativeRendererConfig, scale) == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeRendererConfig, min_fill_pixels) == if p32 { 8 } else { 12 });
    assert!(core::mem::offset_of!(NativeRendererConfig, min_blend_pixels) == if p32 { 12 } else { 16 });
    assert!(core::mem::offset_of!(NativeRendererConfig, min_srm_pixels) == if p32 { 16 } else { 20 });
};

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct NativeRect {
    pub x: u32,
    pub y: u32,
    pub width: u32,
    pub height: u32,
}
const _: () = {
    let p32 = core::mem::size_of::<usize>() == 4;
    assert!(core::mem::size_of::<NativeRect>() == if p32 { 16 } else { 16 });
    assert!(core::mem::align_of::<NativeRect>() == if p32 { 4 } else { 4 });
    assert!(core::mem::offset_of!(NativeRect, x) == if p32 { 0 } else { 0 });
    assert!(core::mem::offset_of!(NativeRect, y) == if p32 { 4 } else { 4 });
    assert!(core::mem::offset_of!(NativeRect, width) == if p32 { 8 } else { 8 });
    assert!(core::mem::offset_of!(NativeRect, height) == if p32 { 12 } else { 12 });
};

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct NativeDamagePlan {
    pub struct_size: usize,
    pub region_count: u32,
    pub full_redraw: bool,
    pub regions: [NativeRect; MAX_DAMAGE_REGIONS],
}
const _: () = {
    let p32 = core::mem::size_of::<usize>() == 4;
    assert!(core::mem::size_of::<NativeDamagePlan>() == if p32 { 140 } else { 144 });
    assert!(core::mem::align_of::<NativeDamagePlan>() == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeDamagePlan, struct_size) == if p32 { 0 } else { 0 });
    assert!(core::mem::offset_of!(NativeDamagePlan, region_count) == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeDamagePlan, full_redraw) == if p32 { 8 } else { 12 });
    assert!(core::mem::offset_of!(NativeDamagePlan, regions) == if p32 { 12 } else { 16 });
};

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct NativeRenderStats {
    pub struct_size: usize,
    pub ppa_fills: u32,
    pub ppa_blends: u32,
    pub ppa_srm: u32,
    pub software_ops: u32,
    pub software_words: u32,
    pub damage_regions: u32,
    pub damage_pixels: u32,
    pub damage_bounds: NativeRect,
    pub full_redraw: bool,
}
const _: () = {
    let p32 = core::mem::size_of::<usize>() == 4;
    assert!(core::mem::size_of::<NativeRenderStats>() == if p32 { 52 } else { 56 });
    assert!(core::mem::align_of::<NativeRenderStats>() == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeRenderStats, struct_size) == if p32 { 0 } else { 0 });
    assert!(core::mem::offset_of!(NativeRenderStats, ppa_fills) == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeRenderStats, ppa_blends) == if p32 { 8 } else { 12 });
    assert!(core::mem::offset_of!(NativeRenderStats, ppa_srm) == if p32 { 12 } else { 16 });
    assert!(core::mem::offset_of!(NativeRenderStats, software_ops) == if p32 { 16 } else { 20 });
    assert!(core::mem::offset_of!(NativeRenderStats, software_words) == if p32 { 20 } else { 24 });
    assert!(core::mem::offset_of!(NativeRenderStats, damage_regions) == if p32 { 24 } else { 28 });
    assert!(core::mem::offset_of!(NativeRenderStats, damage_pixels) == if p32 { 28 } else { 32 });
    assert!(core::mem::offset_of!(NativeRenderStats, damage_bounds) == if p32 { 32 } else { 36 });
    assert!(core::mem::offset_of!(NativeRenderStats, full_redraw) == if p32 { 48 } else { 52 });
};

#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct NativeAccelerator {
    pub struct_size: usize,
    pub user_data: *mut c_void,
    pub fill_rgb565: Option<FillFn>,
    pub blend_a8_rgb565: Option<BlendFn>,
    pub srm_psm5650_rgb565: Option<SrmFn>,
}
const _: () = {
    let p32 = core::mem::size_of::<usize>() == 4;
    assert!(core::mem::size_of::<NativeAccelerator>() == if p32 { 20 } else { 40 });
    assert!(core::mem::align_of::<NativeAccelerator>() == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeAccelerator, struct_size) == if p32 { 0 } else { 0 });
    assert!(core::mem::offset_of!(NativeAccelerator, user_data) == if p32 { 4 } else { 8 });
    assert!(core::mem::offset_of!(NativeAccelerator, fill_rgb565) == if p32 { 8 } else { 16 });
    assert!(core::mem::offset_of!(NativeAccelerator, blend_a8_rgb565) == if p32 { 12 } else { 24 });
    assert!(core::mem::offset_of!(NativeAccelerator, srm_psm5650_rgb565) == if p32 { 16 } else { 32 });
};
