// GENERATED — do not edit; run `bun contracts/spec/gen-rust.ts`.
pub use pocketjs_core::spec::{btn, prop, Display, NodeType};

pub const NUMERIC_TYPES: &[&str] = &["i8", "i16", "i32", "i64", "u8", "u16", "u32", "u64", "usize", "f32", "f64"];
pub const BUILTINS: &[&str] = &["len", "trunc", "floor", "ceil", "round", "idiv", "imod", "min", "max", "abs", "clamp", "fixed"];
pub const HOST_ELEMENTS: &[(&str, u8)] = &[
    ("View", 0),
    ("Text", 1),
    ("Image", 2),
];
pub const STYLE_PROPS: &[(&str, u8, &str)] = &[
    ("width", 1, "f32"),
    ("height", 2, "f32"),
    ("minW", 3, "f32"),
    ("minH", 4, "f32"),
    ("maxW", 5, "f32"),
    ("maxH", 6, "f32"),
    ("paddingT", 8, "f32"),
    ("paddingR", 9, "f32"),
    ("paddingB", 10, "f32"),
    ("paddingL", 11, "f32"),
    ("marginT", 12, "f32"),
    ("marginR", 13, "f32"),
    ("marginB", 14, "f32"),
    ("marginL", 15, "f32"),
    ("gap", 16, "f32"),
    ("flexDir", 17, "i32"),
    ("justify", 18, "i32"),
    ("align", 19, "i32"),
    ("grow", 20, "f32"),
    ("shrink", 21, "f32"),
    ("basis", 22, "f32"),
    ("flexWrap", 23, "i32"),
    ("posType", 24, "i32"),
    ("insetT", 25, "f32"),
    ("insetR", 26, "f32"),
    ("insetB", 27, "f32"),
    ("insetL", 28, "f32"),
    ("display", 29, "i32"),
    ("overflow", 30, "i32"),
    ("zIndex", 31, "i32"),
    ("hitPass", 32, "i32"),
    ("bgColor", 64, "u32"),
    ("gradFrom", 65, "u32"),
    ("gradTo", 66, "u32"),
    ("gradDir", 67, "i32"),
    ("radius", 68, "f32"),
    ("opacity", 69, "f32"),
    ("borderColor", 70, "u32"),
    ("borderWidth", 71, "f32"),
    ("shadow", 72, "i32"),
    ("bevelOuterLight", 77, "u32"),
    ("bevelOuterDark", 78, "u32"),
    ("bevelInnerLight", 79, "u32"),
    ("bevelInnerDark", 80, "u32"),
    ("bevelWidth", 81, "f32"),
    ("gradVia", 82, "u32"),
    ("gradViaPos", 83, "f32"),
    ("textColor", 96, "u32"),
    ("fontSlot", 97, "i32"),
    ("textAlign", 98, "i32"),
    ("lineHeight", 99, "f32"),
    ("tracking", 100, "f32"),
    ("translateX", 128, "f32"),
    ("translateY", 129, "f32"),
    ("scale", 130, "f32"),
    ("rotate", 131, "f32"),
    ("scaleX", 132, "f32"),
    ("scaleY", 133, "f32"),
    ("originX", 134, "f32"),
    ("originY", 135, "f32"),
    ("rotateX", 136, "f32"),
    ("rotateY", 137, "f32"),
    ("translateZ", 138, "f32"),
    ("perspective", 139, "f32"),
    ("arcStart", 140, "f32"),
    ("arcSweep", 141, "f32"),
    ("arcWidth", 142, "f32"),
];
pub const HOST_ATTRIBUTES: &[(&str, &[&str])] = &[
    ("View", &["class", "style", "focusable", "debug-name"]),
    ("Text", &["class"]),
    ("Image", &["class", "src"]),
];
pub const HOST_EVENTS: &[(&str, &[&str])] = &[
    ("View", &["press"]),
    ("Text", &[]),
    ("Image", &[]),
];
pub const BUILTIN_SIGNATURES: &[(&str, &[&str], &str, &str)] = &[
    ("len", &["string | T[]"], "i32", "none"),
    ("trunc", &["float"], "i32", "float"),
    ("floor", &["float"], "i32", "float"),
    ("ceil", &["float"], "i32", "float"),
    ("round", &["float"], "i32", "float"),
    ("idiv", &["T", "T"], "T", "integer"),
    ("imod", &["T", "T"], "T", "integer"),
    ("min", &["T", "T"], "T", "same"),
    ("max", &["T", "T"], "T", "same"),
    ("abs", &["T"], "T", "same"),
    ("clamp", &["T", "T", "T"], "T", "same"),
    ("fixed", &["float", "i32"], "string", "float"),
];
