// aot/compiler/targets/gb.ts — the Game Boy backend.
//
// Unlike the GBA (flat ROM, runtime chunk parsing), the GB build residualizes
// all game data into per-bank C arrays (gen_data*.c) compiled with GBDK-2020.
// Banking uses GBDK autobanking: every data file is `#pragma bank 255` and the
// linker (bankpack) assigns MBC5 ROM banks; the runtime switches banks with
// SWITCH_ROM(BANK(sym)) around each access.
//
// Pixel policy (DMG): the authored 16-color art is mapped to 4 shades by
// luminance. BG shade 0 is lightest (BGP identity 0xE4); OBJ color 0 is
// transparent and visible colors map to 1..3.

import { mkdir } from "node:fs/promises";
import { $ } from "bun";
import {
  BG_TILE_BUDGET,
  BUDGET,
  OBJ_TILE_BUDGET,
  TILE_2BPP_BYTES,
  TOK_ASCII_MIN,
} from "../../spec/pjgb.ts";
import { halfcellPixels, unifontGlyph } from "../cjk.ts";
import { tokenize } from "../text.ts";
import type { CompileOutput } from "../index.ts";
import type { Rgb } from "../context.ts";
import type { TargetBuildResult } from "./index.ts";

const ROOT = new URL("../../..", import.meta.url).pathname; // repo root
const RT = ROOT + "aot/runtime/gb";
const GBDK = process.env.GBDK_HOME ?? `${process.env.HOME}/.pocketjs/toolchains/gbdk`;

// GB script bytecode is copied to a WRAM buffer before execution.
const GB_SCRIPT_BUF = 2048;

// ---------------------------------------------------------------------------
// Pixel encoding
// ---------------------------------------------------------------------------
const lum = (c: Rgb): number => 0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2];

/** Map an RGB to a DMG shade 0 (lightest) .. 3 (darkest). */
export function shadeOf(c: Rgb): number {
  const l = lum(c);
  if (l >= 192) return 0;
  if (l >= 128) return 1;
  if (l >= 64) return 2;
  return 3;
}

const BAYER2 = [
  [-9, 3],
  [9, -3],
];
function shadeOfLum(l: number): number {
  if (l >= 192) return 0;
  if (l >= 128) return 1;
  if (l >= 64) return 2;
  return 3;
}

/**
 * Per-tile 4-shade mapper for downsampled art: pixels near the tile's mean
 * luminance flatten TO the mean (killing row-banding from averaged texture),
 * distinct features keep their own level, and a Bayer 2x2 offset turns the
 * remaining threshold noise into the classic handheld dither.
 */
export function tileShadeMapper(px: number[], palette: Rgb[]): (v: number, x: number, y: number) => number {
  const lums = px.map((v) => lum(palette[v] ?? [0, 0, 0]));
  const mean = lums.reduce((a, b) => a + b, 0) / lums.length;
  return (v, x, y) => {
    const own = lum(palette[v] ?? [0, 0, 0]);
    const l = Math.abs(own - mean) < 26 ? mean : own;
    return shadeOfLum(l + BAYER2[y & 1][x & 1]);
  };
}

/** GB 2bpp tile: 16 bytes; per row, byte0 = low bitplane, byte1 = high. */
export function tile2gb(px: number[], toShade: (v: number, x: number, y: number) => number): Uint8Array {
  const out = new Uint8Array(TILE_2BPP_BYTES);
  for (let row = 0; row < 8; row++) {
    let lo = 0;
    let hi = 0;
    for (let x = 0; x < 8; x++) {
      const s = toShade(px[row * 8 + x], x, row) & 3;
      lo |= (s & 1) << (7 - x);
      hi |= ((s >> 1) & 1) << (7 - x);
    }
    out[row * 2] = lo;
    out[row * 2 + 1] = hi;
  }
  return out;
}

// Textbox glyphs: ink = shade 0 (white via BGP), box bg = shade 3 (black).
const GLYPH_INK = 0;
const GLYPH_BG = 3;

// ---------------------------------------------------------------------------
// C emission helpers
// ---------------------------------------------------------------------------
function cBytes(name: string, bytes: ArrayLike<number>, opts: { banked?: boolean } = {}): string {
  const rows: string[] = [];
  for (let i = 0; i < bytes.length; i += 16) {
    const slice: string[] = [];
    for (let j = i; j < Math.min(i + 16, bytes.length); j++) slice.push(`0x${(bytes[j] & 0xff).toString(16).padStart(2, "0")}`);
    rows.push("  " + slice.join(",") + ",");
  }
  const body = [`const unsigned char ${name}[] = {`, ...rows, "};"];
  if (opts.banked) body.push(`BANKREF(${name})`);
  return body.join("\n");
}

function cWords(name: string, words: number[], opts: { banked?: boolean } = {}): string {
  const rows: string[] = [];
  for (let i = 0; i < words.length; i += 12) {
    rows.push("  " + words.slice(i, i + 12).map((w) => `0x${(w & 0xffff).toString(16)}`).join(",") + ",");
  }
  const body = [`const unsigned int ${name}[] = {`, ...rows, "};"];
  if (opts.banked) body.push(`BANKREF(${name})`);
  return body.join("\n");
}

const bankedFile = (body: string[]): string =>
  ["// GENERATED by @pocketjs/aot (gb backend) — do not edit.", "#pragma bank 255", '#include <gbdk/platform.h>', "", ...body, ""].join("\n");
const fixedFile = (body: string[]): string =>
  ["// GENERATED by @pocketjs/aot (gb backend) — do not edit.", '#include <gbdk/platform.h>', '#include "gen_data.h"', "", ...body, ""].join("\n");

// ---------------------------------------------------------------------------
// Lowering
// ---------------------------------------------------------------------------
interface GbFiles {
  files: Record<string, string>; // filename -> contents (written into runtime/gb)
  header: string; // gen_data.h
}

export function lowerGb(out: CompileOutput): GbFiles {
  const { ctx, model, game } = out;
  const t = ctx.target;

  // --- encode text bank first so the glyph set is complete ---
  const texts = ctx.texts.list().map((s) => tokenize(s, ctx.fullGlyphId));
  const textBlob: number[] = [];
  const textOffs: number[] = [];
  for (const tk of texts) {
    textOffs.push(textBlob.length);
    textBlob.push(...tk);
  }

  // --- BG tiles: blank + tileset + box; glyph slots are VRAM-only ---
  const bgTiles: Uint8Array[] = ctx.bgTilePx.map((px) => tile2gb(px, tileShadeMapper(px, ctx.bgPaletteRgb)));
  const boxTile = bgTiles.length;
  bgTiles.push(tile2gb(new Array(64).fill(0), () => GLYPH_BG));
  const slotBase = bgTiles.length;
  const slotTiles = t.glyphSlots * 2;

  // --- glyphs ---
  const glyphHalf: number[] = [];
  for (let c = TOK_ASCII_MIN; c <= 0x7e; c++) {
    const [top, bottom] = halfcellPixels(unifontGlyph(c), 0, GLYPH_INK, GLYPH_BG);
    glyphHalf.push(...tile2gb(top, (v) => v), ...tile2gb(bottom, (v) => v));
  }
  const glyphFull: number[] = [];
  for (const ch of ctx.fullGlyphs.list()) {
    const gl = unifontGlyph(ch.codePointAt(0)!);
    for (const half of [0, 1] as const) {
      const [top, bottom] = halfcellPixels(gl, half, GLYPH_INK, GLYPH_BG);
      glyphFull.push(...tile2gb(top, (v) => v), ...tile2gb(bottom, (v) => v));
    }
  }

  // --- OBJ tiles: per frame L-halfcell(top,bottom), R-halfcell(top,bottom) ---
  const objTiles: number[] = [];
  ctx.spriteProtos.forEach((sp, si) => {
    const pal = sp.palette;
    const objShade = (v: number): number => (v === 0 ? 0 : Math.max(1, shadeOf(pal[v] ?? [0, 0, 0])));
    for (const grid of ctx.spriteFrames16[si]) {
      for (const [ox, oy] of [
        [0, 0],
        [0, 8],
        [8, 0],
        [8, 8],
      ]) {
        const tpx: number[] = [];
        for (let y = 0; y < 8; y++) for (let x = 0; x < 8; x++) tpx.push(grid[(oy + y) * 16 + (ox + x)]);
        objTiles.push(...tile2gb(tpx, objShade));
      }
    }
  });
  const objTileCount = objTiles.length / TILE_2BPP_BYTES;

  // --- validation ---
  const err: string[] = [];
  if (slotBase + slotTiles > BG_TILE_BUDGET.gb) err.push(`BG tiles ${slotBase}+${slotTiles} slots > ${BG_TILE_BUDGET.gb}`);
  if (objTileCount > OBJ_TILE_BUDGET.gb) err.push(`OBJ tiles ${objTileCount} > ${OBJ_TILE_BUDGET.gb}`);
  if (ctx.fullGlyphs.size > BUDGET.MAX_FULL_GLYPHS) err.push(`too many CJK glyphs (${ctx.fullGlyphs.size})`);
  if (textBlob.length > 0xffff) err.push(`text bank too large (${textBlob.length})`);
  for (const s of ctx.scripts) {
    if (s.bytecode.length > GB_SCRIPT_BUF) err.push(`script ${s.name} is ${s.bytecode.length}B > ${GB_SCRIPT_BUF}B WRAM buffer`);
  }
  for (const m of model.maps) {
    if (m.w > t.maxMapW || m.h > t.maxMapH) err.push(`map "${m.name}" ${m.w}x${m.h} exceeds ${t.maxMapW}x${t.maxMapH}`);
    if (m.actors.length > BUDGET.MAX_ACTORS_PER_MAP) err.push(`map "${m.name}" has ${m.actors.length} actors`);
  }
  if (err.length) throw new Error("GB lowering failed:\n  - " + err.join("\n  - "));

  // --- script blob (u16 offsets, n+1 entries) ---
  const scriptBlob: number[] = [];
  const scriptOffs: number[] = [];
  for (const s of ctx.scripts) {
    scriptOffs.push(scriptBlob.length);
    scriptBlob.push(...s.bytecode);
  }
  scriptOffs.push(scriptBlob.length);

  // --- per-map data (records use the spec layouts, packed) ---
  const files: Record<string, string> = {};
  const mapInfos: string[] = [];
  model.maps.forEach((m) => {
    const actors: number[] = [];
    for (const a of m.actors) {
      actors.push(a.x & 0xff, a.x >> 8, a.y & 0xff, a.y >> 8, a.spriteId, a.facing, a.movement, a.flags, a.onTalk & 0xff, (a.onTalk >> 8) & 0xff, 0, 0);
    }
    const warps: number[] = [];
    for (const wp of m.warps) {
      warps.push(wp.x & 0xff, wp.x >> 8, wp.y & 0xff, wp.y >> 8, wp.destMapIdx!, wp.destDir!, wp.destX! & 0xff, wp.destX! >> 8, wp.destY! & 0xff, wp.destY! >> 8, 0, 0);
    }
    files[`gen_map_${m.index}.c`] = bankedFile([
      cBytes(`pj_map${m.index}_tiles`, m.tiles, { banked: true }),
      "",
      cBytes(`pj_map${m.index}_coll`, m.collision, { banked: true }),
      "",
      cBytes(`pj_map${m.index}_actors`, actors.length ? actors : [0], { banked: true }),
      "",
      cBytes(`pj_map${m.index}_warps`, warps.length ? warps : [0], { banked: true }),
    ]);
    mapInfos.push(
      `  { ${m.w}, ${m.h}, 0x${m.onEnter.toString(16)}, ${m.actors.length}, ${m.warps.length}, ` +
        `BANK(pj_map${m.index}_tiles), pj_map${m.index}_tiles, pj_map${m.index}_coll, ` +
        `(const PjActor *)pj_map${m.index}_actors, (const PjWarp *)pj_map${m.index}_warps },`,
    );
  });

  files["gen_tiles.c"] = bankedFile([
    cBytes("pj_bg_tiles", bgTiles.flatMap((b) => [...b]), { banked: true }),
    "",
    cBytes("pj_obj_tiles", objTiles, { banked: true }),
  ]);
  files["gen_glyphs_half.c"] = bankedFile([cBytes("pj_glyphs_half", glyphHalf, { banked: true })]);
  files["gen_glyphs_full.c"] = bankedFile([cBytes("pj_glyphs_full", glyphFull.length ? glyphFull : [0], { banked: true })]);
  files["gen_texts.c"] = bankedFile([
    cWords("pj_text_offs", textOffs, { banked: true }),
    "",
    cBytes("pj_texts", textBlob.length ? textBlob : [0], { banked: true }),
  ]);
  files["gen_scripts.c"] = bankedFile([
    cWords("pj_script_offs", scriptOffs, { banked: true }),
    "",
    cBytes("pj_scripts", scriptBlob.length ? scriptBlob : [0], { banked: true }),
  ]);

  // sprite prototype table (fixed bank; hot)
  const sprites = ctx.spriteProtos
    .map((sp) => `  { ${sp.tileBase * 4}, ${sp.frames} },`)
    .join("\n");
  files["gen_fixed.c"] = fixedFile([
    `const PjMapInfo pj_maps[] = {`,
    ...mapInfos,
    `};`,
    "",
    `const PjSprite pj_sprites[] = {`,
    sprites || "  { 0, 1 },",
    `};`,
  ]);

  // --- gen_data.h ---
  const header = [
    "// GENERATED by @pocketjs/aot (gb backend) — do not edit.",
    "#ifndef PJ_GEN_DATA_H",
    "#define PJ_GEN_DATA_H",
    '#include <gbdk/platform.h>',
    "",
    "typedef struct { unsigned int x, y; unsigned char sprite, facing, move, flags; unsigned int on_talk, rsv; } PjActor;",
    "typedef struct { unsigned int x, y; unsigned char dest_map, dest_dir; unsigned int dest_x, dest_y, rsv; } PjWarp;",
    "typedef struct { unsigned char w, h, on_enter, n_actors, n_warps, bank;",
    "                 const unsigned char *tiles; const unsigned char *coll;",
    "                 const PjActor *actors; const PjWarp *warps; } PjMapInfo;",
    "typedef struct { unsigned int tile_base; unsigned char frames; } PjSprite;",
    "",
    `#define PJ_MAP_COUNT ${model.maps.length}`,
    `#define PJ_SPRITE_COUNT ${ctx.spriteProtos.length}`,
    `#define PJ_TEXT_COUNT ${texts.length}`,
    `#define PJ_SCRIPT_COUNT ${ctx.scripts.length}`,
    `#define PJ_START_MAP ${model.start.map}`,
    `#define PJ_START_X ${model.start.x}`,
    `#define PJ_START_Y ${model.start.y}`,
    `#define PJ_START_DIR ${model.start.dir}`,
    `#define PJ_BG_TILE_COUNT ${bgTiles.length}`,
    `#define PJ_OBJ_TILE_COUNT ${objTileCount}`,
    `#define PJ_BOX_TILE ${boxTile}`,
    `#define PJ_SLOT_BASE ${slotBase}`,
    `#define PJ_FULL_GLYPH_COUNT ${ctx.fullGlyphs.size}`,
    `#define PJ_SCRIPT_BUF ${GB_SCRIPT_BUF}`,
    "",
    "extern const PjMapInfo pj_maps[];",
    "extern const PjSprite pj_sprites[];",
    ...model.maps.flatMap((m) => [
      `extern const unsigned char pj_map${m.index}_tiles[]; BANKREF_EXTERN(pj_map${m.index}_tiles)`,
      `extern const unsigned char pj_map${m.index}_coll[];`,
      `extern const unsigned char pj_map${m.index}_actors[];`,
      `extern const unsigned char pj_map${m.index}_warps[];`,
    ]),
    "extern const unsigned char pj_bg_tiles[]; BANKREF_EXTERN(pj_bg_tiles)",
    "extern const unsigned char pj_obj_tiles[]; BANKREF_EXTERN(pj_obj_tiles)",
    "extern const unsigned char pj_glyphs_half[]; BANKREF_EXTERN(pj_glyphs_half)",
    "extern const unsigned char pj_glyphs_full[]; BANKREF_EXTERN(pj_glyphs_full)",
    "extern const unsigned int pj_text_offs[]; BANKREF_EXTERN(pj_text_offs)",
    "extern const unsigned char pj_texts[]; BANKREF_EXTERN(pj_texts)",
    "extern const unsigned int pj_script_offs[]; BANKREF_EXTERN(pj_script_offs)",
    "extern const unsigned char pj_scripts[]; BANKREF_EXTERN(pj_scripts)",
    "",
    "#endif",
    "",
  ].join("\n");

  return { files, header };
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------
export async function buildGb(out: CompileOutput, outPath: string): Promise<TargetBuildResult> {
  const { files, header } = lowerGb(out);
  await mkdir(RT + "/gen", { recursive: true });
  await Bun.write(`${RT}/gen_data.h`, header);
  const genSources: string[] = [];
  for (const [name, contents] of Object.entries(files)) {
    const p = `${RT}/gen/${name}`;
    await Bun.write(p, contents);
    genSources.push(p);
  }

  const runtimeSources = ["main", "gbrt", "vm", "textbox"].map((m) => `${RT}/${m}.c`);
  const lcc = `${GBDK}/bin/lcc`;
  const flags = [
    "-Wa-l",
    "-Wl-m",
    "-Wm-yt0x19", // MBC5
    "-Wm-yoA", // auto ROM bank count
    "-Wm-ya0",
    `-Wm-yn${out.game.title.replace(/[^A-Za-z0-9 ]/g, "").slice(0, 15) || "POCKETJS"}`,
    "-autobank",
    `-I${RT}`,
  ];
  await $`${lcc} ${flags} -o ${outPath} ${runtimeSources} ${genSources}`.quiet();
  const size = (await Bun.file(outPath).arrayBuffer()).byteLength;
  return { rom: outPath, size };
}
