[package]
name = "pocket3d-world"
description = "Deterministic physical and reactive world state for Pocket3D"
readme = "README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
glam = { workspace = true, features = ["std", "serde"] }
serde = { workspace = true }
