// Deterministic codegen: contracts/spec/spec.ts -> pocket_spec.h, the C
// header every native host includes for the cross-language input constants
// (button bitmask, analog center). Hosts keep their own platform key codes;
// the portable mask they map onto comes only from here.
//
// Run from PocketJS/:  bun contracts/spec/gen-c.ts
//
// tests/contract.ts imports generateC() and byte-compares its output against
// every committed copy in POCKET_SPEC_HEADERS, so the C constants can never
// drift from spec.ts. Keep this generator free of anything non-deterministic.

import { ANALOG_CENTER, BTN } from "./spec.ts";

/** Every committed copy of the generated header, relative to this file. */
export const POCKET_SPEC_HEADERS = [
  "../../hosts/iphone2g/pocket_spec.h",
  "../../hosts/sifli/include/pocket_spec.h",
] as const;

function hex(n: number, pad = 4): string {
  return "0x" + (n >>> 0).toString(16).toUpperCase().padStart(pad, "0");
}

export function generateC(): string {
  const lines: string[] = [];
  const put = (line = "") => lines.push(line);

  put("/* Generated by contracts/spec/gen-c.ts from contracts/spec/spec.ts.");
  put(" * Do not edit: run `bun contracts/spec/gen-c.ts` and commit the result;");
  put(" * tests/contract.ts byte-compares this file against the generator. */");
  put("#ifndef POCKET_SPEC_H");
  put("#define POCKET_SPEC_H");
  put();
  put("/* Portable button bitmask — identical on every host. Native hosts map");
  put(" * their platform key codes onto these bits; the guest only sees the mask. */");
  for (const [name, value] of Object.entries(BTN)) {
    put(`#define POCKET_BTN_${name} ${hex(value)}U`);
  }
  put();
  put("/* frame(buttons, analog): analog packs a stick as (x << 8) | y, each axis");
  put(" * 0..255 with 128 = center. Hosts without a stick pass this value. */");
  put(`#define POCKET_ANALOG_CENTER ${hex(ANALOG_CENTER)}U`);
  put();
  put("#endif");
  return lines.join("\n") + "\n";
}

if (import.meta.main) {
  const header = generateC();
  for (const relative of POCKET_SPEC_HEADERS) {
    const out = new URL(relative, import.meta.url).pathname;
    await Bun.write(out, header);
    console.log(`wrote ${out}`);
  }
}
