// AUTO-GENERATED by demos/figma/gen-assets.ts (bun demos/figma/gen-assets.ts).
// Deep-zoom tile manifest for the baked Figma pages. The viewer positions and
// streams tiles from THIS data alone — solid tiles never touch the tileset
// blobs (they draw as plain background/solids[] colored rects), only '#'
// tiles go through the loadTileTexture op. Plain .ts (not *.generated.ts) so
// the build's pass-1 scanner walks it.

export const TILE = 256;

export interface FigLevel {
  /** page-px -> level-px scale; level pixel = (pageCoord - origin) * scale */
  scale: number;
  cols: number;
  rows: number;
  /** pak key of this level's TILESET entry (tile index = row * cols + col) */
  key: string;
  /**
   * Row-major tile map, one string per row, one char per tile:
   *   '.'                 solid tile of the page background color (bg)
   *   '#'                 textured tile — stream it via loadTileTexture
   *   'a'..'z' 'A'..'Z'   solid tile of color solids[i], i = a:0 .. z:25, A:26 .. Z:51
   */
  grid: string[];
  /** ABGR colors for the lettered solid tiles above. */
  solids: number[];
}

export interface FigPage {
  name: string;
  /** content origin in page coords (tile (0,0) of every level maps here) */
  ox: number;
  oy: number;
  /** content size in page px */
  w: number;
  h: number;
  /** page background, ABGR u32 */
  bg: number;
  levels: FigLevel[];
}

export const PAGES: FigPage[] = [
  {
    name: "👋 Welcome",
    ox: -2092, oy: 551, w: 6392, h: 1724, bg: 0xffd0d0d0,
    levels: [
      {
        scale: 0.5, cols: 13, rows: 4, key: "ui:tile.fig.0.0",
        solids: [],
        grid: [
          "#############",
          "#############",
          "##..######...",
          "....######...",
        ],
      },
      {
        scale: 0.25, cols: 7, rows: 2, key: "ui:tile.fig.0.1",
        solids: [],
        grid: [
          "#######",
          "#.###..",
        ],
      },
      {
        scale: 0.125, cols: 4, rows: 1, key: "ui:tile.fig.0.2",
        solids: [],
        grid: [
          "####",
        ],
      },
      {
        scale: 0.0625, cols: 2, rows: 1, key: "ui:tile.fig.0.3",
        solids: [],
        grid: [
          "##",
        ],
      },
    ],
  },
  {
    name: "🧩 Components",
    ox: -3272, oy: 1857, w: 18280, h: 2537, bg: 0xffd2d2d2,
    levels: [
      {
        scale: 1, cols: 72, rows: 10, key: "ui:tile.fig.1.0",
        solids: [0xffffffff, 0xff999999],
        grid: [
          "#####.##################################################################",
          "#####.########aa#######################################a##########a#####",
          "#####.########aa##########..#####.#####...##..#########a##############b#",
          "......####a###aa##########....###...............##..###a##########a###b#",
          "......#########a#......###....###...............##..###a################",
          "...........######......###....###...............##..###a####.##aa#aaaaa#",
          "...........######......###..........................########.#####a##aa#",
          "...........######......###..............................####.#####a##aa#",
          "...........######.......................................####.###########",
          "...........######.......................................####.###########",
        ],
      },
      {
        scale: 0.5, cols: 36, rows: 5, key: "ui:tile.fig.1.1",
        solids: [0xffffffff],
        grid: [
          "####################################",
          "#######a#####.######.#.#############",
          "...######..##..##.......#.##########",
          ".....####..##.............##########",
          ".....####...................########",
        ],
      },
      {
        scale: 0.25, cols: 18, rows: 3, key: "ui:tile.fig.1.2",
        solids: [],
        grid: [
          "##################",
          ".########...######",
          "..###.........####",
        ],
      },
      {
        scale: 0.125, cols: 9, rows: 2, key: "ui:tile.fig.1.3",
        solids: [],
        grid: [
          "#########",
          ".##....##",
        ],
      },
      {
        scale: 0.0625, cols: 5, rows: 1, key: "ui:tile.fig.1.4",
        solids: [],
        grid: [
          "#####",
        ],
      },
      {
        scale: 0.03125, cols: 3, rows: 1, key: "ui:tile.fig.1.5",
        solids: [],
        grid: [
          "###",
        ],
      },
      {
        scale: 0.015625, cols: 2, rows: 1, key: "ui:tile.fig.1.6",
        solids: [],
        grid: [
          "##",
        ],
      },
    ],
  },
  {
    name: "🍉 Stickers",
    ox: -4100, oy: 12177, w: 1588, h: 993, bg: 0xffededed,
    levels: [
      {
        scale: 1, cols: 7, rows: 4, key: "ui:tile.fig.2.0",
        solids: [],
        grid: [
          "#######",
          "#######",
          "#######",
          "#######",
        ],
      },
      {
        scale: 0.5, cols: 4, rows: 2, key: "ui:tile.fig.2.1",
        solids: [],
        grid: [
          "####",
          "####",
        ],
      },
      {
        scale: 0.25, cols: 2, rows: 1, key: "ui:tile.fig.2.2",
        solids: [],
        grid: [
          "##",
        ],
      },
    ],
  },
  {
    name: "🌈 Examples",
    ox: -1925, oy: 5912, w: 26229, h: 10360, bg: 0xfff2f2f2,
    levels: [
      {
        scale: 0.5, cols: 52, rows: 21, key: "ui:tile.fig.3.0",
        solids: [0xffd8d8d8],
        grid: [
          "..##aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa#",
          "###############aaaa##########aaaa########aaaaaaaaaa#",
          "###############aaaa##########aaaa########aaaaaaaaaa#",
          "###############aaaa##########aaaa########aaaaaaaaaa#",
          "..##########aaaaaaa#######aaaaaaa#######aaaaaaaaaaa#",
          "..##########aaaaaaa#######aaaaaaa#######aaaaaaaaaaa#",
          "..##########aaaaaaa#######aaaaaaa#######aaaaaaaaaaa#",
          "..##########aaaaaaa#######aaaaaaa#######aaaaaaaaaaa#",
          "..#########aaaaaaaa#############a#################a#",
          "..#########aaaaaaaa#############a#################a#",
          "..#########aaaaaaaa#############a#################a#",
          "..#########aaaaaaaa#############a#################a#",
          "..###############aa#######aaaaaaa######aaaaaaaaaaaa#",
          "..###############aa#######aaaaaaa######aaaaaaaaaaaa#",
          "..###############aa#######aaaaaaa######aaaaaaaaaaaa#",
          "..###############aa#######aaaaaaa######aaaaaaaaaaaa#",
          "..############aaaaa########aaaaaaaaaaaaaaaaaaaaaaaa#",
          "..############aaaaa########aaaaaaaaaaaaaaaaaaaaaaaa#",
          "..############aaaaa########aaaaaaaaaaaaaaaaaaaaaaaa#",
          "..############aaaaa########aaaaaaaaaaaaaaaaaaaaaaaa#",
          "..##################################################",
        ],
      },
      {
        scale: 0.25, cols: 26, rows: 11, key: "ui:tile.fig.3.1",
        solids: [0xffd8d8d8],
        grid: [
          "########a######a#####aaaa#",
          "########a######a#####aaaa#",
          ".#####aaa####aaa####aaaaa#",
          ".#####aaa####aaa####aaaaa#",
          ".#####aaa#################",
          ".#####aaa#################",
          ".############aaa####aaaaa#",
          ".############aaa####aaaaa#",
          ".######aa#####aaaaaaaaaaa#",
          ".######aa#####aaaaaaaaaaa#",
          ".#########################",
        ],
      },
      {
        scale: 0.125, cols: 13, rows: 6, key: "ui:tile.fig.3.2",
        solids: [0xffd8d8d8],
        grid: [
          "###########a#",
          "###a###a##aa#",
          "###a#########",
          "#######a##aa#",
          "#######aaaaa#",
          "#############",
        ],
      },
      {
        scale: 0.0625, cols: 7, rows: 3, key: "ui:tile.fig.3.3",
        solids: [],
        grid: [
          "#######",
          "#######",
          "#######",
        ],
      },
      {
        scale: 0.03125, cols: 4, rows: 2, key: "ui:tile.fig.3.4",
        solids: [],
        grid: [
          "####",
          "####",
        ],
      },
      {
        scale: 0.015625, cols: 2, rows: 1, key: "ui:tile.fig.3.5",
        solids: [],
        grid: [
          "##",
        ],
      },
    ],
  },
];
