// aot/spec/gen-c.ts — generate runtime/pjgb_gen.h from spec/pjgb.ts so the C
// runtime can never drift from the TS compiler. Mirrors ../../spec/gen-rust.ts.
//
//   bun aot/spec/gen-c.ts   (writes aot/runtime/pjgb_gen.h)

import {
  ACTOR_FLAG,
  ACTOR_INSTANCE_SIZE,
  BUDGET,
  CHUNK,
  COLLISION_SOLID,
  COLLISION_WALKABLE,
  DBG,
  DEBUG_ADDR,
  DEBUG_BLOCK_SIZE,
  DEBUG_MAGIC,
  DIR,
  EWRAM_BASE,
  GAME_HEADER_SIZE,
  GAME_TITLE_LEN,
  MAP_HEADER_SIZE,
  MOVE,
  OP,
  PJGB_CHUNK_ENTRY_SIZE,
  PJGB_HEADER_SIZE,
  PJGB_VERSION,
  SCREEN_H,
  SCREEN_TILES_H,
  SCREEN_TILES_W,
  SCREEN_W,
  SCRIPT_NONE,
  SPRITE_PROTO_SIZE,
  TILE_4BPP_BYTES,
  VM_MAX_STACK,
  WARP_SIZE,
} from "./pjgb.ts";

function section(title: string): string {
  return `\n/* ${"-".repeat(70)}\n * ${title}\n * ${"-".repeat(70)} */\n`;
}
function defs(prefix: string, obj: Record<string, number>): string {
  return Object.entries(obj)
    .map(([k, v]) => `#define ${prefix}${k} ${v >= 0 ? `0x${(v >>> 0).toString(16)}` : v}`)
    .join("\n");
}

const lines: string[] = [];
lines.push("// GENERATED by aot/spec/gen-c.ts from aot/spec/pjgb.ts — DO NOT EDIT.");
lines.push("#ifndef PJGB_GEN_H");
lines.push("#define PJGB_GEN_H");
lines.push("#include <stdint.h>");

lines.push(section("Screen / tiles"));
lines.push(defs("PJGB_", {
  SCREEN_W,
  SCREEN_H,
  SCREEN_TILES_W,
  SCREEN_TILES_H,
  TILE_4BPP_BYTES,
}));

lines.push(section("Container header + chunks"));
lines.push(defs("PJGB_", {
  VERSION: PJGB_VERSION,
  HEADER_SIZE: PJGB_HEADER_SIZE,
  CHUNK_ENTRY_SIZE: PJGB_CHUNK_ENTRY_SIZE,
}));
lines.push(defs("CHUNK_", CHUNK));

lines.push(section("Struct sizes / field constants"));
lines.push(defs("PJGB_", {
  GAME_TITLE_LEN,
  GAME_HEADER_SIZE,
  MAP_HEADER_SIZE,
  ACTOR_INSTANCE_SIZE,
  WARP_SIZE,
  SPRITE_PROTO_SIZE,
  SCRIPT_NONE,
  COLLISION_WALKABLE,
  COLLISION_SOLID,
}));

lines.push(section("Directions / movement / actor flags"));
lines.push(defs("DIR_", DIR));
lines.push(defs("MOVE_", MOVE));
lines.push(defs("ACTOR_FLAG_", ACTOR_FLAG));

lines.push(section("Script VM"));
lines.push(defs("OP_", OP));
lines.push(defs("PJGB_", { VM_MAX_STACK }));

lines.push(section("Debug block (fixed EWRAM address for the mGBA harness)"));
lines.push(defs("PJGB_", { EWRAM_BASE, DEBUG_ADDR, DEBUG_BLOCK_SIZE }));
lines.push(`#define DEBUG_MAGIC 0x${(DEBUG_MAGIC >>> 0).toString(16)}`);
lines.push(defs("DBG_", DBG));

lines.push(section("Budgets"));
lines.push(defs("BUDGET_", BUDGET));

lines.push("\n#endif /* PJGB_GEN_H */\n");

const out = new URL("../runtime/pjgb_gen.h", import.meta.url).pathname;
await Bun.write(out, lines.join("\n"));
console.log("wrote", out);
