// aot/spec/gen-c.ts — generate runtime/<target>/pjgb_gen.h from spec/pjgb.ts
// so no C runtime can drift from the TS compiler. Mirrors ../../spec/gen-rust.ts.
//
//   bun aot/spec/gen-c.ts   (writes aot/runtime/{gba,gb,nes}/pjgb_gen.h)

import {
  ACTOR_FLAG,
  ACTOR_INSTANCE_SIZE,
  BUDGET,
  CHUNK,
  COLLISION_SOLID,
  COLLISION_WALKABLE,
  DBG,
  DEBUG_BLOCK_SIZE,
  DEBUG_MAGIC,
  DIR,
  GAME_HEADER_SIZE,
  GAME_TITLE_LEN,
  GLYPH_STORE_HEADER_SIZE,
  HALF_GLYPH_COUNT,
  MAP_HEADER_SIZE,
  MOVE,
  OP,
  PJGB_CHUNK_ENTRY_SIZE,
  PJGB_HEADER_SIZE,
  PJGB_VERSION,
  SCRIPT_NONE,
  SPRITE_PROTO_SIZE,
  TARGETS,
  TEXT_MODE,
  TILE_2BPP_BYTES,
  TILE_4BPP_BYTES,
  TOK_ASCII_MAX,
  TOK_ASCII_MIN,
  TOK_END,
  TOK_FULL_FLAG,
  TOK_NEWLINE,
  VM_MAX_STACK,
  WARP_SIZE,
  type TargetName,
} from "./pjgb.ts";

function section(title: string): string {
  return `\n/* ${"-".repeat(70)}\n * ${title}\n * ${"-".repeat(70)} */\n`;
}
function defs(prefix: string, obj: Record<string, number>): string {
  return Object.entries(obj)
    .map(([k, v]) => `#define ${prefix}${k} ${v >= 0 ? `0x${(v >>> 0).toString(16)}` : v}`)
    .join("\n");
}

function header(target: TargetName): string {
  const t = TARGETS[target];
  const lines: string[] = [];
  lines.push(`// GENERATED by aot/spec/gen-c.ts from aot/spec/pjgb.ts (${target}) — DO NOT EDIT.`);
  lines.push("#ifndef PJGB_GEN_H");
  lines.push("#define PJGB_GEN_H");

  lines.push(section("Target"));
  lines.push(defs("PJGB_", {
    SCREEN_W: t.screenW,
    SCREEN_H: t.screenH,
    SCREEN_TILES_W: t.screenW / 8,
    SCREEN_TILES_H: t.screenH / 8,
    MAX_MAP_W: t.maxMapW,
    MAX_MAP_H: t.maxMapH,
    TILE_BYTES: t.tileBytes,
    TILE_4BPP_BYTES,
    TILE_2BPP_BYTES,
  }));

  lines.push(section("Text (cjk16 metrics; layout anchors live in the runtime)"));
  lines.push(defs("PJGB_TEXT_", {
    COLS: t.textCols,
    LINES: t.textLines,
    CHOICE_COLS: t.choiceCols,
    MAX_CHOICES: t.maxChoices,
    GLYPH_SLOTS: t.glyphSlots,
  }));
  lines.push(defs("TEXT_MODE_", TEXT_MODE));
  lines.push(defs("TOK_", {
    END: TOK_END,
    NEWLINE: TOK_NEWLINE,
    ASCII_MIN: TOK_ASCII_MIN,
    ASCII_MAX: TOK_ASCII_MAX,
    FULL_FLAG: TOK_FULL_FLAG,
  }));
  lines.push(defs("PJGB_", { HALF_GLYPH_COUNT, GLYPH_STORE_HEADER_SIZE }));

  lines.push(section("Container header + chunks (GBA parses; GB/NES get gen_data)"));
  lines.push(defs("PJGB_", {
    VERSION: PJGB_VERSION,
    HEADER_SIZE: PJGB_HEADER_SIZE,
    CHUNK_ENTRY_SIZE: PJGB_CHUNK_ENTRY_SIZE,
  }));
  lines.push(defs("CHUNK_", CHUNK));

  lines.push(section("Struct sizes / field constants"));
  lines.push(defs("PJGB_", {
    GAME_TITLE_LEN,
    GAME_HEADER_SIZE,
    MAP_HEADER_SIZE,
    ACTOR_INSTANCE_SIZE,
    WARP_SIZE,
    SPRITE_PROTO_SIZE,
    SCRIPT_NONE,
    COLLISION_WALKABLE,
    COLLISION_SOLID,
  }));

  lines.push(section("Directions / movement / actor flags"));
  lines.push(defs("DIR_", DIR));
  lines.push(defs("MOVE_", MOVE));
  lines.push(defs("ACTOR_FLAG_", ACTOR_FLAG));

  lines.push(section("Script VM"));
  lines.push(defs("OP_", OP));
  lines.push(defs("PJGB_", { VM_MAX_STACK }));

  lines.push(section("Debug block (fixed RAM address for the emulator harness)"));
  lines.push(defs("PJGB_", { DEBUG_ADDR: t.debugAddr, DEBUG_BLOCK_SIZE }));
  lines.push(`#define DEBUG_MAGIC 0x${(DEBUG_MAGIC >>> 0).toString(16)}`);
  lines.push(defs("DBG_", DBG));

  lines.push(section("Budgets"));
  lines.push(defs("BUDGET_", BUDGET));

  lines.push("\n#endif /* PJGB_GEN_H */\n");
  return lines.join("\n");
}

for (const target of Object.keys(TARGETS) as TargetName[]) {
  const out = new URL(`../runtime/${target}/pjgb_gen.h`, import.meta.url).pathname;
  await Bun.write(out, header(target));
  console.log("wrote", out);
}
