// saga/compiler/emit.ts — residualize the CompiledFilm into runtime/gen_data.c.
// Everything is plain C arrays in ROM; no container parsing at runtime.

import type { CompiledFilm, CompiledScene } from "./index.ts";

function u8arr(name: string, data: Uint8Array): string {
  const lines: string[] = [`static const u8 ${name}[] = {`];
  for (let i = 0; i < data.length; i += 24) {
    lines.push("  " + Array.from(data.subarray(i, i + 24)).join(",") + ",");
  }
  lines.push("};");
  return lines.join("\n");
}

function u16arr(name: string, data: Uint16Array | number[]): string {
  const arr = Array.from(data);
  const lines: string[] = [`static const u16 ${name}[] = {`];
  for (let i = 0; i < arr.length; i += 16) {
    lines.push("  " + arr.slice(i, i + 16).map((v) => "0x" + v.toString(16)).join(",") + ",");
  }
  lines.push("};");
  return lines.join("\n");
}

function u32arr(name: string, data: number[]): string {
  const lines: string[] = [`static const u32 ${name}[] = {`];
  for (let i = 0; i < data.length; i += 12) {
    lines.push("  " + data.slice(i, i + 12).map((v) => String(v >>> 0)).join(",") + ",");
  }
  lines.push("};");
  return lines.join("\n");
}

export function emitGenData(film: CompiledFilm): string {
  const parts: string[] = [
    "/* gen_data.c — GENERATED by saga/compiler. Do not edit. */",
    '#include "saga.h"',
    "",
  ];

  film.scenes.forEach((s: CompiledScene, i: number) => {
    parts.push(u16arr(`s${i}_pal_bg`, s.palBg));
    parts.push(u16arr(`s${i}_pal_obj`, s.palObj));
    parts.push(u8arr(`s${i}_tiles_main`, s.tilesMain));
    if (s.nShared) parts.push(u8arr(`s${i}_tiles_shared`, s.tilesShared));
    parts.push(u16arr(`s${i}_map_main`, s.mapMain));
    if (s.mapFar) parts.push(u16arr(`s${i}_map_far`, s.mapFar));
    if (s.mapSky) parts.push(u16arr(`s${i}_map_sky`, s.mapSky));
    if (s.gradient) parts.push(u16arr(`s${i}_grad`, s.gradient));
    if (s.objTiles.length) parts.push(u8arr(`s${i}_obj`, s.objTiles));
    if (s.protos.length) {
      const rows = s.protos
        .map((p) => `  {${p.tileBase},${p.w},${p.h},${p.frames},${p.palbank},${p.fps},${p.walkFpd}},`)
        .join("\n");
      parts.push(`static const SagaProto s${i}_protos[] = {\n${rows}\n};`);
    }
    parts.push(u8arr(`s${i}_cue`, s.cue));
    parts.push(u16arr(`s${i}_cue_offs`, s.cueOffs));
    if (s.world) {
      const w = s.world;
      parts.push(u8arr(`s${i}_solid`, w.solid));
      if (w.npcs.length) {
        const rows = w.npcs
          .map((n) => `  {${n.cx},${n.cy},${n.dir},${n.slot},${n.proto},${n.cue},${n.solid}},`)
          .join("\n");
        parts.push(`static const SagaNpc s${i}_npcs[] = {\n${rows}\n};`);
      }
      if (w.trigs.length) {
        const rows = w.trigs
          .map((t) => `  {${t.cx},${t.cy},${t.w},${t.h},${t.kind},${t.value},${t.cue}},`)
          .join("\n");
        parts.push(`static const SagaTrig s${i}_trigs[] = {\n${rows}\n};`);
      }
      parts.push(
        `static const SagaWorld s${i}_world = { ${w.cols}, ${w.rows}, s${i}_solid, ` +
          `${w.startCx}, ${w.startCy}, ${w.startDir}, ${w.playerSlot}, ${w.playerProto}, ` +
          `${w.npcs.length ? `s${i}_npcs` : "0"}, ${w.npcs.length}, ` +
          `${w.trigs.length ? `s${i}_trigs` : "0"}, ${w.trigs.length} };`,
      );
    }
    parts.push("");
  });

  parts.push(u32arr("film_text_offs", film.textOffs));
  parts.push(u8arr("film_text_blob", film.textBlob));
  parts.push(u8arr("film_glyphs", film.glyphs));
  parts.push(u8arr("film_ui_bg", film.uiBg));
  parts.push(u8arr("film_ui_obj", film.uiObj));
  parts.push("");

  const rows = film.scenes.map((s, i) => {
    const f = (b: boolean, t: string) => (b ? t : "0");
    return [
      "  {",
      `s${i}_pal_bg, s${i}_pal_obj,`,
      `s${i}_tiles_main, ${s.nMain},`,
      `${s.nShared ? `s${i}_tiles_shared` : "0"}, ${s.nShared},`,
      `s${i}_map_main,`,
      `${f(!!s.mapFar, `s${i}_map_far`)}, ${f(!!s.mapSky, `s${i}_map_sky`)},`,
      `${s.mapSz},`,
      `${s.farFacQ8}, ${s.skyFacQ8}, ${s.farVxQ8}, ${s.skyVxQ8},`,
      `${f(!!s.gradient, `s${i}_grad`)},`,
      `${s.objTiles.length ? `s${i}_obj` : "0"}, ${s.objTiles.length},`,
      `${s.protos.length ? `s${i}_protos` : "0"}, ${s.protos.length},`,
      `s${i}_cue, ${s.cue.length},`,
      `s${i}_cue_offs, ${s.cueOffs.length},`,
      `${s.kind}, ${f(!!s.world, `&s${i}_world`)},`,
      `${s.cam0}, ${s.camMin}, ${s.camMax},`,
      `${s.rasterMode}, ${s.rasterAmp}, ${s.letterbox0}, 0x${s.backdrop.toString(16)}`,
      "},",
    ].join(" ");
  });
  parts.push(`static const SagaScene film_scenes[] = {\n${rows.join("\n")}\n};`);
  parts.push("");
  parts.push(
    `const SagaFilm film = { film_scenes, ${film.scenes.length}, film_text_offs, film_text_blob, ` +
      `${film.textOffs.length}, film_glyphs, ${film.nHalfcells}, film_ui_bg, film_ui_obj, ${film.uiObj.length} };`,
  );
  parts.push("");
  return parts.join("\n");
}
