[package]
name = "pocketjs-idf-native-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
pocketjs-idf-ui-core = { path = "../../native/ui-core" }
pocketjs-idf-render-rgb565 = { path = "../../native/render-rgb565" }
pocketjs-idf-abi = { path = "../../native/abi" }

[workspace]
