// GENERATED by aot/spec/gen-c.ts from aot/spec/pjgb.ts (3ds) — DO NOT EDIT.
#ifndef PJGB_GEN_H
#define PJGB_GEN_H

/* ----------------------------------------------------------------------
 * Target
 * ---------------------------------------------------------------------- */

#define PJGB_SCREEN_W 0xc8
#define PJGB_SCREEN_H 0x78
#define PJGB_SCREEN_TILES_W 0x19
#define PJGB_SCREEN_TILES_H 0xf
#define PJGB_MAX_MAP_W 0x20
#define PJGB_MAX_MAP_H 0x20
#define PJGB_TILE_BYTES 0x20
#define PJGB_TILE_4BPP_BYTES 0x20
#define PJGB_TILE_2BPP_BYTES 0x10

/* ----------------------------------------------------------------------
 * Text (cjk16 metrics; layout anchors live in the runtime)
 * ---------------------------------------------------------------------- */

#define PJGB_TEXT_COLS 0x24
#define PJGB_TEXT_LINES 0x4
#define PJGB_TEXT_CHOICE_COLS 0x22
#define PJGB_TEXT_MAX_CHOICES 0x4
#define PJGB_TEXT_GLYPH_SLOTS 0x90
#define TEXT_MODE_ASCII8 0x0
#define TEXT_MODE_CJK16 0x1
#define TOK_END 0x0
#define TOK_NEWLINE 0xa
#define TOK_ASCII_MIN 0x20
#define TOK_ASCII_MAX 0x7e
#define TOK_FULL_FLAG 0x80
#define PJGB_HALF_GLYPH_COUNT 0x5f
#define PJGB_GLYPH_STORE_HEADER_SIZE 0x8

/* ----------------------------------------------------------------------
 * Container header + chunks (GBA parses; GB/NES get gen_data)
 * ---------------------------------------------------------------------- */

#define PJGB_VERSION 0x1
#define PJGB_HEADER_SIZE 0x10
#define PJGB_CHUNK_ENTRY_SIZE 0x10
#define CHUNK_GAME 0x1
#define CHUNK_PAL_BG 0x2
#define CHUNK_PAL_OBJ 0x3
#define CHUNK_TILES_BG 0x4
#define CHUNK_TILES_OBJ 0x5
#define CHUNK_MAP 0x6
#define CHUNK_TEXT_BANK 0x7
#define CHUNK_SCRIPT_CODE 0x8
#define CHUNK_SCRIPT_TABLE 0x9
#define CHUNK_SPRITE_TABLE 0xa
#define CHUNK_GLYPHS 0xb

/* ----------------------------------------------------------------------
 * Struct sizes / field constants
 * ---------------------------------------------------------------------- */

#define PJGB_GAME_TITLE_LEN 0x18
#define PJGB_GAME_HEADER_SIZE 0x30
#define PJGB_MAP_HEADER_SIZE 0x1c
#define PJGB_ACTOR_INSTANCE_SIZE 0xc
#define PJGB_WARP_SIZE 0xc
#define PJGB_SPRITE_PROTO_SIZE 0x8
#define PJGB_SCRIPT_NONE 0xffff
#define PJGB_COLLISION_WALKABLE 0x0
#define PJGB_COLLISION_SOLID 0x1

/* ----------------------------------------------------------------------
 * Directions / movement / actor flags
 * ---------------------------------------------------------------------- */

#define DIR_DOWN 0x0
#define DIR_UP 0x1
#define DIR_LEFT 0x2
#define DIR_RIGHT 0x3
#define MOVE_STATIC 0x0
#define MOVE_WANDER 0x1
#define MOVE_PATROL_H 0x2
#define MOVE_PATROL_V 0x3
#define ACTOR_FLAG_NONE 0x0
#define ACTOR_FLAG_SOLID 0x1

/* ----------------------------------------------------------------------
 * Script VM
 * ---------------------------------------------------------------------- */

#define OP_END 0x0
#define OP_NOP 0x1
#define OP_TEXT 0x2
#define OP_SET_FLAG 0x3
#define OP_CLEAR_FLAG 0x4
#define OP_PUSH_FLAG 0x5
#define OP_PUSH_CONST 0x6
#define OP_POP 0x7
#define OP_DUP 0x8
#define OP_EQ 0x9
#define OP_NE 0xa
#define OP_NOT 0xb
#define OP_JUMP 0xc
#define OP_JUMP_IF_FALSE 0xd
#define OP_CHOICE 0xe
#define OP_LOCK_PLAYER 0xf
#define OP_RELEASE_PLAYER 0x10
#define OP_FACE_PLAYER 0x11
#define OP_WARP 0x12
#define OP_SET_VAR 0x13
#define OP_ADD_VAR 0x14
#define OP_PUSH_VAR 0x15
#define OP_GIVE_ITEM 0x16
#define OP_BATTLE 0x17
#define OP_WAIT 0x18
#define OP_PLAY_SFX 0x19
#define OP_LT 0x1a
#define OP_GT 0x1b
#define OP_LE 0x1c
#define OP_GE 0x1d
#define OP_RND 0x1e
#define PJGB_VM_MAX_STACK 0x10

/* ----------------------------------------------------------------------
 * Debug block (fixed RAM address for the emulator harness)
 * ---------------------------------------------------------------------- */

#define PJGB_DEBUG_ADDR 0x14000000
#define PJGB_DEBUG_BLOCK_SIZE 0x44
#define DEBUG_MAGIC 0x504a4442
#define DBG_MAGIC 0x0
#define DBG_PLAYER_X 0x4
#define DBG_PLAYER_Y 0x6
#define DBG_PLAYER_DIR 0x8
#define DBG_CUR_MAP 0x9
#define DBG_TEXT_ACTIVE 0xa
#define DBG_SCRIPT_ACTIVE 0xb
#define DBG_FRAME 0xc
#define DBG_CUR_TEXT 0x10
#define DBG_CHOICE_CURSOR 0x12
#define DBG_BOOTED 0x13
#define DBG_FLAGS 0x14
#define DBG_VARS 0x24

/* ----------------------------------------------------------------------
 * Budgets
 * ---------------------------------------------------------------------- */

#define BUDGET_MAX_ACTORS_PER_MAP 0x18
#define BUDGET_MAX_MAPS 0x20
#define BUDGET_MAX_SPRITES 0x10
#define BUDGET_MAX_FLAGS 0x80
#define BUDGET_MAX_VARS 0x10
#define BUDGET_MAX_TEXTS 0x200
#define BUDGET_MAX_SCRIPTS 0xfe
#define BUDGET_MAX_BG_TILES 0x200
#define BUDGET_MAX_OBJ_TILES 0x400
#define BUDGET_MAX_MAP_TILES 0x4000
#define BUDGET_MAX_FULL_GLYPHS 0x200

#endif /* PJGB_GEN_H */
