// aot/compiler/pack.ts — assemble chunks into the PJGB container blob and emit
// it as a C byte array (gen_cart.c) for linking into the ROM.

import {
  ByteWriter,
  PJGB_CHUNK_ENTRY_SIZE,
  PJGB_HEADER_SIZE,
  PJGB_MAGIC_BYTES,
  PJGB_VERSION,
} from "../spec/pjgb.ts";

export interface Chunk {
  kind: number;
  id: number;
  data: Uint8Array;
}

const align4 = (n: number): number => (n + 3) & ~3;

/** Pack chunks into a PJGB blob: [header][chunk table][chunk data...]. */
export function packCart(chunks: Chunk[]): Uint8Array {
  const tableOff = PJGB_HEADER_SIZE;
  const dataStart = align4(tableOff + chunks.length * PJGB_CHUNK_ENTRY_SIZE);

  let off = dataStart;
  const offsets = chunks.map((c) => {
    const o = off;
    off += align4(c.data.length);
    return o;
  });
  const total = off;

  const w = new ByteWriter();
  w.bytes(PJGB_MAGIC_BYTES).u16(PJGB_VERSION).u16(chunks.length).u32(tableOff).u32(total);
  chunks.forEach((c, i) => {
    w.u32(c.kind).u32(c.id).u32(offsets[i]).u32(c.data.length);
  });
  w.align4();
  chunks.forEach((c) => {
    w.bytes(c.data).align4();
  });

  const out = w.toUint8Array();
  if (out.length !== total) {
    throw new Error(`pack: size mismatch ${out.length} != ${total}`);
  }
  return out;
}

/** Emit the blob as a linkable C source file. */
export function emitCartC(blob: Uint8Array): string {
  const rows: string[] = [];
  for (let i = 0; i < blob.length; i += 16) {
    const slice = Array.from(blob.slice(i, i + 16)).map((b) => `0x${b.toString(16).padStart(2, "0")}`);
    rows.push("  " + slice.join(",") + ",");
  }
  return [
    "// GENERATED by @pocketjs/aot — the PJGB cartridge blob linked into the ROM.",
    "const unsigned char __attribute__((aligned(4))) pjgb_cart[] = {",
    ...rows,
    "};",
    `const unsigned int pjgb_cart_len = ${blob.length};`,
    "",
  ].join("\n");
}
