// demos/nightbloom/gen-assets.ts — NIGHTBLOOM's content pipeline: every unit
// sprite, projectile and backdrop is generated by the PixelLab pixel-art API
// (pixellab.ai) from the seeded ART manifest in data.ts, then normalized into
// the pak-safe PNG subset. Same contract as demos/tidelight/gen-assets.ts:
//
//   bun demos/nightbloom/gen-assets.ts             # generate missing assets
//   bun demos/nightbloom/gen-assets.ts --force     # regenerate everything
//   bun demos/nightbloom/gen-assets.ts --only=p-catnip-1.png
//
// Auth: PIXELLAB_API_KEY in the repo root .env. Every entry pins a `seed`, so
// a re-run reproduces the same art; generated files are committed, which makes
// the script a cheap no-op unless an asset is deleted or --force is passed.
//
// Evolution stages are init_image chains (stage II derives from stage I,
// III from II) so a creature keeps its identity as it ascends — the same
// identity-preserving trick tidelight uses for portrait moods, applied to
// a whole bestiary.
//
// Output discipline: replies are decoded and re-encoded through the exact
// canonical subset the pak build accepts (colorType 6, bit depth 8, filter 0,
// single node:zlib IDAT) so committed bytes stay deterministic.

import { existsSync, readFileSync } from "node:fs";
import { deflateSync } from "node:zlib";
import { decodePng } from "../../compiler/pak.ts";
import { ART, validateContent, type ArtEntry } from "./data.ts";

const HERE = new URL(".", import.meta.url).pathname; // demos/nightbloom/
const ROOT = new URL("../..", import.meta.url).pathname; // PocketJS/
const API = "https://api.pixellab.ai/v1";

// ---------------------------------------------------------------------------
// Canonical PNG encoder (identical subset to demos/tidelight/gen-assets.ts,
// validated against compiler/pak.ts decodePng)
// ---------------------------------------------------------------------------

const CRC = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; t[n] = c >>> 0; }
  return t;
})();
function crc32(buf: Uint8Array): number { let c = 0xffffffff; for (let i = 0; i < buf.length; i++) c = CRC[(c ^ buf[i]) & 255] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; }
function u32be(n: number): Uint8Array { const b = new Uint8Array(4); new DataView(b.buffer).setUint32(0, n >>> 0, false); return b; }
function chunk(type: string, data: Uint8Array): Uint8Array {
  const tb = new TextEncoder().encode(type);
  const body = new Uint8Array(tb.length + data.length); body.set(tb, 0); body.set(data, tb.length);
  const out = new Uint8Array(4 + body.length + 4);
  out.set(u32be(data.length), 0); out.set(body, 4); out.set(u32be(crc32(body)), 4 + body.length);
  return out;
}
function encodePng(w: number, h: number, rgba: Uint8Array): Uint8Array {
  const stride = w * 4;
  const raw = new Uint8Array((stride + 1) * h);
  for (let y = 0; y < h; y++) { raw[y * (stride + 1)] = 0; raw.set(rgba.subarray(y * stride, y * stride + stride), y * (stride + 1) + 1); }
  const ihdr = new Uint8Array(13); const dv = new DataView(ihdr.buffer);
  dv.setUint32(0, w, false); dv.setUint32(4, h, false); ihdr[8] = 8; ihdr[9] = 6;
  const idat = new Uint8Array(deflateSync(raw));
  const sig = new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10]);
  const parts = [sig, chunk("IHDR", ihdr), chunk("IDAT", idat), chunk("IEND", new Uint8Array(0))];
  const total = parts.reduce((n, p) => n + p.length, 0); const out = new Uint8Array(total);
  let o = 0; for (const p of parts) { out.set(p, o); o += p.length; } return out;
}

// ---------------------------------------------------------------------------
// PixelLab client
// ---------------------------------------------------------------------------

function apiKey(): string {
  const env = process.env.PIXELLAB_API_KEY;
  if (env) return env;
  const envPath = ROOT + ".env";
  if (existsSync(envPath)) {
    const m = readFileSync(envPath, "utf8").match(/^PIXELLAB_API_KEY=["']?([^"'\n]+)["']?$/m);
    if (m) return m[1];
  }
  throw new Error("nightbloom: PIXELLAB_API_KEY not set (repo .env or environment)");
}

async function generate(key: string, asset: ArtEntry): Promise<Uint8Array> {
  const body: Record<string, unknown> = {
    description: asset.prompt,
    image_size: { width: asset.w, height: asset.h },
    text_guidance_scale: 8,
    no_background: asset.transparent ?? false,
    seed: asset.seed,
  };
  if (asset.direction) body.direction = asset.direction;
  if (asset.shading) body.shading = asset.shading;
  if (asset.detail) body.detail = asset.detail;
  if (asset.initFrom) {
    const initPath = HERE + asset.initFrom;
    if (!existsSync(initPath)) throw new Error(`nightbloom: init image ${asset.initFrom} missing — the manifest orders bases first`);
    const bytes = new Uint8Array(await Bun.file(initPath).arrayBuffer());
    body.init_image = { type: "base64", base64: Buffer.from(bytes).toString("base64") };
    body.init_image_strength = asset.initStrength ?? 300;
  }

  for (let attempt = 1; ; attempt++) {
    let res: Response;
    try {
      res = await fetch(`${API}/generate-image-pixflux`, {
        method: "POST",
        headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
    } catch (err) {
      if (attempt <= 3) {
        console.log(`  network error (${err instanceof Error ? err.message : err}), retry ${attempt}/3 in 5s ...`);
        await Bun.sleep(5000);
        continue;
      }
      throw err;
    }
    if (res.status === 429 && attempt <= 3) {
      console.log(`  rate limited, retry ${attempt}/3 in 5s ...`);
      await Bun.sleep(5000);
      continue;
    }
    if (!res.ok) {
      const detail = await res.text();
      throw new Error(`nightbloom: pixellab ${res.status} for ${asset.name}: ${detail.slice(0, 300)}`);
    }
    const json = (await res.json()) as { image: { base64: string } };
    return Uint8Array.from(Buffer.from(json.image.base64, "base64"));
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const problems = validateContent();
  if (problems.length > 0) {
    throw new Error(`nightbloom: content tables are inconsistent:\n  ${problems.join("\n  ")}`);
  }

  const force = process.argv.includes("--force");
  const only = process.argv.find((a) => a.startsWith("--only="))?.slice("--only=".length);
  const key = apiKey();

  let generated = 0;
  let skipped = 0;
  for (const asset of ART) {
    const path = HERE + asset.name;
    if (only && asset.name !== only) continue;
    if (existsSync(path) && !force && !only) {
      skipped++;
      continue;
    }
    const t0 = Date.now();
    const png = await generate(key, asset);
    const img = decodePng(png); // validate against the pak decoder's subset
    if (img.width !== asset.w || img.height !== asset.h) {
      throw new Error(`nightbloom: ${asset.name} came back ${img.width}x${img.height}, wanted ${asset.w}x${asset.h}`);
    }
    await Bun.write(path, encodePng(img.width, img.height, img.rgba));
    generated++;
    console.log(`  generated ${asset.name}  ${asset.w}x${asset.h} seed ${asset.seed}  (${((Date.now() - t0) / 1000).toFixed(1)}s)`);
  }

  const bal = await fetch(`${API}/balance`, { headers: { Authorization: `Bearer ${apiKey()}` } })
    .then((r) => (r.ok ? r.json() : null))
    .catch(() => null);
  console.log(
    `nightbloom: ${generated} generated, ${skipped} kept` +
      (bal && typeof (bal as { usd?: number }).usd === "number" ? `  (pixellab balance: $${(bal as { usd: number }).usd})` : ""),
  );
}

await main();
