// GENERATED by scripts/launcher.ts scan — do not edit by hand; COMMIT
// the regenerated file (test/launcher-sim.test.ts asserts freshness).
// The display-side registry twin of dist/launcher-registry.json: the
// launcher app imports it for titles + cover asset keys; the host's
// appTable (spec op 39) stays the runtime truth for what is embedded.

export interface RegistryApp {
  output: string;
  id: string;
  title: string;
  /** Pak image asset of the 256×128 cover. The literal path below is
   *  what the build's asset collector picks up and bakes. */
  cover: string;
}

export const REGISTRY: readonly RegistryApp[] = [
  { output: "cafe-main", id: "dev.pocket-stack.cafe", title: "PocketJS: Café", cover: "covers/cover-cafe-main.png" },
  { output: "chrome-main", id: "dev.pocket-stack.chrome", title: "PocketJS: Chrome", cover: "covers/cover-chrome-main.png" },
  { output: "cursor-main", id: "dev.pocket-stack.cursor", title: "PocketJS: Cursor", cover: "covers/cover-cursor-main.png" },
  { output: "cards-main", id: "dev.pocket-stack.cards", title: "PocketJS: Feature Cards", cover: "covers/cover-cards-main.png" },
  { output: "gallery-main", id: "dev.pocket-stack.gallery", title: "PocketJS: Gallery (L / R paging)", cover: "covers/cover-gallery-main.png" },
  { output: "library-main", id: "dev.pocket-stack.library", title: "PocketJS: Game Library", cover: "covers/cover-library-main.png" },
  { output: "hero-main", id: "dev.pocket-stack.hero", title: "PocketJS: Hero", cover: "covers/cover-hero-main.png" },
  { output: "hero-vue-vapor-main", id: "dev.pocket-stack.hero.vue.vapor", title: "PocketJS: Hero Vue Vapor", cover: "covers/cover-hero-vue-vapor-main.png" },
  { output: "stats-main", id: "dev.pocket-stack.stats", title: "PocketJS: Mission Control", cover: "covers/cover-stats-main.png" },
  { output: "motions-main", id: "dev.pocket-stack.motions", title: "PocketJS: Motion Lab (yui540 studies on baked keyframe timelines)", cover: "covers/cover-motions-main.png" },
  { output: "notifications-main", id: "dev.pocket-stack.notifications", title: "PocketJS: Notifications", cover: "covers/cover-notifications-main.png" },
  { output: "music-main", id: "dev.pocket-stack.music", title: "PocketJS: Now Playing", cover: "covers/cover-music-main.png" },
  { output: "settings-main", id: "dev.pocket-stack.settings", title: "PocketJS: Settings", cover: "covers/cover-settings-main.png" },
  { output: "im-main", id: "dev.pocket-stack.im", title: "PocketJS: Talk", cover: "covers/cover-im-main.png" },
  { output: "zoomlab-main", id: "dev.pocket-stack.zoomlab", title: "Zoom Lab", cover: "covers/cover-zoomlab-main.png" },
] as const;
