[package]
name = "pocketjs-sf2000"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
libquickjs-sys = { git = "https://github.com/pocket-stack/quickjs-rs.git", rev = "ba5bdd0dc013518768e76cd9e05cd30ed53dd35b" }
pocketjs-core = { path = "../../engine/core" }

[features]
default = ["std"]
std = []

[profile.release]
opt-level = 2
lto = "thin"
codegen-units = 1
panic = "abort"
