// static/compiler/targets/gb.ts — the Game Boy packager: DMG 2bpp art,
// MBC5 bank assignment (each blob whole in one 16 KB bank, accessed through
// the 0x4000 window), bank-0 C tables + banked assembly data, and the
// sdcc/sdasgb/sdldgb/makebin/rgbfix toolchain drive.

import { $ } from "bun";
import { dirname, join } from "node:path";
import { BANK_SIZE, FONT_GLYPHS } from "../../spec/isa.ts";
import { SPRITE_ENTRY_SIZE } from "../../spec/rpg.ts";
import { encodeTileGb, frameToTiles, gbShadeLut, glyphTile, luma, tileFromHexRows } from "../assets.ts";
import { FONT8 } from "../font.gen.ts";
import type { LinkedGame } from "../link.ts";

const RUNTIME = join(import.meta.dir, "..", "..", "runtime");

interface GbBlob {
  bytes: Uint8Array;
}

export function encodeGbArt(linked: LinkedGame): { art: Uint8Array; font: Uint8Array; obj: Uint8Array } {
  const { model } = linked;
  const bgLut = gbShadeLut(model.tileset.palette);

  const art: number[] = [];
  for (let i = 1; i < model.tileNames.length; i++) {
    const tile = model.tileset.tiles[model.tileNames[i]];
    art.push(...encodeTileGb(tileFromHexRows(tile.px), bgLut));
  }

  const font: number[] = [];
  for (let g = 0; g < FONT_GLYPHS; g++) {
    // ink = 3 (black), paper = 0 (white) under the identity BGP ramp
    font.push(...encodeTileGb(glyphTile(FONT8[g], 3, 0), (v) => v));
  }

  // OBJ: pixel 0 transparent; visible colors clamp to shades 1..3 so nothing
  // vanishes (DMG OBJ color 0 is always transparent).
  const obj: number[] = [];
  for (const sp of model.sprites) {
    const shade = gbShadeLut(sp.palette);
    const lut = (idx: number): number => {
      if (idx === 0) return 0;
      const s = shade(idx);
      return s === 0 ? 1 : s;
    };
    const framesPerDir = sp.facings.down.length;
    void framesPerDir;
    for (const facing of ["down", "up", "right"] as const) {
      for (const frame of sp.facings[facing]) {
        const [tl, tr, bl, br] = frameToTiles(frame);
        // 8x16 pairs: left column (top,bottom), then right column
        for (const t of [tl, bl, tr, br]) obj.push(...encodeTileGb(t, lut));
      }
    }
  }
  void luma;
  return { art: Uint8Array.from(art), font: Uint8Array.from(font), obj: Uint8Array.from(obj) };
}

export function emitGbSources(linked: LinkedGame): { genC: string; bankAsm: Map<number, string>; bankCount: number } {
  const { model } = linked;
  const { art, font, obj } = encodeGbArt(linked);

  // Full blob list: linked blobs + art/font/obj.
  const blobs: GbBlob[] = linked.blobs.map((b) => ({ bytes: b.bytes }));
  const artBlob = blobs.length;
  blobs.push({ bytes: art });
  const fontBlob = blobs.length;
  blobs.push({ bytes: font });
  const objBlob = blobs.length;
  blobs.push({ bytes: obj });

  // First-fit bank assignment (banks 1..).
  const bankOf: number[] = [];
  const bankUsed: number[] = []; // per bank index (0 = bank 1)
  for (let i = 0; i < blobs.length; i++) {
    const size = blobs[i].bytes.length;
    if (size > BANK_SIZE) throw new Error(`gb: blob ${i} is ${size} B > one bank`);
    let placed = -1;
    for (let b = 0; b < bankUsed.length; b++) {
      if (bankUsed[b] + size <= BANK_SIZE) {
        placed = b;
        break;
      }
    }
    if (placed < 0) {
      placed = bankUsed.length;
      bankUsed.push(0);
    }
    bankOf[i] = placed + 1;
    bankUsed[placed] += size;
  }

  // Banked data: one .s per bank.
  const bankAsm = new Map<number, string>();
  for (let b = 1; b <= bankUsed.length; b++) {
    const lines: string[] = [
      `; gen_bank${b}.s — GENERATED by targets/gb.ts. DO NOT EDIT.`,
      `\t.module gen_bank${b}`,
      `\t.area _CODE_${b}`,
    ];
    blobs.forEach((blob, i) => {
      if (bankOf[i] !== b) return;
      lines.push(`_ps_b${i}::`);
      const bytes = blob.bytes;
      for (let at = 0; at < bytes.length; at += 16) {
        const row = Array.from(bytes.subarray(at, at + 16)).join(",");
        lines.push(`\t.db ${row}`);
      }
      if (bytes.length === 0) lines.push("\t.db 0");
    });
    bankAsm.set(b, lines.join("\n") + "\n");
  }

  // Bank 0 tables.
  const lines: string[] = [];
  const push = (s: string) => lines.push(s);
  const cArray = (name: string, bytes: ArrayLike<number>, type = "unsigned char"): void => {
    const vals: string[] = [];
    for (let i = 0; i < bytes.length; i++) vals.push(String(bytes[i]));
    push(`const ${type} ${name}[] = { ${vals.join(",")} };`);
  };
  push("/* gen_data.c — GENERATED by targets/gb.ts. DO NOT EDIT. */");
  push('#include "spec_gen.h"');
  push("typedef unsigned char u8; typedef unsigned short u16;");
  cArray("ps_game_header", linked.header, "u8");
  push(`const u16 ps_script_table[] = { ${linked.scriptTable.join(",")} };`);
  {
    const b: number[] = [];
    for (const e of linked.textTable) b.push(e.blob, e.off & 0xff, (e.off >> 8) & 0xff);
    cArray("ps_text_table", b, "u8");
  }
  cArray("ps_map_blob", linked.mapBlobIndex, "u8");
  // Sprite table: tile_base in 8x8 OBJ tiles, 4 per frame, [L pair][R pair].
  {
    const table: number[] = [];
    let tileBase = 0;
    for (const sp of model.sprites) {
      const framesPerDir = sp.facings.down.length;
      table.push(tileBase & 0xff, (tileBase >> 8) & 0xff, framesPerDir, 0);
      tileBase += 3 * framesPerDir * 4;
    }
    if (table.length !== model.sprites.length * SPRITE_ENTRY_SIZE) throw new Error("sprite table drifted");
    cArray("ps_sprite_table", table, "u8");
  }
  blobs.forEach((_, i) => push(`extern const u8 ps_b${i}[];`));
  cArray("ps_blob_bank", bankOf, "u8");
  push(`const u8 *const ps_blob_addr[] = { ${blobs.map((_, i) => `ps_b${i}`).join(",")} };`);
  push(`const u8 ps_art_blob = ${artBlob};`);
  push(`const u8 ps_font_blob = ${fontBlob};`);
  push(`const u8 ps_obj_blob = ${objBlob};`);
  push(`const u8 ps_bg_tile_count = ${model.tileNames.length - 1};`);
  push(`const u16 ps_obj_tile_bytes = ${obj.length};`);

  return { genC: lines.join("\n") + "\n", bankAsm, bankCount: bankUsed.length };
}

export async function buildGb(linked: LinkedGame, outRom: string): Promise<void> {
  const outDir = dirname(outRom);
  const genDir = join(outDir, "gen-gb");
  await $`mkdir -p ${genDir}`.quiet();

  const { genC, bankAsm, bankCount } = emitGbSources(linked);
  await Bun.write(join(genDir, "gen_data.c"), genC);
  for (const [b, asm] of bankAsm) await Bun.write(join(genDir, `gen_bank${b}.s`), asm);

  const gbDir = join(RUNTIME, "gb");
  const coreDir = join(RUNTIME, "core");
  const genInc = join(RUNTIME, "gen");
  const cflags = ["-msm83", "--opt-code-speed", `-DPS_TARGET_GB`, `-I${genInc}`, `-I${coreDir}`, `-I${gbDir}`];

  // compile C
  for (const [src, rel] of [
    [join(coreDir, "vm.c"), "vm.rel"],
    [join(coreDir, "rpg.c"), "rpg.rel"],
    [join(gbDir, "hal_gb.c"), "hal_gb.rel"],
    [join(genDir, "gen_data.c"), "gen_data.rel"],
  ] as const) {
    await $`sdcc ${cflags} -c ${src} -o ${join(genDir, rel)}`.quiet();
  }
  // assemble crt0 + banks
  await $`sdasgb -plosgff -o ${join(genDir, "crt0.rel")} ${join(gbDir, "crt0.s")}`.quiet();
  const bankRels: string[] = [];
  for (const b of bankAsm.keys()) {
    const rel = join(genDir, `gen_bank${b}.rel`);
    await $`sdasgb -plosgff -o ${rel} ${join(genDir, `gen_bank${b}.s`)}`.quiet();
    bankRels.push(rel);
  }

  // link (banked areas at 0x4000 window)
  const ihx = join(genDir, "game.ihx");
  const bankFlags = [...bankAsm.keys()].map((b) => `-Wl-b_CODE_${b}=0x${(b * 0x10000 + 0x4000).toString(16)}`);
  await $`sdcc -msm83 --no-std-crt0 --code-loc 0x0200 --data-loc 0xc0a0 ${bankFlags} ${join(genDir, "crt0.rel")} ${join(genDir, "vm.rel")} ${join(genDir, "rpg.rel")} ${join(genDir, "hal_gb.rel")} ${join(genDir, "gen_data.rel")} ${bankRels} -o ${ihx}`.quiet();

  // ROM image: round banks up to a power of two (MBC5 minimum 2 x 16K)
  let romBanks = 2;
  while (romBanks < bankCount + 1) romBanks *= 2;
  await $`makebin -Z -yo ${romBanks} ${ihx} ${outRom}`.quiet();
  const title = linked.model.title.toUpperCase().replace(/[^A-Z0-9 ]/g, "").slice(0, 11);
  await $`rgbfix -v -m 0x19 -p 0 -t ${title} ${outRom}`.quiet();
}
