// static/compiler/targets/gba.ts — the GBA packager: native 4bpp art, one
// generated gen_data.c (flat ROM keeps every blob addressable), and the
// arm-none-eabi toolchain drive + cartridge header patch.

import { $ } from "bun";
import { dirname, join } from "node:path";
import { FONT_GLYPHS, TARGETS, bgLayout } from "../../spec/isa.ts";
import { SPRITE_ENTRY_SIZE } from "../../spec/rpg.ts";
import {
  encodeTileGba,
  frameToTiles,
  gbaPaletteBank,
  glyphTile,
  tileFromHexRows,
} from "../assets.ts";
import { FONT8 } from "../font.gen.ts";
import type { LinkedGame } from "../link.ts";

const RUNTIME = join(import.meta.dir, "..", "..", "runtime");

// GBA text ink/paper pixel values inside font tiles (palette bank 15).
const INK = 1;
const PAPER = 2;

export interface GbaArtifacts {
  genC: string;
}

export function emitGbaData(linked: LinkedGame): string {
  const { model } = linked;
  const t = TARGETS.gba;
  const L = bgLayout(t);
  const lines: string[] = [];
  const push = (s: string) => lines.push(s);

  const cArray = (name: string, bytes: ArrayLike<number>, type = "unsigned char"): void => {
    const vals: string[] = [];
    for (let i = 0; i < bytes.length; i++) vals.push(String(bytes[i]));
    push(`const ${type} ${name}[] = { ${vals.join(",")} };`);
  };

  push("/* gen_data.c — GENERATED by targets/gba.ts. DO NOT EDIT. */");
  push('#include "spec_gen.h"');
  push("typedef unsigned char u8; typedef unsigned short u16;");

  // Fixed-region tables.
  cArray("ps_game_header", linked.header, "u8");
  {
    const vals = linked.scriptTable.map(String).join(",");
    push(`const u16 ps_script_table[] = { ${vals} };`);
  }
  {
    const b: number[] = [];
    for (const e of linked.textTable) b.push(e.blob, e.off & 0xff, (e.off >> 8) & 0xff);
    cArray("ps_text_table", b, "u8");
  }
  cArray("ps_map_blob", linked.mapBlobIndex, "u8");

  // Blobs.
  linked.blobs.forEach((b, i) => cArray(`ps_blob_${i}`, b.bytes, "u8"));
  push(`const u8 *const ps_blobs[] = { ${linked.blobs.map((_, i) => `ps_blob_${i}`).join(",")} };`);

  // BG art tiles (index 1..N; blank is index 0 and stays zero-filled).
  const art: number[] = [];
  for (let i = 1; i < model.tileNames.length; i++) {
    const tile = model.tileset.tiles[model.tileNames[i]];
    art.push(...encodeTileGba(tileFromHexRows(tile.px)));
  }
  cArray("ps_bg_art", art, "u8");
  push(`const u16 ps_bg_art_tiles = ${model.tileNames.length - 1};`);

  // Font tiles (95 glyphs at the fixed base).
  const font: number[] = [];
  for (let g = 0; g < FONT_GLYPHS; g++) {
    font.push(...encodeTileGba(glyphTile(FONT8[g], INK, PAPER)));
  }
  cArray("ps_font", font, "u8");

  // OBJ tiles + sprite table. GBA 1D mapping: frame block = TL,TR,BL,BR.
  const objBytes: number[] = [];
  const spriteTable: number[] = [];
  let tileBase = 0;
  model.sprites.forEach((sp, si) => {
    const framesPerDir = sp.facings.down.length;
    spriteTable.push(tileBase & 0xff, (tileBase >> 8) & 0xff, framesPerDir, si);
    for (const facing of ["down", "up", "right"] as const) {
      for (const frame of sp.facings[facing]) {
        for (const tile of frameToTiles(frame)) objBytes.push(...encodeTileGba(tile));
        tileBase += 4;
      }
    }
  });
  if (spriteTable.length !== model.sprites.length * SPRITE_ENTRY_SIZE) {
    throw new Error("sprite table drifted");
  }
  cArray("ps_obj_tiles", objBytes, "u8");
  push(`const u16 ps_obj_tile_count = ${tileBase};`);
  cArray("ps_sprite_table", spriteTable, "u8");
  push(`const u8 ps_sprite_count = ${model.sprites.length};`);

  // Palettes: BG bank 0 = tileset, BG bank 15 = textbox; OBJ bank i = sprite i.
  cArray("ps_bg_pal0", Array.from(gbaPaletteBank(model.tileset.palette)), "u16");
  const textPal = new Uint16Array(16);
  textPal[INK] = 0x0000; // black ink
  textPal[PAPER] = 0x7fff; // white paper
  cArray("ps_text_pal", Array.from(textPal), "u16");
  {
    const objPal: number[] = [];
    for (const sp of model.sprites) objPal.push(...gbaPaletteBank(sp.palette));
    cArray("ps_obj_pal", objPal, "u16");
  }
  push(`const u16 ps_bg_font_base = ${L.fontBase};`);

  return lines.join("\n") + "\n";
}

// The GBA BIOS validates these 156 bytes at boot on real hardware; every
// homebrew toolchain (gbafix, devkitARM, tonc) ships the same table.
// prettier-ignore
const NINTENDO_LOGO = [
  0x24,0xFF,0xAE,0x51,0x69,0x9A,0xA2,0x21,0x3D,0x84,0x82,0x0A,0x84,0xE4,0x09,0xAD,
  0x11,0x24,0x8B,0x98,0xC0,0x81,0x7F,0x21,0xA3,0x52,0xBE,0x19,0x93,0x09,0xCE,0x20,
  0x10,0x46,0x4A,0x4A,0xF8,0x27,0x31,0xEC,0x58,0xC7,0xE8,0x33,0x82,0xE3,0xCE,0xBF,
  0x85,0xF4,0xDF,0x94,0xCE,0x4B,0x09,0xC1,0x94,0x56,0x8A,0xC0,0x13,0x72,0xA7,0xFC,
  0x9F,0x84,0x4D,0x73,0xA3,0xCA,0x9A,0x61,0x58,0x97,0xA3,0x27,0xFC,0x03,0x98,0x76,
  0x23,0x1D,0xC7,0x61,0x03,0x04,0xAE,0x56,0xBF,0x38,0x84,0x00,0x40,0xA7,0x0E,0xFD,
  0xFF,0x52,0xFE,0x03,0x6F,0x95,0x30,0xF1,0x97,0xFB,0xC0,0x85,0x60,0xD6,0x80,0x25,
  0xA9,0x63,0xBE,0x03,0x01,0x4E,0x38,0xE2,0xF9,0xA2,0x34,0xFF,0xBB,0x3E,0x03,0x44,
  0x78,0x00,0x90,0xCB,0x88,0x11,0x3A,0x94,0x65,0xC0,0x7C,0x63,0x87,0xF0,0x3C,0xAF,
  0xD6,0x25,0xE4,0x8B,0x38,0x0A,0xAC,0x72,0x21,0xD4,0xF8,0x07,
];

export async function buildGba(linked: LinkedGame, outRom: string): Promise<void> {
  const outDir = dirname(outRom);
  const genDir = join(outDir, "gen-gba");
  await $`mkdir -p ${genDir}`.quiet();
  await Bun.write(join(genDir, "gen_data.c"), emitGbaData(linked));

  const gbaDir = join(RUNTIME, "gba");
  const coreDir = join(RUNTIME, "core");
  const genInc = join(RUNTIME, "gen");
  const elf = join(genDir, "game.elf");

  await $`arm-none-eabi-gcc -mcpu=arm7tdmi -mthumb-interwork -marm -ffreestanding -nostdlib -O2 -fno-strict-aliasing -Wall -Werror=implicit-function-declaration -DPS_TARGET_GBA -I${genInc} -I${coreDir} -I${gbaDir} -T${gbaDir}/gba.ld ${gbaDir}/crt0.s ${coreDir}/vm.c ${coreDir}/rpg.c ${gbaDir}/hal_gba.c ${join(genDir, "gen_data.c")} -lgcc -o ${elf}`;
  await $`arm-none-eabi-objcopy -O binary ${elf} ${outRom}`;

  // Cartridge header: logo + title + checksum (flashcart-friendly).
  const rom = new Uint8Array(await Bun.file(outRom).arrayBuffer());
  rom.set(NINTENDO_LOGO, 0x04);
  const title = linked.model.title.toUpperCase().replace(/[^A-Z0-9 ]/g, "").slice(0, 12);
  for (let i = 0; i < 12; i++) rom[0xa0 + i] = i < title.length ? title.charCodeAt(i) : 0;
  rom.set([0x50, 0x53, 0x54, 0x43], 0xac); // game code "PSTC"
  rom[0xb2] = 0x96; // fixed value
  let sum = 0;
  for (let i = 0xa0; i <= 0xbc; i++) sum = (sum + rom[i]) & 0xff;
  rom[0xbd] = (-(0x19 + sum)) & 0xff;
  await Bun.write(outRom, rom);
}
