// static/compiler/targets/nes.ts — the NES packager: planar 2bpp CHR with
// master-palette reduction, UNROM (mapper 2) bank assignment (data banks at
// the $8000 window, code fixed at $C000), generated ld65 config + iNES
// header, and the cc65/ca65/ld65 toolchain drive.

import { $ } from "bun";
import { dirname, join } from "node:path";
import { BANK_SIZE, FONT_GLYPHS } from "../../spec/isa.ts";
import { encodeTileNes, frameToTiles, glyphTile, nearestNesColor, nesReduce, tileFromHexRows } from "../assets.ts";
import { FONT8 } from "../font.gen.ts";
import type { LinkedGame } from "../link.ts";

const RUNTIME = join(import.meta.dir, "..", "..", "runtime");
const CC65_LIB = "/opt/homebrew/share/cc65/lib/none.lib";

export function encodeNesArt(linked: LinkedGame): {
  art: Uint8Array;
  font: Uint8Array;
  obj: Uint8Array;
  bgPal: number[];
  objPal: number[];
  spriteTable: number[];
} {
  const { model } = linked;
  const backdrop = nearestNesColor(model.tileset.palette[0]);

  const bg = nesReduce(model.tileset.palette, backdrop);
  const art: number[] = [];
  for (let i = 1; i < model.tileNames.length; i++) {
    const tile = model.tileset.tiles[model.tileNames[i]];
    art.push(...encodeTileNes(tileFromHexRows(tile.px), bg.valueOf));
  }

  const font: number[] = [];
  for (let g = 0; g < FONT_GLYPHS; g++) {
    font.push(...encodeTileNes(glyphTile(FONT8[g], 3, 1), (v) => v)); // ink black(3), paper white(1)
  }

  // OBJ: per-sprite subpalette, deduped into the 4 OBJ slots.
  const obj: number[] = [];
  const objSubpals: string[] = [];
  const objPal: number[] = [];
  const spriteTable: number[] = [];
  let tileBase = 0;
  for (const sp of model.sprites) {
    const red = nesReduce(sp.palette, backdrop);
    const key = red.subpal.join(",");
    let slot = objSubpals.indexOf(key);
    if (slot < 0 && objSubpals.length < 4) {
      slot = objSubpals.length;
      objSubpals.push(key);
      objPal.push(...red.subpal);
    } else if (slot < 0) {
      // 4 hardware OBJ subpalettes: extra sprites adopt the nearest one.
      let bestD = Infinity;
      for (let i = 0; i < objSubpals.length; i++) {
        const pal = objSubpals[i].split(",").map(Number);
        let d = 0;
        for (let c = 1; c < 4; c++) d += Math.abs(pal[c] - red.subpal[c]);
        if (d < bestD) {
          bestD = d;
          slot = i;
        }
      }
    }
    const framesPerDir = sp.facings.down.length;
    spriteTable.push(tileBase & 0xff, (tileBase >> 8) & 0xff, framesPerDir, slot);
    for (const facing of ["down", "up", "right"] as const) {
      for (const frame of sp.facings[facing]) {
        const [tl, tr, bl, br] = frameToTiles(frame);
        for (const t of [tl, bl, tr, br]) obj.push(...encodeTileNes(t, red.valueOf));
        tileBase += 4;
      }
    }
  }
  while (objPal.length < 16) objPal.push(0x0f);
  if (tileBase > 256) throw new Error(`nes: ${tileBase} OBJ tiles exceeds pattern table 1 (256)`);

  return {
    art: Uint8Array.from(art),
    font: Uint8Array.from(font),
    obj: Uint8Array.from(obj),
    bgPal: [backdrop, ...bg.subpal.slice(1)],
    objPal,
    spriteTable,
  };
}

export async function buildNes(linked: LinkedGame, outRom: string): Promise<void> {
  const { model } = linked;
  const outDir = dirname(outRom);
  const genDir = join(outDir, "gen-nes");
  await $`mkdir -p ${genDir}`.quiet();

  const { art, font, obj, bgPal, objPal, spriteTable } = encodeNesArt(linked);

  // Blob list + first-fit into switchable banks.
  const blobs = [...linked.blobs.map((b) => b.bytes), art, font, obj];
  const artBlob = linked.blobs.length;
  const fontBlob = artBlob + 1;
  const objBlob = artBlob + 2;
  const bankOf: number[] = [];
  const bankUsed: number[] = [];
  blobs.forEach((bytes, i) => {
    if (bytes.length > BANK_SIZE) throw new Error(`nes: blob ${i} exceeds one bank`);
    let placed = -1;
    for (let b = 0; b < bankUsed.length; b++) {
      if (bankUsed[b] + bytes.length <= BANK_SIZE) {
        placed = b;
        break;
      }
    }
    if (placed < 0) {
      placed = bankUsed.length;
      bankUsed.push(0);
    }
    bankOf[i] = placed;
    bankUsed[placed] += bytes.length;
  });
  const dataBanks = bankUsed.length;
  const prgCount = dataBanks + 1; // + fixed bank

  // gen_data.c (fixed bank tables)
  {
    const lines: string[] = [];
    const push = (s: string) => lines.push(s);
    const cArray = (name: string, bytes: ArrayLike<number>, type = "unsigned char"): void => {
      const vals: string[] = [];
      for (let i = 0; i < bytes.length; i++) vals.push(String(bytes[i]));
      push(`const ${type} ${name}[] = { ${vals.join(",")} };`);
    };
    push("/* gen_data.c — GENERATED by targets/nes.ts. DO NOT EDIT. */");
    push('#include "spec_gen.h"');
    push("typedef unsigned char u8; typedef unsigned short u16;");
    cArray("ps_game_header", linked.header, "u8");
    push(`const u16 ps_script_table[] = { ${linked.scriptTable.join(",")} };`);
    {
      const b: number[] = [];
      for (const e of linked.textTable) b.push(e.blob, e.off & 0xff, (e.off >> 8) & 0xff);
      cArray("ps_text_table", b, "u8");
    }
    cArray("ps_map_blob", linked.mapBlobIndex, "u8");
    cArray("ps_sprite_table", spriteTable, "u8");
    blobs.forEach((_, i) => push(`extern const u8 ps_b${i}[];`));
    cArray("ps_blob_bank", bankOf, "u8");
    push(`const u8 *const ps_blob_addr[] = { ${blobs.map((_, i) => `ps_b${i}`).join(",")} };`);
    push(`const u8 ps_art_blob = ${artBlob};`);
    push(`const u8 ps_font_blob = ${fontBlob};`);
    push(`const u8 ps_obj_blob = ${objBlob};`);
    push(`const u8 ps_bg_tile_count = ${model.tileNames.length - 1};`);
    push(`const u16 ps_obj_tile_bytes = ${obj.length};`);
    cArray("ps_bg_pal", bgPal, "u8");
    cArray("ps_obj_pal", objPal, "u8");
    await Bun.write(join(genDir, "gen_data.c"), lines.join("\n") + "\n");
  }

  // iNES header + per-bank data .s
  {
    const h = [
      `; gen_header.s — GENERATED. iNES: mapper 2 (UNROM), CHR-RAM.`,
      `.segment "HEADER"`,
      `.byte $4e, $45, $53, $1a`,
      `.byte ${prgCount}`,
      `.byte 0`,
      `.byte $20`,
      `.byte 0, 0, 0, 0, 0, 0, 0, 0, 0`,
    ];
    await Bun.write(join(genDir, "gen_header.s"), h.join("\n") + "\n");
  }
  for (let b = 0; b < dataBanks; b++) {
    const lines = [`; gen_bank${b}.s — GENERATED by targets/nes.ts.`, `.segment "BANK${b}"`];
    blobs.forEach((bytes, i) => {
      if (bankOf[i] !== b) return;
      lines.push(`.export _ps_b${i}`);
      lines.push(`_ps_b${i}:`);
      for (let at = 0; at < bytes.length; at += 16) {
        lines.push(`.byte ${Array.from(bytes.subarray(at, at + 16)).join(",")}`);
      }
      if (bytes.length === 0) lines.push(".byte 0");
    });
    await Bun.write(join(genDir, `gen_bank${b}.s`), lines.join("\n") + "\n");
  }

  // ld65 config
  {
    const mem: string[] = [`  HDR: start = $0000, size = $0010, type = ro, file = %O, fill = yes;`];
    const seg: string[] = [`  HEADER: load = HDR, type = ro;`];
    for (let b = 0; b < dataBanks; b++) {
      mem.push(`  PRG${b}: start = $8000, size = $4000, type = ro, file = %O, fill = yes, fillval = $ff;`);
      seg.push(`  BANK${b}: load = PRG${b}, type = ro;`);
    }
    mem.push(`  PRGFIX: start = $c000, size = $4000, type = ro, file = %O, fill = yes, fillval = $ff;`);
    mem.push(`  ZP: start = $0002, size = $00fa, type = rw;`);
    mem.push(`  RAM: start = $0300, size = $0400, type = rw;`);
    seg.push(`  CODE: load = PRGFIX, type = ro;`);
    seg.push(`  STARTUP: load = PRGFIX, type = ro, optional = yes;`);
    seg.push(`  ONCE: load = PRGFIX, type = ro, optional = yes;`);
    seg.push(`  RODATA: load = PRGFIX, type = ro;`);
    seg.push(`  DATA: load = PRGFIX, run = RAM, type = rw, define = yes;`);
    seg.push(`  VECTORS: load = PRGFIX, type = ro, start = $fffa;`);
    seg.push(`  ZEROPAGE: load = ZP, type = zp;`);
    seg.push(`  BSS: load = RAM, type = bss, define = yes;`);
    const cfg = [
      "SYMBOLS {",
      "  __STACKSTART__: type = weak, value = $0700;",
      "  __STACKSIZE__: type = weak, value = $0100;",
      "}",
      `MEMORY {\n${mem.join("\n")}\n}`,
      `SEGMENTS {\n${seg.join("\n")}\n}`,
      "FEATURES {",
      "  CONDES: type = constructor, label = __CONSTRUCTOR_TABLE__, count = __CONSTRUCTOR_COUNT__, segment = RODATA;",
      "  CONDES: type = destructor, label = __DESTRUCTOR_TABLE__, count = __DESTRUCTOR_COUNT__, segment = RODATA;",
      "}",
      "",
    ].join("\n");
    await Bun.write(join(genDir, "nes.cfg"), cfg);
  }

  const nesDir = join(RUNTIME, "nes");
  const coreDir = join(RUNTIME, "core");
  const genInc = join(RUNTIME, "gen");
  const cc = ["-t", "none", "-O", "-DPS_TARGET_NES", `-I${genInc}`, `-I${coreDir}`, `-I${nesDir}`];

  const objs: string[] = [];
  for (const [src, name] of [
    [join(coreDir, "vm.c"), "vm"],
    [join(coreDir, "rpg.c"), "rpg"],
    [join(nesDir, "hal_nes.c"), "hal_nes"],
    [join(genDir, "gen_data.c"), "gen_data"],
  ] as const) {
    const s = join(genDir, `${name}.cc65.s`);
    await $`cc65 ${cc} -o ${s} ${src}`.quiet();
    const o = join(genDir, `${name}.o`);
    await $`ca65 -o ${o} ${s}`.quiet();
    objs.push(o);
  }
  for (const asm of ["gen_header", ...Array.from({ length: dataBanks }, (_, b) => `gen_bank${b}`)]) {
    const o = join(genDir, `${asm}.o`);
    await $`ca65 -o ${o} ${join(genDir, `${asm}.s`)}`.quiet();
    objs.push(o);
  }
  {
    const o = join(genDir, "crt0.o");
    await $`ca65 -o ${o} ${join(nesDir, "crt0.s")}`.quiet();
    objs.push(o);
  }

  await $`ld65 -C ${join(genDir, "nes.cfg")} -o ${outRom} ${objs} ${CC65_LIB}`.quiet();
}
