/* saga_gen.h — GENERATED from saga/spec/saga.ts. Do not edit. */
#ifndef SAGA_GEN_H
#define SAGA_GEN_H
#define C_ASCII_HALF 95
#define C_BRICK_COLS 12
#define C_BRICK_ROWS_MAX 6
#define C_CAP_CARD 2
#define C_CAP_CHIP 0
#define C_CAP_COLS 26
#define C_CAP_DIALOG 3
#define C_CAP_LINES 2
#define C_CAP_SUB 1
#define C_CBB_MAIN 0
#define C_CBB_SHARED 2
#define C_CELLS_H 20
#define C_CELLS_W 30
#define C_CELL_PX 16
#define C_CMP_EQ 0
#define C_CMP_GE 5
#define C_CMP_GT 3
#define C_CMP_LE 4
#define C_CMP_LT 2
#define C_CMP_NE 1
#define C_COUNTER_DIGITS 6
#define C_DBG_MAGIC 1095188819
#define C_DEBUG_ADDR 33554432
#define C_DIR_DOWN 0
#define C_DIR_LEFT 2
#define C_DIR_RIGHT 3
#define C_DIR_UP 1
#define C_EASE_IN 1
#define C_EASE_INOUT 3
#define C_EASE_LINEAR 0
#define C_EASE_OUT 2
#define C_FADE_IN_BLACK 0
#define C_FADE_IN_WHITE 2
#define C_FADE_OUT_BLACK 1
#define C_FADE_OUT_WHITE 3
#define C_FARSKY_BASE 4
#define C_FARSKY_MAX 316
#define C_GLYPH_SLOTS 96
#define C_GLYPH_SLOT_BASE 320
#define C_MAIN_TILE_MAX 1024
#define C_MAX_CHOICES 5
#define C_MAX_CUES 24
#define C_MAX_NPCS 8
#define C_MAX_PROTOS 12
#define C_MAX_SCENES 20
#define C_MAX_SPRITES 16
#define C_MAX_TRIGS 12
#define C_MAX_TWEENS 16
#define C_METER_SEGS 8
#define C_N_FLAGS 16
#define C_N_VARS 24
#define C_OAM_BALL 120
#define C_OAM_BRICK 48
#define C_OAM_COUNTER 16
#define C_OAM_METER 26
#define C_OAM_PADDLE 121
#define C_OAM_PROMPT 24
#define C_OBJ_TILE_MAX 1024
#define C_OBJ_UI_BASE 960
#define C_PALBANK_FAR 2
#define C_PALBANK_MAIN 3
#define C_PALBANK_OBJ_UI 15
#define C_PALBANK_SKY 1
#define C_PALBANK_UI 15
#define C_RASTER_GRADIENT 1
#define C_RASTER_OFF 0
#define C_RASTER_WAVE_FAR 3
#define C_RASTER_WAVE_MAIN 2
#define C_SBB_FAR 26
#define C_SBB_MAIN 24
#define C_SBB_SKY 27
#define C_SBB_UI 28
#define C_SCENE_CINE 0
#define C_SCENE_WORLD 1
#define C_SCREEN_H 160
#define C_SCREEN_W 240
#define C_SFX_BLIP 0
#define C_SFX_CONFIRM 1
#define C_SFX_STAR 3
#define C_SFX_WHOOSH 2
#define C_SPR_BEHIND 4
#define C_SPR_GHOST 8
#define C_SPR_HFLIP 1
#define C_SPR_SCREEN 2
#define C_STEP_FRAMES 8
#define C_TOK_END 0
#define C_TOK_NL 10
#define C_TRIG_AUTO 2
#define C_TRIG_EXAMINE 1
#define C_TRIG_EXIT 0
#define C_TW_SPRITE_BASE 64
#define C_T_BLANK 0
#define C_T_BOX 1
#define C_T_BOX_ACCENT 2
#define C_T_CURSOR 3
#define C_UI_ACCENT 3
#define C_UI_BOX 2
#define C_UI_INK 1
#define C_UI_SHADOW 4
#define C_WALK_ROW_DOWN 0
#define C_WALK_ROW_SIDE 2
#define C_WALK_ROW_UP 1
#define C_WORLD_COLS_MAX 25
#define C_WORLD_ROWS_MAX 25
#define OP_END 0
#define OP_WAIT 1
#define OP_WAITA 2
#define OP_WAIT_TWEENS 3
#define OP_FADE 4
#define OP_CAPTION 5
#define OP_CAPTION_CLR 6
#define OP_DIALOG 7
#define OP_CHOICE 8
#define OP_TWEEN 9
#define OP_SPRITE_SHOW 10
#define OP_SPRITE_HIDE 11
#define OP_SPRITE_ANIM 12
#define OP_SPRITE_MOVE 13
#define OP_CONTROL 14
#define OP_MASH 15
#define OP_GOTO_SCENE 16
#define OP_RASTER 17
#define OP_SFX 18
#define OP_COUNTER 19
#define OP_AFFINE 20
#define OP_LETTERBOX 21
#define OP_WORLD 22
#define OP_BREAKOUT 23
#define OP_METER 24
#define OP_WARP 25
#define OP_FACE 26
#define OP_WALK 27
#define OP_PUSH 32
#define OP_SET_VAR 33
#define OP_GET_VAR 34
#define OP_ADD_VAR 35
#define OP_SET_FLAG 36
#define OP_CLR_FLAG 37
#define OP_GET_FLAG 38
#define OP_CMP 39
#define OP_JZ 40
#define OP_JMP 41
#define OP_RND 42
#define OP_POP 43
#define TW_CAM_X 0
#define TW_CAM_Y 1
#define TW_BLDY 2
#define TW_EVA 3
#define TW_EVB 4
#define TW_MOSAIC 5
#define TW_WAVE_AMP 6
#define TW_LETTERBOX 7
#define TW_SHAKE 8
#define TW_FAR_VX 9
#define TW_SKY_VX 10
#define TW_OBJ_SCALE 11
#define TW_OBJ_ANGLE 12
#define WAITING_RUN 0
#define WAITING_A 1
#define WAITING_DIALOG 2
#define WAITING_CHOICE 3
#define WAITING_CONTROL 4
#define WAITING_MASH 5
#define WAITING_FILM_DONE 6
#define WAITING_BUSY 7
#define WAITING_WORLD 8
#define WAITING_MINIGAME 9
#define DBG_MAGIC_VAL 1095188819
#define DBGO_MAGIC 0
#define DBGO_BOOTED 4
#define DBGO_SCENE 5
#define DBGO_WAITING 6
#define DBGO_LAST_CHOICE 7
#define DBGO_FRAME 8
#define DBGO_CUE_IP 10
#define DBGO_CAM_X 12
#define DBGO_CUR_TEXT 14
#define DBGO_TWEEN_MASK 16
#define DBGO_CAPTION_BUSY 18
#define DBGO_FILM_DONE 19
#define DBGO_VARS 20
#define DBGO_SPR0_X 68
#define DBGO_SPR0_Y 70
#define DBGO_PLAYER_CX 72
#define DBGO_PLAYER_CY 73
#define DBGO_PLAYER_DIR 74
#define DBGO_BRICKS 75
#define DBGO_KIND 76
#endif
