// AUTO-GENERATED by apps/zoomlab/gen-assets.ts (bun apps/zoomlab/gen-assets.ts).
// Deep-zoom tile manifest for the synthetic zoomlab pages. The viewer
// positions and streams tiles from THIS data alone — solid tiles never touch
// the tileset blobs (they draw as plain background/solids[] colored rects),
// only '#' tiles go through the loadTileTexture op. Plain .ts (not
// *.generated.ts) so the build's pass-1 scanner walks it.

export const TILE = 256;

export interface ZoomLevel {
  /** doc-px -> level-px scale; level pixel = docCoord * scale */
  scale: number;
  cols: number;
  rows: number;
  /** pak key of this level's TILESET entry (tile index = row * cols + col) */
  key: string;
  /**
   * Row-major tile map, one string per row, one char per tile:
   *   '.'                 solid tile of the page background color (bg)
   *   '#'                 textured tile — stream it via loadTileTexture
   *   'a'..'z' 'A'..'Z'   solid tile of color solids[i], i = a:0 .. z:25, A:26 .. Z:51
   */
  grid: string[];
  /** ABGR colors for the lettered solid tiles above. */
  solids: number[];
}

export interface ZoomPage {
  name: string;
  /** content size in doc px */
  w: number;
  h: number;
  /** page background, ABGR u32 */
  bg: number;
  levels: ZoomLevel[];
}

export const PAGES: ZoomPage[] = [
  {
    name: "Poster",
    w: 4096, h: 2304, bg: 0xffe8e8e8,
    levels: [
      {
        scale: 0.5, cols: 8, rows: 5, key: "ui:tile.zoom.0.0",
        solids: [0xff514137],
        grid: [
          "...##.##",
          "#####.aa",
          "#######.",
          ".#######",
          "...#####",
        ],
      },
      {
        scale: 0.25, cols: 4, rows: 3, key: "ui:tile.zoom.0.1",
        solids: [],
        grid: [
          "####",
          "####",
          ".###",
        ],
      },
      {
        scale: 0.125, cols: 2, rows: 2, key: "ui:tile.zoom.0.2",
        solids: [],
        grid: [
          "##",
          "##",
        ],
      },
      {
        scale: 0.0625, cols: 1, rows: 1, key: "ui:tile.zoom.0.3",
        solids: [],
        grid: [
          "#",
        ],
      },
    ],
  },
  {
    name: "Counter Sheet",
    w: 2048, h: 1536, bg: 0xff3b291e,
    levels: [
      {
        scale: 0.5, cols: 4, rows: 3, key: "ui:tile.zoom.1.0",
        solids: [0xffa6b814],
        grid: [
          "###a",
          "###.",
          "###.",
        ],
      },
      {
        scale: 0.25, cols: 2, rows: 2, key: "ui:tile.zoom.1.1",
        solids: [],
        grid: [
          "##",
          "##",
        ],
      },
      {
        scale: 0.125, cols: 1, rows: 1, key: "ui:tile.zoom.1.2",
        solids: [],
        grid: [
          "#",
        ],
      },
    ],
  },
];
