import { createHash } from "node:crypto";
import {
  cpSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  BLACKBERRY_ANDROID_DEV_TARGET_ID,
  resolveBlackBerryClassicBuildPlan,
} from "./blackberry-classic-profile.ts";
import {
  buildGuestBundle,
  ensureQuickJsCheckout,
  type GuestBundle,
  type GuestBundleRequest,
  mustRunCommand,
  packageIdentity,
  type PackageIdentity,
  printCheck,
  quickJsCheckout,
  quickJsCheckoutStatus,
  readGuestBundle,
  renderTemplate,
  runCommand,
  sha256File,
  xmlEscape,
} from "./native-host-build.ts";

const LABEL = "PocketJS BlackBerry Android";
const repository = fileURLToPath(new URL("..", import.meta.url));
const command = Bun.argv[2] ?? "doctor";
const toolchain = JSON.parse(
  readFileSync(
    join(repository, "tools/cli/blackberry-android-toolchain.json"),
    "utf8",
  ),
) as {
  readonly toolchainVersion: string;
  readonly cachePath: string;
  readonly javaImage: string;
  readonly quickjs: {
    readonly version: string;
    readonly repository: string;
    readonly revision: string;
  };
  readonly rust: {
    readonly toolchain: string;
    readonly target: string;
  };
  readonly android: {
    readonly apiLevel: number;
    readonly platformVersion: string;
    readonly buildToolsVersion: string;
    readonly ndkVersion: string;
    readonly abi: string;
    readonly clangTarget: string;
    readonly repository: string;
    readonly packages: readonly SdkPackage[];
  };
  readonly app: {
    readonly manifest: string;
    readonly output: string;
  };
};

interface SdkArchive {
  readonly asset: string;
  /** The checksum Google publishes in repository2-3.xml (what sdkmanager checks). */
  readonly sha1: string;
}

/** One SDK component: the archive per host OS and where it unpacks. */
interface SdkPackage {
  readonly id: string;
  readonly path: string;
  readonly archives: Readonly<Partial<Record<"any" | "linux" | "darwin", SdkArchive>>>;
}

/**
 * The NDK ships one LLVM prebuilt per host operating system. Linux x86-64 is
 * the verified host; the macOS prebuilt is x86-64 as well and runs under
 * Rosetta on Apple silicon.
 */
function ndkHostTag(): string {
  switch (process.platform) {
    case "linux":
      return "linux-x86_64";
    case "darwin":
      return "darwin-x86_64";
    default:
      throw new Error(`${LABEL}: no NDK r23c prebuilt for host ${process.platform}`);
  }
}

const cache = join(homedir(), ".cache/pocket-stack", toolchain.cachePath);
const sdk = process.env.POCKETJS_ANDROID_SDK_ROOT ?? join(cache, "sdk");
const buildTools = join(sdk, "build-tools", toolchain.android.buildToolsVersion);
const ndk = join(sdk, "ndk", toolchain.android.ndkVersion);
const llvm = join(ndk, "toolchains/llvm/prebuilt", ndkHostTag(), "bin");
const clang = join(llvm, `${toolchain.android.clangTarget}-clang`);
const readelf = join(llvm, "llvm-readelf");
const androidJar = join(
  sdk,
  "platforms",
  `android-${toolchain.android.apiLevel}`,
  "android.jar",
);
const appHost = join(repository, "hosts/blackberry-classic-android/app");
const build = join(repository, ".pocket-build/blackberry-android");
const staging = join(build, "staging");
const appOutput = join(repository, toolchain.app.output);
const signing = join(cache, "signing");
/* One local key signs every APK; Android upgrades an installed package only
 * when the new APK carries the same signing identity, so a key generated by
 * an earlier version of this tool keeps being used under its old name. */
const keystoreName = existsSync(join(signing, "blackberry-android-probe.jks"))
  ? "blackberry-android-probe.jks"
  : "blackberry-classic.jks";
const keystore = join(signing, keystoreName);
const quickJs = quickJsCheckout(join(cache, "sources/quickjs-rs"));
const guest: GuestBundleRequest = {
  label: LABEL,
  repository,
  target: BLACKBERRY_ANDROID_DEV_TARGET_ID,
  resolvePlan: (manifest) =>
    resolveBlackBerryClassicBuildPlan(manifest, BLACKBERRY_ANDROID_DEV_TARGET_ID),
  manifestPath: join(repository, toolchain.app.manifest),
  planPath: join(repository, ".pocket/blackberry-android/app.plan.json"),
  outputDirectory: join(repository, "dist/blackberry-android/guest"),
};

function run(program: string, args: readonly string[]) {
  return runCommand(program, args, repository);
}

function mustRun(
  program: string,
  args: readonly string[],
  cwd = repository,
  env: NodeJS.ProcessEnv = process.env,
): string {
  return mustRunCommand(LABEL, program, args, cwd, env);
}

function dockerJava(args: readonly string[]): string {
  const uid = process.getuid?.() ?? 1000;
  const gid = process.getgid?.() ?? 1000;
  return mustRun("docker", [
    "run",
    "--rm",
    "--user",
    `${uid}:${gid}`,
    "-e",
    "HOME=/tmp",
    "-v",
    `${repository}:/repo:ro`,
    "-v",
    `${sdk}:/android-sdk:ro`,
    "-v",
    `${build}:/build`,
    "-v",
    `${signing}:/signing`,
    toolchain.javaImage,
    ...args,
  ]);
}

function javaImagePresent(): boolean {
  return run("docker", ["image", "inspect", toolchain.javaImage]).exitCode === 0;
}

/**
 * Checks the target's std directory in the pinned toolchain's sysroot. `rustup
 * target list --toolchain X` would install a missing X on the spot, which a
 * doctor must not do.
 */
function rustTargetInstalled(): boolean {
  const sysroot = run("rustup", ["run", toolchain.rust.toolchain, "rustc", "--print", "sysroot"]);
  if (sysroot.exitCode !== 0) return false;
  return existsSync(
    join(sysroot.stdout.trim(), "lib/rustlib", toolchain.rust.target, "lib"),
  );
}

function checkPath(label: string, path: string): boolean {
  return printCheck(label, existsSync(path), path);
}

function doctor(): void {
  const rust = run("rustup", ["run", toolchain.rust.toolchain, "rustc", "--version"]);
  const quickjs = quickJsCheckoutStatus(quickJs.root, toolchain.quickjs);
  const sdkChecks = [
    checkPath(`Android SDK Platform ${toolchain.android.apiLevel}`, androidJar),
    checkPath(`NDK ${toolchain.android.ndkVersion} clang`, clang),
    checkPath("NDK llvm-readelf", readelf),
    checkPath("aapt2", join(buildTools, "aapt2")),
    checkPath("aapt", join(buildTools, "aapt")),
    checkPath("d8", join(buildTools, "d8")),
    checkPath("zipalign", join(buildTools, "zipalign")),
    checkPath("apksigner", join(buildTools, "apksigner")),
  ];
  const checks = [
    ...sdkChecks,
    printCheck("Java image", javaImagePresent(), toolchain.javaImage),
    printCheck(
      "Rust nightly",
      rust.exitCode === 0,
      rust.stdout.trim() || toolchain.rust.toolchain,
    ),
    printCheck(
      "Rust Android target",
      rustTargetInstalled(),
      `${toolchain.rust.target} on ${toolchain.rust.toolchain}`,
    ),
    printCheck("pinned QuickJS", quickjs.ok, quickjs.detail),
  ];
  if (sdkChecks.some((ok) => !ok)) {
    console.log(
      `Run \`bun blackberry-android setup\` to unpack the pinned SDK archives into ${sdk}, ` +
        `or point POCKETJS_ANDROID_SDK_ROOT at an SDK that already holds ` +
        `${toolchain.android.packages.map((pkg) => pkg.id).join(", ")}.`,
    );
  }
  if (checks.some((ok) => !ok)) process.exitCode = 1;
  else console.log(`[ok] toolchain: ${toolchain.toolchainVersion}`);
}

function requireToolchain(): void {
  doctor();
  if (process.exitCode) {
    throw new Error(`${LABEL}: toolchain is incomplete; see the doctor report above`);
  }
}

async function sha1File(path: string): Promise<string> {
  const hash = createHash("sha1");
  for await (const chunk of Bun.file(path).stream()) hash.update(chunk);
  return hash.digest("hex");
}

/**
 * Unpacks the pinned SDK archives (the same files `sdkmanager` installs) into
 * the SDK root, one host-OS archive per component; nothing is downloaded for
 * a component whose directory already exists.
 */
async function installSdkPackages(): Promise<void> {
  const downloads = join(cache, "downloads");
  for (const pkg of toolchain.android.packages) {
    const target = join(sdk, pkg.path);
    if (existsSync(target)) continue;
    const archive =
      pkg.archives[process.platform as "linux" | "darwin"] ?? pkg.archives.any;
    if (!archive) {
      throw new Error(`${LABEL}: ${pkg.id} has no archive for host ${process.platform}`);
    }
    mkdirSync(downloads, { recursive: true });
    const download = join(downloads, archive.asset);
    if (!existsSync(download) || (await sha1File(download)) !== archive.sha1) {
      const url = `${toolchain.android.repository}${archive.asset}`;
      console.log(`${LABEL}: downloading ${url}`);
      const response = await fetch(url);
      if (!response.ok || response.body === null) {
        throw new Error(`${LABEL}: ${url} failed (${response.status})`);
      }
      const partial = `${download}.part`;
      const sink = Bun.file(partial).writer();
      let received = 0;
      for await (const chunk of response.body) {
        sink.write(chunk);
        received += chunk.byteLength;
      }
      await sink.end();
      renameSync(partial, download);
      console.log(`${LABEL}: ${archive.asset} ${received} bytes`);
      const digest = await sha1File(download);
      if (digest !== archive.sha1) {
        rmSync(download, { force: true });
        throw new Error(
          `${LABEL}: ${archive.asset} sha1 ${digest} does not match the pinned ${archive.sha1}`,
        );
      }
    }
    const scratch = mkdtempSync(join(downloads, "unpack-"));
    try {
      mustRun("unzip", ["-q", download, "-d", scratch]);
      const entries = readdirSync(scratch).filter((name) => !name.startsWith("."));
      if (entries.length !== 1) {
        throw new Error(
          `${LABEL}: ${archive.asset} unpacked to ${entries.length} entries, expected one directory`,
        );
      }
      mkdirSync(dirname(target), { recursive: true });
      renameSync(join(scratch, entries[0]), target);
      console.log(`${LABEL}: ${pkg.id} -> ${target}`);
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
  }
}

async function setup(): Promise<void> {
  await installSdkPackages();
  if (!javaImagePresent()) mustRun("docker", ["pull", toolchain.javaImage]);
  ensureQuickJsCheckout(LABEL, quickJs.root, toolchain.quickjs);
  if (!rustTargetInstalled()) {
    mustRun("rustup", [
      "target",
      "add",
      toolchain.rust.target,
      "--toolchain",
      toolchain.rust.toolchain,
    ]);
  }
  doctor();
}

function ensureKeystore(): void {
  mkdirSync(signing, { recursive: true });
  if (existsSync(keystore)) return;
  dockerJava([
    "keytool",
    "-genkeypair",
    "-noprompt",
    "-keystore",
    `/signing/${keystoreName}`,
    "-storepass",
    "android",
    "-alias",
    "androiddebugkey",
    "-keypass",
    "android",
    "-dname",
    "CN=PocketJS BlackBerry Classic,O=PocketJS,C=HK",
    "-keyalg",
    "RSA",
    "-keysize",
    "2048",
    "-validity",
    "10000",
  ]);
}

/** javac → jar → d8 for PocketActivity, into staging/classes.dex. */
function compileActivity(): void {
  mkdirSync(join(build, "classes"), { recursive: true });
  mkdirSync(join(build, "dex"), { recursive: true });
  dockerJava([
    "javac",
    "-encoding",
    "UTF-8",
    "-source",
    "7",
    "-target",
    "7",
    "-bootclasspath",
    `/android-sdk/platforms/android-${toolchain.android.apiLevel}/android.jar`,
    "-d",
    "/build/classes",
    "/repo/hosts/blackberry-classic-android/app/src/dev/pocketstack/blackberry/PocketActivity.java",
  ]);
  dockerJava(["jar", "cf", "/build/classes.jar", "-C", "/build/classes", "."]);
  dockerJava([
    `/android-sdk/build-tools/${toolchain.android.buildToolsVersion}/d8`,
    "--min-api",
    String(toolchain.android.apiLevel),
    "--output",
    "/build/dex",
    "/build/classes.jar",
  ]);
  copyFileSync(join(build, "dex/classes.dex"), join(staging, "classes.dex"));
}

/**
 * aapt2 → zipalign → apksigner over staging/ (classes.dex + lib/) plus the
 * guest assets. Android 4.3 verifies only the JAR (v1) signature scheme, so
 * every newer scheme is disabled explicitly.
 */
function packageApk(identity: PackageIdentity, resources: string, assets: string): {
  readonly signature: string;
  readonly badging: string;
} {
  const compiled = join(build, "app-res.zip");
  mustRun(join(buildTools, "aapt2"), ["compile", "--dir", resources, "-o", compiled]);
  const manifest = join(build, "AndroidManifest.xml");
  writeFileSync(
    manifest,
    renderTemplate(readFileSync(join(appHost, "AndroidManifest.xml"), "utf8"), {
      PACKAGE: identity.packageId,
      VERSION_CODE: identity.versionCode,
      VERSION_NAME: identity.version,
    }),
  );
  const unsigned = join(build, "app-unsigned.apk");
  mustRun(join(buildTools, "aapt2"), [
    "link",
    "-o",
    unsigned,
    "--manifest",
    manifest,
    "-I",
    androidJar,
    "-A",
    assets,
    "--min-sdk-version",
    String(toolchain.android.apiLevel),
    "--target-sdk-version",
    String(toolchain.android.apiLevel),
    compiled,
  ]);
  mustRun("zip", ["-q", "-r", unsigned, "classes.dex", "lib"], staging);
  const aligned = join(build, "app-aligned.apk");
  mustRun(join(buildTools, "zipalign"), ["-f", "-p", "4", unsigned, aligned]);
  ensureKeystore();
  dockerJava([
    `/android-sdk/build-tools/${toolchain.android.buildToolsVersion}/apksigner`,
    "sign",
    "--ks",
    `/signing/${keystoreName}`,
    "--ks-key-alias",
    "androiddebugkey",
    "--ks-pass",
    "pass:android",
    "--key-pass",
    "pass:android",
    "--min-sdk-version",
    String(toolchain.android.apiLevel),
    "--v1-signing-enabled",
    "true",
    "--v2-signing-enabled",
    "false",
    "--v3-signing-enabled",
    "false",
    "--v4-signing-enabled",
    "false",
    "--out",
    "/build/app-signed.apk",
    "/build/app-aligned.apk",
  ]);
  mkdirSync(dirname(appOutput), { recursive: true });
  copyFileSync(join(build, "app-signed.apk"), appOutput);
  const signature = dockerJava([
    `/android-sdk/build-tools/${toolchain.android.buildToolsVersion}/apksigner`,
    "verify",
    "--verbose",
    "--print-certs",
    "--min-sdk-version",
    String(toolchain.android.apiLevel),
    "/build/app-signed.apk",
  ]);
  const badging = mustRun(join(buildTools, "aapt"), ["dump", "badging", appOutput]);
  return { signature, badging };
}

function resetBuild(): void {
  rmSync(build, { recursive: true, force: true });
  mkdirSync(join(staging, "lib", toolchain.android.abi), { recursive: true });
}

function buildRustCore(): string {
  const rustTarget = join(build, "rust");
  mustRun(
    "rustup",
    [
      "run",
      toolchain.rust.toolchain,
      "cargo",
      "build",
      "--release",
      "--locked",
      "--target",
      toolchain.rust.target,
      "--features",
      "bare-platform",
      "--target-dir",
      rustTarget,
    ],
    join(repository, "engine/ui-cabi"),
    {
      ...process.env,
      CARGO_PROFILE_RELEASE_LTO: "false",
      CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER: clang,
    },
  );
  const library = join(rustTarget, toolchain.rust.target, "release/libpocketjs_symbian_core.a");
  if (!existsSync(library)) {
    throw new Error(`${LABEL}: Rust core archive is absent: ${library}`);
  }
  return library;
}

function buildQuickJs(): string {
  const objects = join(build, "objects/quickjs");
  mkdirSync(objects, { recursive: true });
  const flags = [
    "-std=gnu11",
    "-O2",
    "-fPIC",
    "-funsigned-char",
    "-fno-strict-aliasing",
    "-ffunction-sections",
    "-fdata-sections",
    "-D_GNU_SOURCE",
    `-DCONFIG_VERSION="${toolchain.quickjs.version}"`,
    `-I${quickJs.source}`,
  ];
  const objectPaths: string[] = [];
  for (const source of ["cutils.c", "dtoa.c", "libregexp.c", "libunicode.c", "quickjs.c"]) {
    const object = join(objects, source.replace(/\.c$/, ".o"));
    mustRun(clang, [...flags, "-c", join(quickJs.source, source), "-o", object]);
    objectPaths.push(object);
  }
  const staticFunctions = join(objects, "static-functions.o");
  mustRun(clang, [...flags, "-c", quickJs.staticFunctions, "-o", staticFunctions]);
  objectPaths.push(staticFunctions);
  const library = join(build, "libquickjs.a");
  mustRun(join(llvm, "llvm-ar"), ["rcs", library, ...objectPaths]);
  return library;
}

function buildNativeLibrary(bundle: GuestBundle, quickJsLibrary: string, coreLibrary: string): string {
  const objects = join(build, "objects");
  const cFlags = [
    "-std=gnu11",
    "-Os",
    "-fPIC",
    "-fno-strict-aliasing",
    "-ffunction-sections",
    "-fdata-sections",
    "-fvisibility=hidden",
    "-Wall",
    "-Wextra",
    "-Werror",
    "-Wno-unused-parameter",
  ];
  const portableRuntime = join(objects, "pocket_runtime.o");
  mustRun(clang, [
    ...cFlags,
    `-DPOCKETJS_TARGET_ID="${bundle.inputs.target}"`,
    `-DPOCKETJS_HOST_ABI=${bundle.inputs.hostAbi}`,
    `-DPOCKET_RASTER_DENSITY=${bundle.inputs.viewport.rasterDensity}`,
    `-I${join(repository, "engine/quickjs-c")}`,
    `-I${join(repository, "engine/ui-cabi/include")}`,
    `-I${join(repository, "contracts/generated")}`,
    `-I${quickJs.source}`,
    "-c",
    join(repository, "engine/quickjs-c/pocket_runtime.c"),
    "-o",
    portableRuntime,
  ]);
  const androidRuntime = join(objects, "android_runtime.o");
  mustRun(clang, [
    ...cFlags,
    `-DPOCKET_LOGICAL_WIDTH=${bundle.inputs.viewport.logical[0]}`,
    `-DPOCKET_LOGICAL_HEIGHT=${bundle.inputs.viewport.logical[1]}`,
    `-I${join(repository, "engine/quickjs-c")}`,
    `-I${join(repository, "hosts/blackberry-classic")}`,
    `-I${join(repository, "contracts/generated")}`,
    "-c",
    join(appHost, "jni/runtime.c"),
    "-o",
    androidRuntime,
  ]);
  const sharedSources = [
    {
      name: "pocket_input",
      source: join(repository, "hosts/blackberry-classic/pocket_input.c"),
      includes: [
        `-I${join(repository, "hosts/blackberry-classic")}`,
        `-I${join(repository, "contracts/generated")}`,
      ],
    },
    {
      name: "rust_eh_personality",
      source: join(repository, "engine/quickjs-c/rust_eh_personality.c"),
      includes: [],
    },
  ] satisfies Array<{ name: string; source: string; includes: string[] }>;
  const sharedObjects = sharedSources.map(({ name, source, includes }) => {
    const object = join(objects, `${name}.o`);
    mustRun(clang, [
      ...cFlags,
      ...includes,
      "-c",
      source,
      "-o",
      object,
    ]);
    return object;
  });
  const nativeLibrary = join(staging, "lib", toolchain.android.abi, "libpocketjs.so");
  /* No -landroid: the library needs nothing beyond GLESv2/log/dl/m/c, and
   * --no-undefined turns any missing native symbol into a link failure. */
  mustRun(clang, [
    "-shared",
    "-Wl,--build-id=none",
    "-Wl,--gc-sections",
    "-Wl,--exclude-libs,ALL",
    "-Wl,--no-undefined",
    androidRuntime,
    portableRuntime,
    ...sharedObjects,
    quickJsLibrary,
    coreLibrary,
    "-o",
    nativeLibrary,
    "-lGLESv2",
    "-llog",
    "-ldl",
    "-lm",
  ]);
  return nativeLibrary;
}

function buildApp(): void {
  requireToolchain();
  const bundle = readGuestBundle(guest);
  resetBuild();
  const coreLibrary = buildRustCore();
  const quickJsLibrary = buildQuickJs();
  const nativeLibrary = buildNativeLibrary(bundle, quickJsLibrary, coreLibrary);
  compileActivity();

  const assets = join(build, "assets");
  mkdirSync(assets, { recursive: true });
  copyFileSync(bundle.javaScript, join(assets, "app.js"));
  copyFileSync(bundle.pack, join(assets, "app.pak"));
  const identity = packageIdentity(bundle.inputs.app);
  const resources = join(build, "resources");
  cpSync(join(appHost, "res"), resources, { recursive: true });
  writeFileSync(
    join(resources, "values/strings.xml"),
    renderTemplate(readFileSync(join(appHost, "res/values/strings.xml"), "utf8"), {
      /* Android string resources also need apostrophes escaped. */
      TITLE: xmlEscape(identity.title).replace(/'/g, "\\'"),
    }),
  );
  mkdirSync(join(resources, "drawable"), { recursive: true });
  copyFileSync(
    join(repository, "assets/images/logo.png"),
    join(resources, "drawable/icon.png"),
  );
  const { signature, badging } = packageApk(identity, resources, assets);
  for (const marker of [
    `package: name='${identity.packageId}' versionCode='${identity.versionCode}' versionName='${identity.version}'`,
    `sdkVersion:'${toolchain.android.apiLevel}'`,
  ]) {
    if (!badging.includes(marker)) {
      throw new Error(`${LABEL}: APK badging is missing ${marker}`);
    }
  }
  const receipt = {
    schema: 1,
    toolchain: toolchain.toolchainVersion,
    planHash: bundle.plan.planHash,
    package: identity,
    target: bundle.inputs.target,
    hostAbi: bundle.inputs.hostAbi,
    viewport: bundle.inputs.viewport,
    apk: {
      path: toolchain.app.output,
      bytes: readFileSync(appOutput).byteLength,
      sha256: sha256File(appOutput),
    },
    guest: {
      javaScript: sha256File(bundle.javaScript),
      pack: sha256File(bundle.pack),
    },
    nativeLibrary: {
      bytes: readFileSync(nativeLibrary).byteLength,
      sha256: sha256File(nativeLibrary),
      elf: mustRun(readelf, ["-h", "-A", "-d", nativeLibrary]),
    },
    quickjs: {
      version: toolchain.quickjs.version,
      revision: toolchain.quickjs.revision,
    },
    rust: toolchain.rust,
    signature,
    badging,
  };
  const receiptPath = join(dirname(appOutput), "pocketjs-blackberry-classic.receipt.json");
  writeFileSync(receiptPath, `${JSON.stringify(receipt, null, 2)}\n`);
  console.log(`${LABEL}: Hero APK -> ${appOutput}`);
  console.log(`SHA-256: ${receipt.apk.sha256}`);
  console.log(`Receipt: ${receiptPath}`);
}

switch (command) {
  case "doctor":
    doctor();
    break;
  case "setup":
    await setup();
    break;
  case "build-demo":
    buildGuestBundle(guest);
    break;
  case "build-app":
    buildApp();
    break;
  case "build":
    buildGuestBundle(guest);
    buildApp();
    break;
  default:
    throw new Error(
      "usage: bun tools/blackberry-android.ts <doctor|setup|build-demo|build-app|build>",
    );
}
