#!/usr/bin/env bun
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { IDF_NATIVE_CALLBACKS, IDF_NATIVE_STRUCTS } from "../contracts/spec/idf-native.ts";
import * as pocket from "../contracts/spec/pocket-package.ts";
import { PAK_MAGIC, PAK_VERSION, PAK_HEADER_SIZE, PAK_ENTRY_SIZE } from "../contracts/spec/spec.ts";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const primitive: Record<string, string> = { usize: "size_t", u64: "uint64_t", u32: "uint32_t", u16: "uint16_t", u8: "uint8_t", i32: "int32_t", f32: "float", f64: "double", bool: "bool", c_void: "void", NativeUiCore: "pocketjs_ui_core_t", NativeRenderer: "pocketjs_rgb565_renderer_t", NativeRenderTarget: "pocketjs_rgb565_target_t" };
function cType(type: string): string {
  if (primitive[type]) return primitive[type];
  if (type.startsWith("*const ")) return `const ${cType(type.slice(7))} *`;
  if (type.startsWith("*mut ")) return `${cType(type.slice(5))} *`;
  const callback = IDF_NATIVE_CALLBACKS.find(c => `Option<${c.name}>` === type);
  if (callback) return callback.cName;
  const record = IDF_NATIVE_STRUCTS.find(s => s.name === type);
  if (record) return record.cName;
  throw new Error(`unknown ABI type ${type}`);
}
function array(type: string) { return type.match(/^\[(\w+); (\d+|MAX_DAMAGE_REGIONS)\]$/); }
function layout(type: string, pointer: number): { size: number; align: number; offsets?: number[] } {
  if (type.startsWith("*") || type.startsWith("Option<") || type === "usize") return { size: pointer, align: pointer };
  const scalar = { u64: 8, u32: 4, u16: 2, u8: 1, bool: 1 }[type];
  if (scalar) return { size: scalar, align: scalar };
  const a = array(type);
  if (a) { const element = layout(a[1], pointer); return { ...element, size: element.size * (a[2] === "MAX_DAMAGE_REGIONS" ? 8 : Number(a[2])) }; }
  const record = IDF_NATIVE_STRUCTS.find(s => s.name === type);
  if (!record) throw new Error(`unknown layout ${type}`);
  let size = 0, align = 1;
  const offsets: number[] = [];
  for (const field of record.fields) {
    const child = layout(field.type, pointer);
    size = Math.ceil(size / child.align) * child.align;
    offsets.push(size);
    size += child.size;
    align = Math.max(align, child.align);
  }
  return { size: Math.ceil(size / align) * align, align, offsets };
}
const banner = "Generated by tools/esp-idf-contracts.ts from contracts/spec/idf-native.ts. Do not edit.";
function rustTypes(): string {
  let result = `// ${banner}\n#![no_std]\nuse core::ffi::c_void;\npub const MAX_DAMAGE_REGIONS: usize = 8;\n`;
  for (const callback of IDF_NATIVE_CALLBACKS) result += `\npub type ${callback.name} = unsafe extern "C" fn(${callback.args.join(", ")}) -> bool;\n`;
  for (const record of IDF_NATIVE_STRUCTS) {
    result += `\n#[repr(C)]\n#[derive(Clone, Copy, Default)]\npub struct ${record.name} {\n`;
    for (const field of record.fields) result += `    pub ${field.name}: ${field.type},\n`;
    result += "}\n";
    const a = layout(record.name, 4), b = layout(record.name, 8);
    result += `const _: () = {\n    let p32 = core::mem::size_of::<usize>() == 4;\n`;
    for (const [op, x, y] of [["size_of", a.size, b.size], ["align_of", a.align, b.align]])
      result += `    assert!(core::mem::${op}::<${record.name}>() == if p32 { ${x} } else { ${y} });\n`;
    record.fields.forEach((field, i) => result += `    assert!(core::mem::offset_of!(${record.name}, ${field.name}) == if p32 { ${a.offsets![i]} } else { ${b.offsets![i]} });\n`);
    result += "};\n";
  }
  return result;
}
function cTypes(component: "core" | "renderer"): string {
  let result = `/* ${banner} */\n#pragma once\n#include <stdbool.h>\n#include <stddef.h>\n#include <stdint.h>\n`;
  result += "#ifdef __cplusplus\n#define PJS_ABI_ASSERT static_assert\n#define PJS_ABI_ALIGNOF alignof\n#else\n#define PJS_ABI_ASSERT _Static_assert\n#define PJS_ABI_ALIGNOF _Alignof\n#endif\n";
  if (component === "renderer") result += "#define POCKETJS_RGB565_MAX_DAMAGE_REGIONS 8U\n";
  for (const record of IDF_NATIVE_STRUCTS.filter(s => s.component === component)) {
    if (record.name === "NativeAccelerator") for (const callback of IDF_NATIVE_CALLBACKS)
      result += `\ntypedef bool (*${callback.cName})(${callback.args.map(cType).join(", ")});\n`;
    result += "\ntypedef struct {\n";
    for (const field of record.fields) {
      const a = array(field.type);
      if (field.name === "epoch") result += "  /* Borrow generation changes on every draw, mutation, and tick. */\n";
      if (field.name === "private_core") result += "  /* Opaque C bridge; callers must not inspect or dereference. */\n";
      result += a ? `  ${cType(a[1])} ${field.cName}[${a[2] === "MAX_DAMAGE_REGIONS" ? 8 : a[2]}];\n` : `  ${cType(field.type)} ${field.cName};\n`;
    }
    result += `} ${record.cName};\n`;
    const a = layout(record.name, 4), b = layout(record.name, 8);
    result += `PJS_ABI_ASSERT(sizeof(${record.cName}) == (sizeof(void *) == 4 ? ${a.size} : ${b.size}), "${record.cName} size");\n`;
    result += `PJS_ABI_ASSERT(PJS_ABI_ALIGNOF(${record.cName}) == (sizeof(void *) == 4 ? ${a.align} : ${b.align}), "${record.cName} alignment");\n`;
    record.fields.forEach((field, i) => result += `PJS_ABI_ASSERT(offsetof(${record.cName}, ${field.cName}) == (sizeof(void *) == 4 ? ${a.offsets![i]} : ${b.offsets![i]}), "${record.cName}.${field.cName}");\n`);
  }
  return result + "\n#undef PJS_ABI_ASSERT\n#undef PJS_ABI_ALIGNOF\n";
}
export function generatedIdfContracts(): Map<string, string> {
  const constants: Record<string, number> = {
    POCKET_MAGIC: pocket.POCKET_PACKAGE_MAGIC, POCKET_VERSION: pocket.POCKET_PACKAGE_VERSION,
    POCKET_HEADER_SIZE: pocket.POCKET_PACKAGE_HEADER_SIZE, POCKET_VARIANT_SIZE: pocket.POCKET_PACKAGE_VARIANT_SIZE,
    POCKET_SECTION_SIZE: pocket.POCKET_PACKAGE_SECTION_SIZE, POCKET_ALIGN: pocket.POCKET_PACKAGE_ALIGN,
    POCKET_TARGET_BYTES: pocket.POCKET_PACKAGE_TARGET_BYTES, POCKET_FOOTER_SIZE: pocket.POCKET_PACKAGE_FOOTER_SIZE,
    HOST_INPUTS_MAGIC: pocket.POCKET_HOST_INPUTS_MAGIC, HOST_INPUTS_VERSION: pocket.POCKET_HOST_INPUTS_VERSION,
    HOST_INPUTS_SIZE: pocket.POCKET_HOST_INPUTS_SIZE,
  };
  for (const [name, value] of Object.entries(pocket.POCKET_SECTION)) constants[`SECTION_${name.replace(/[A-Z]/g, c => "_" + c).toUpperCase()}`] = value;
  for (const [group, fields] of Object.entries(pocket.POCKET_LAYOUT)) for (const [name, value] of Object.entries(fields))
    constants[`OFFSET_${group.replace(/[A-Z]/g, c => "_" + c).toUpperCase()}_${name.replace(/[A-Z]/g, c => "_" + c).toUpperCase()}`] = value;
  const cConstants = "/* Generated from contracts/spec/pocket-package.ts. Do not edit. */\n#pragma once\n" +
    Object.entries(constants).map(([key, value]) => `#define ${key} ${value}U\n`).join("");
  const pyConstants = "# Generated from contracts/spec/pocket-package.ts. Do not edit.\n" +
    Object.entries(constants).map(([key, value]) => `${key} = ${value}\n`).join("") +
    `HOST_PRESENTATIONS = ${JSON.stringify(pocket.HOST_PRESENTATIONS)}\n`;
  const rustConstants = "// Generated from contracts/spec/pocket-package.ts. Do not edit.\n#![allow(dead_code)]\n" +
    Object.entries(constants).map(([key, value]) => `pub const ${key}: ${key.includes("MAGIC") || key.includes("VERSION") || key.startsWith("SECTION_") ? "u32" : "usize"} = ${value};\n`).join("");
  return new Map([
    ["hosts/esp-idf/components/pocketjs_package/include/pocketjs/package_format.h", cConstants],
    ["hosts/esp-idf/components/pocketjs_package/tools/package_format.py", pyConstants],
    ["engine/core/src/package_format.rs", rustConstants],
    ["hosts/esp-idf/components/pocketjs_ui_qjs/include/pocketjs/pak_format.h",
      "/* Generated from contracts/spec/spec.ts. Do not edit. */\n#pragma once\n" +
      Object.entries({ PAK_MAGIC, PAK_VERSION, PAK_HEADER_SIZE, PAK_ENTRY_SIZE }).map(([key, value]) => `#define ${key} ${value}U\n`).join("")],
    ["hosts/esp-idf/native/abi/src/lib.rs", rustTypes()],
    ["hosts/esp-idf/components/pocketjs_ui_core/include/pocketjs/ui_types.h", cTypes("core")],
    ["hosts/esp-idf/components/pocketjs_render_rgb565/include/pocketjs/render_types.h", cTypes("renderer")],
    ["hosts/esp-idf/components/pocketjs_ui_core/include/pocketjs/native_ui.h", cFunctions("ui-core", "ui_core")],
    ["hosts/esp-idf/components/pocketjs_render_rgb565/include/pocketjs/native_renderer.h", cFunctions("render-rgb565", "render_rgb565")],
  ]);
}

function cFunctions(crate: string, header: string): string {
  const source = readFileSync(resolve(root, `hosts/esp-idf/native/${crate}/src/lib.rs`), "utf8");
  let result = `/* Generated from native/${crate}/src/lib.rs. Do not edit. */\n#pragma once\n#include "pocketjs/${header}.h"\n`;
  const signatures = new Map<string, { args: string; result: string }>();
  for (const match of source.matchAll(/pub unsafe extern "C" fn (\w+)\(\s*([^)]*)\)\s*(?:->\s*([\w:* ]+))?\s*\{/g)) {
    signatures.set(match[1], { args: match[2], result: match[3]?.trim() ?? "c_void" });
  }
  for (const match of source.matchAll(/core_void!\((\w+)\(([^)]*)\)/g))
    signatures.set(match[1], { args: `core: *mut NativeUiCore,${match[2]}`, result: "c_void" });
  if (signatures.size < 5) throw new Error(`no native signatures found in ${crate}`);
  for (const [name, signature] of [...signatures].sort(([a], [b]) => a.localeCompare(b))) {
    const args = signature.args.split(",").map(a => a.trim()).filter(Boolean).map(arg => {
      const [name, type] = arg.split(":").map(p => p.trim());
      return `${cType(type)} ${name}`;
    });
    result += `${cType(signature.result)} ${name}(${args.join(", ") || "void"});\n`;
  }
  return result;
}
if (import.meta.main) {
  const check = Bun.argv.includes("--check");
  for (const [path, contents] of generatedIdfContracts()) {
    const file = resolve(root, path);
    if (check) {
      if (!existsSync(file) || readFileSync(file, "utf8") !== contents) throw new Error(`stale generated contract: ${path}`);
    } else await Bun.write(file, contents);
  }
}
