// tools/esp-idf.ts — build inputs for the ESP-IDF network hosts.
//
//   bun tools/esp-idf.ts smoke-inputs --board=atoms3r|tab5 --outdir=<dir>
//        [--mac-host=H --mac-http-port=P --mac-ws-port=P]
//        [--peer-host=H --peer-port=P] [--serve-port=P] [--tls-host=H]
//        [--tick-hz=N] [--no-bundle]
//
// The smoke firmware's CMake runs this before compiling. It turns the smoke
// manifest (hosts/esp-idf/examples/net-smoke/pocket.json, format 3) plus the
// rig's endpoints (Kconfig: workstation peer, peer board, serve port, TLS
// host) into one resolved manifest, resolves the Build Plan against the
// board's private profile (tools/esp-idf-profile.ts), and writes into
// <outdir>:
//
//   pocket.resolved.json   the manifest the plan was resolved from
//   plan.json              the ResolvedBuildPlan (planHash covers the policy)
//   network-policy.json    HostBuildInputs.network.policyJson — the canonical
//                          ResolvedNetworkPolicy the firmware embeds and hands
//                          to pnet_runtime_create verbatim
//   host-inputs.h          C defines: plan hash, target, features, tick rate
//   app.js                 the guest bundle (tools/build.ts --plan)
//
// The firmware never authors a policy: everything it mounts and allows comes
// from these files, and planHash names the build on the device.

import { mkdirSync } from "node:fs";
import { dirname, join, resolve as resolvePath } from "node:path";
import { fileURLToPath } from "node:url";
import type { NetworkConnectRule, NetworkListenRule } from "../contracts/spec/network-policy.ts";
import { extractHostBuildInputs } from "../framework/src/manifest/host-build-inputs.ts";
import { espIdfPanel, resolveEspIdfBuildPlan, type EspIdfBoard } from "./esp-idf-profile.ts";

const ROOT = resolvePath(fileURLToPath(new URL("..", import.meta.url)));
const SMOKE_DIR = join(ROOT, "hosts/esp-idf/examples/net-smoke");

export interface SmokeRig {
  readonly board: EspIdfBoard;
  readonly macHost?: string;
  readonly macHttpPort: number;
  readonly macWsPort: number;
  readonly peerHost?: string;
  readonly peerPort: number;
  readonly servePort: number;
  readonly tlsHost?: string;
  readonly tickHz: number;
}

/** The smoke manifest with the rig's endpoints merged into its intent:
 * workstation peer HTTP (its port and the two after it — the WebSocket
 * listener and a closed port for the connection-refused case), workstation
 * WebSocket, peer board HTTP, the serve port, the positive TLS host, and the
 * board's panel as the (nominal, headless) viewport. */
export function smokeManifest(base: Record<string, any>, rig: SmokeRig): Record<string, any> {
  const manifest = structuredClone(base);
  const network = (manifest.permissions ??= {}).network ??= {};
  const connect: NetworkConnectRule[] = [...(network.connect ?? [])];
  if (rig.macHost) {
    connect.push({ protocol: "http", host: rig.macHost, port: { min: rig.macHttpPort, max: rig.macHttpPort + 2 } });
    connect.push({ protocol: "ws", host: rig.macHost, port: rig.macWsPort });
  }
  if (rig.peerHost) connect.push({ protocol: "http", host: rig.peerHost, port: rig.peerPort });
  if (rig.tlsHost && !connect.some((rule) => rule.protocol === "https" && rule.host === rig.tlsHost && rule.port === 443)) {
    connect.push({ protocol: "https", host: rig.tlsHost, port: 443 });
  }
  network.connect = connect;
  const listen: NetworkListenRule[] = [{ protocol: "http", address: "0.0.0.0", port: rig.servePort }];
  network.listen = listen;
  const panel = espIdfPanel(rig.board);
  manifest.app.viewport = { logical: [panel[0], panel[1]], presentation: "native" };
  return manifest;
}

/** C header with the plan facts the firmware compiles against. */
export function hostInputsHeader(inputs: ReturnType<typeof extractHostBuildInputs>, rig: SmokeRig): string {
  const define = (name: string, value: string | number) => `#define ${name} ${typeof value === "number" ? value : JSON.stringify(value)}`;
  const feature = (id: string) => define(`POCKETJS_FEATURE_${id.toUpperCase().replace(/[^A-Z0-9]/g, "_")}`, inputs.features[id] ? 1 : 0);
  return [
    "/* GENERATED by tools/esp-idf.ts from the smoke manifest's Build Plan — do not edit. */",
    "#ifndef POCKETJS_HOST_INPUTS_H",
    "#define POCKETJS_HOST_INPUTS_H",
    define("POCKETJS_PLAN_HASH", inputs.planHash),
    define("POCKETJS_TARGET", inputs.target),
    define("POCKETJS_HOST_ABI", inputs.hostAbi),
    define("POCKETJS_APP_OUTPUT", inputs.appOutput),
    define("POCKETJS_TICK_HZ", rig.tickHz),
    ...Object.keys(inputs.features).sort().map(feature),
    "#endif",
    "",
  ].join("\n");
}

function flag(args: string[], name: string): string | undefined {
  const prefix = `--${name}=`;
  const hit = args.find((a) => a.startsWith(prefix));
  return hit?.slice(prefix.length);
}

function intFlag(args: string[], name: string, fallback: number): number {
  const raw = flag(args, name);
  if (raw === undefined || raw === "") return fallback;
  const value = Number(raw);
  if (!Number.isInteger(value) || value < 0) throw new Error(`pocket esp-idf: --${name} must be a non-negative integer`);
  return value;
}

async function smokeInputs(args: string[]): Promise<void> {
  const board = flag(args, "board");
  if (board !== "atoms3r" && board !== "tab5") throw new Error("pocket esp-idf: --board=atoms3r|tab5 is required");
  const outdir = flag(args, "outdir");
  if (!outdir) throw new Error("pocket esp-idf: --outdir=<dir> is required");
  const rig: SmokeRig = {
    board,
    macHost: flag(args, "mac-host") || undefined,
    macHttpPort: intFlag(args, "mac-http-port", 8790),
    macWsPort: intFlag(args, "mac-ws-port", 8791),
    peerHost: flag(args, "peer-host") || undefined,
    peerPort: intFlag(args, "peer-port", 8080),
    servePort: intFlag(args, "serve-port", 8080),
    tlsHost: flag(args, "tls-host") || undefined,
    tickHz: intFlag(args, "tick-hz", 60),
  };
  const base = await Bun.file(join(SMOKE_DIR, "pocket.json")).json();
  const manifest = smokeManifest(base, rig);
  const plan = resolveEspIdfBuildPlan(manifest, board);
  const inputs = extractHostBuildInputs(plan);
  const out = resolvePath(outdir);
  mkdirSync(out, { recursive: true });
  await Bun.write(join(out, "pocket.resolved.json"), JSON.stringify(manifest, null, 2) + "\n");
  await Bun.write(join(out, "plan.json"), JSON.stringify(plan, null, 2) + "\n");
  await Bun.write(join(out, "network-policy.json"), inputs.network.policyJson + "\n");
  await Bun.write(join(out, "host-inputs.h"), hostInputsHeader(inputs, rig));
  if (!args.includes("--no-bundle")) {
    const build = Bun.spawnSync(
      ["bun", join(ROOT, "tools/build.ts"), `--plan=${join(out, "plan.json")}`, `--project-root=${SMOKE_DIR}`, `--outdir=${out}`, `--hz=${rig.tickHz}`],
      { cwd: ROOT, stdout: "inherit", stderr: "inherit" },
    );
    if (build.exitCode !== 0) throw new Error(`pocket esp-idf: bundle build failed (${build.exitCode})`);
  }
  console.log(`pocket esp-idf: ${board} plan ${plan.planHash.slice(0, 23)}… → ${out}`);
}

if (import.meta.main) {
  const [command, ...rest] = process.argv.slice(2);
  try {
    if (command === "smoke-inputs") await smokeInputs(rest);
    else {
      console.error("usage: bun tools/esp-idf.ts smoke-inputs --board=atoms3r|tab5 --outdir=<dir> [--mac-host=H ...]");
      process.exit(2);
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
