import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type MappingRange = number | readonly [number, number];
type MappingRow = readonly [MappingRange, number, string?];

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_DIRECTORY = resolve(ROOT, "tools/vendor/tr46-6.0.0");
const OUTPUT_DIRECTORY = resolve(ROOT, "framework/src/net/vendor/url");
const MAPPING_SOURCE = resolve(SOURCE_DIRECTORY, "mappingTable.json");
const REGEX_SOURCE = resolve(SOURCE_DIRECTORY, "regexes.js");
const DATA_OUTPUT = resolve(OUTPUT_DIRECTORY, "idna-data.generated.ts");
const REGEX_OUTPUT = resolve(OUTPUT_DIRECTORY, "idna-regexes.generated.ts");

const UPSTREAM_MAPPING_SHA256 =
  "c45bd284e01f0845bc3c3b1d7594cd7b9ee8b955ddc850882b8e1dc5d0cba95d";
const UPSTREAM_REGEX_SHA256 =
  "3f43551d5109e5a300b29d5a9c261adf2bfd1621ffc086909f8ebf40835fc70f";

function withoutOneTrailingNewline(source: string): string {
  return source.endsWith("\n") ? source.slice(0, -1) : source;
}

function sha256(source: string): string {
  return createHash("sha256").update(source).digest("hex");
}

function assertPinnedSource(source: string, expected: string, label: string): void {
  const raw = sha256(source);
  const withoutNewline = sha256(withoutOneTrailingNewline(source));
  if (raw !== expected && withoutNewline !== expected) {
    throw new Error(`${label} does not match pinned tr46 6.0.0 source: ${raw}`);
  }
}

function wrapStringLiteral(value: string, width = 100): string {
  const chunks: string[] = [];
  for (let offset = 0; offset < value.length;) {
    let end = Math.min(offset + width, value.length);
    const last = value.charCodeAt(end - 1);
    if (last >= 0xd800 && last <= 0xdbff) end--;
    chunks.push(`  ${JSON.stringify(value.slice(offset, end))}`);
    offset = end;
  }
  return chunks.join(" +\n");
}

export function renderTr46Data(source: string): string {
  assertPinnedSource(source, UPSTREAM_MAPPING_SHA256, "mappingTable.json");
  const rows = JSON.parse(source) as MappingRow[];
  const records = new Uint8Array(rows.length * 6);
  let expectedStart = 0;
  let mappingBlob = "";

  for (let index = 0; index < rows.length; index++) {
    const [range, status, mapping = ""] = rows[index]!;
    const start = Array.isArray(range) ? range[0]! : range as number;
    const end = Array.isArray(range) ? range[1]! : range as number;
    if (start !== expectedStart || end < start || end > 0x10ffff) {
      throw new Error(`mapping row ${index} is not a contiguous Unicode range`);
    }
    if (![1, 2, 3, 6, 7].includes(status)) {
      throw new Error(`mapping row ${index} has unknown status ${status}`);
    }
    if (mapping.length > 31 || mappingBlob.length > 0xffff) {
      throw new Error(`mapping row ${index} exceeds the packed format`);
    }

    const offset = index * 6;
    records[offset] = end & 0xff;
    records[offset + 1] = (end >>> 8) & 0xff;
    records[offset + 2] = (end >>> 16) & 0xff;
    records[offset + 3] = mappingBlob.length & 0xff;
    records[offset + 4] = mappingBlob.length >>> 8;
    records[offset + 5] = (mapping.length << 3) | status;
    mappingBlob += mapping;
    expectedStart = end + 1;
  }

  if (expectedStart !== 0x110000) {
    throw new Error("mapping table does not cover every Unicode scalar value");
  }

  const encodedRecords = Buffer.from(records).toString("base64");
  return `// Generated by tools/generate-url-idna-table.ts. Do not edit.\n` +
    `// tr46 6.0.0 / Unicode 17.0.0; source and license: tools/vendor/tr46-6.0.0.\n` +
    `export const TR46_TABLE_ENTRY_COUNT = ${rows.length};\n` +
    `export const TR46_TABLE_RECORDS =\n${wrapStringLiteral(encodedRecords)};\n` +
    `export const TR46_MAPPING_BLOB =\n${wrapStringLiteral(mappingBlob)};\n`;
}

export function renderTr46Regexes(source: string): string {
  assertPinnedSource(source, UPSTREAM_REGEX_SHA256, "regexes.js");
  const body = withoutOneTrailingNewline(source)
    .replace(/^"use strict";\n\n/u, "")
    .replace(/module\.exports = \{([\s\S]*?)\n  \};$/u, "export {$1\n};");
  if (!body.endsWith("};") || body.includes("module.exports")) {
    throw new Error("tr46 regex source shape changed");
  }
  return "// @ts-nocheck -- generated from pinned tr46 source.\n" +
    "// Generated by tools/generate-url-idna-table.ts. Do not edit.\n" + body + "\n";
}

function update(path: string, expected: string, check: boolean): boolean {
  let actual = "";
  try {
    actual = readFileSync(path, "utf8");
  } catch {
    // A missing generated file is ordinary drift.
  }
  if (actual === expected) return true;
  if (check) return false;
  writeFileSync(path, expected);
  return true;
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const mappingSource = readFileSync(MAPPING_SOURCE, "utf8");
  const regexSource = readFileSync(REGEX_SOURCE, "utf8");
  const clean = [
    update(DATA_OUTPUT, renderTr46Data(mappingSource), check),
    update(REGEX_OUTPUT, renderTr46Regexes(regexSource), check),
  ].every(Boolean);
  if (!clean) {
    console.error("generated URL IDNA data is stale; run bun tools/generate-url-idna-table.ts");
    process.exitCode = 1;
  }
}
