// The target contract a native shell bakes in: its identity and surfaces from
// the verified build plan, its capability list from the target registry.
// Rendered as C for engine/ui-cabi/include/pocket_package.h's
// pocket_package_validate_plan, so device-side plan admission and the desktop
// resolver (framework/src/manifest/resolve.ts) share one source of truth.
import type { HostBuildInputs } from "../framework/src/manifest/host-build-inputs.ts";
import type {
  PlatformContractRegistry,
  PresentationMode,
  Viewport,
} from "../contracts/spec/platforms.ts";

export interface NativeSurfaceContract {
  readonly logical: Viewport;
  readonly physical: Viewport;
  readonly presentation: PresentationMode;
  readonly rasterDensity: number;
}

export interface NativeTargetContract {
  readonly target: string;
  readonly hostAbi: number;
  readonly primary: NativeSurfaceContract;
  /** Present only when the plan resolved an auxiliary surface. */
  readonly auxiliary?: NativeSurfaceContract;
  /** Capability ids of the registry entry, sorted by codepoint. */
  readonly capabilities: readonly string[];
  /** Whether packages for this shell may carry a hostExtension payload. */
  readonly hostExtension: boolean;
}

export function resolveNativeTargetContract(
  inputs: HostBuildInputs,
  registry: PlatformContractRegistry,
): NativeTargetContract {
  const profile = registry.targets[inputs.target];
  if (!profile) throw new Error(`target contract: ${inputs.target} is not in the registry`);
  return {
    target: inputs.target,
    hostAbi: inputs.hostAbi,
    primary: {
      logical: inputs.viewport.logical,
      physical: inputs.viewport.physical,
      presentation: inputs.viewport.presentation,
      rasterDensity: inputs.viewport.rasterDensity,
    },
    ...(inputs.surfaces ? { auxiliary: inputs.surfaces.auxiliary } : {}),
    capabilities: [...profile.capabilities].sort((left, right) => (left < right ? -1 : left > right ? 1 : 0)),
    hostExtension: inputs.hostExtension !== undefined,
  };
}

function cText(value: string): string {
  if (!/^[\x20-\x7e]*$/.test(value) || /["\\]/.test(value)) {
    throw new Error(`target contract: ${JSON.stringify(value)} is not a plain ASCII identifier`);
  }
  return `"${value}"`;
}

function cUnsigned(value: number, name: string): string {
  if (!Number.isInteger(value) || value < 0 || value > 0xffffffff) {
    throw new Error(`target contract: ${name} must be an unsigned 32-bit integer`);
  }
  return `${value}u`;
}

/** Deterministic C for one build: `POCKET_TARGET_CONTRACT`. */
export function renderTargetContractHeader(contract: NativeTargetContract): string {
  const auxiliary = contract.auxiliary;
  const lines = [
    "/* Generated by tools/target-contract.ts from the target registry and the",
    " * verified build plan. Do not edit: it is rewritten by every native build. */",
    "#ifndef POCKET_TARGET_CONTRACT_H",
    "#define POCKET_TARGET_CONTRACT_H",
    "",
    '#include "pocket_package.h"',
    "",
    `#define POCKET_TARGET_CONTRACT_ID ${cText(contract.target)}`,
    `#define POCKET_TARGET_CONTRACT_HOST_ABI ${cUnsigned(contract.hostAbi, "hostAbi")}`,
    "",
    "static const char *const POCKET_TARGET_CONTRACT_CAPABILITIES[] = {",
    ...contract.capabilities.map((id) => `  ${cText(id)},`),
    "};",
    "",
    "static const PocketTargetContract POCKET_TARGET_CONTRACT = {",
    "  POCKET_TARGET_CONTRACT_ID,",
    "  POCKET_TARGET_CONTRACT_HOST_ABI,",
    `  ${cUnsigned(contract.primary.logical[0], "logical width")}, ${cUnsigned(contract.primary.logical[1], "logical height")},`,
    `  ${cUnsigned(contract.primary.physical[0], "physical width")}, ${cUnsigned(contract.primary.physical[1], "physical height")},`,
    `  ${cUnsigned(contract.primary.rasterDensity, "rasterDensity")},`,
    `  ${cText(contract.primary.presentation)},`,
    "  POCKET_TARGET_CONTRACT_CAPABILITIES,",
    `  ${cUnsigned(contract.capabilities.length, "capability count")},`,
    auxiliary
      ? `  ${cUnsigned(auxiliary.logical[0], "auxiliary logical width")}, ${cUnsigned(auxiliary.logical[1], "auxiliary logical height")},`
      : "  0u, 0u,",
    auxiliary
      ? `  ${cUnsigned(auxiliary.physical[0], "auxiliary physical width")}, ${cUnsigned(auxiliary.physical[1], "auxiliary physical height")},`
      : "  0u, 0u,",
    auxiliary ? `  ${cUnsigned(auxiliary.rasterDensity, "auxiliary rasterDensity")},` : "  0u,",
    auxiliary ? `  ${cText(auxiliary.presentation)},` : "  NULL,",
    `  ${contract.hostExtension ? "1u" : "0u"},`,
    "};",
    "",
    "#endif",
  ];
  return lines.join("\n") + "\n";
}
