#!/usr/bin/env bun
// static/spec/gen-c.ts — derive runtime/gen/spec_gen.h from the TS spec.
//
//   bun static/spec/gen-c.ts
//
// One header serves all targets; target-specific values sit behind
// PS_TARGET_GBA / PS_TARGET_GB / PS_TARGET_NES (exactly one must be defined
// by the build). C code must use ONLY these macros for anything the compiler
// also encodes — that is what keeps the two sides from drifting.

import { join } from "node:path";
import {
  DBG,
  DEBUG_BLOCK_SIZE,
  DEBUG_MAGIC_BYTES,
  FMT_CELLS,
  FONT_GLYPHS,
  KEYS,
  OP,
  RNG_SEED,
  SYSCALL_BASE,
  TARGETS,
  TEXT_ENTRY_SIZE,
  TOK_ASCII_MAX,
  TOK_ASCII_MIN,
  TOK_END,
  TOK_FMT,
  TOK_NEWLINE,
  VAR_SCRATCH_BASE,
  VM_BURST,
  VM_FLAGS,
  VM_FRAMES,
  VM_LOCALS,
  VM_STACK,
  VM_VARS,
  WAITING,
} from "./isa.ts";
import {
  ACTOR_F,
  ACTOR_SIZE,
  DIR,
  FACE_SELF,
  GAME_HEADER_SIZE,
  GAME_TITLE_LEN,
  MAP_HEADER_SIZE,
  MOVE,
  RPG_OP,
  SCRIPT_NONE,
  SFX,
  SPRITE_ENTRY_SIZE,
  SPRITE_FACINGS,
  SPRITE_TILES_PER_FRAME,
  STEP_PX,
  TEXT_NONE,
  TRIGGER_F,
  TRIGGER_SIZE,
  WANDER_PERIOD,
  WANDER_PHASE,
  WARP_SIZE,
} from "./rpg.ts";

const lines: string[] = [];
const put = (s = "") => lines.push(s);
const def = (name: string, v: number | string) => put(`#define ${name} ${typeof v === "number" ? v : v}`);
const hex = (v: number) => `0x${v.toString(16).toUpperCase()}`;

put("/* spec_gen.h — GENERATED by static/spec/gen-c.ts. DO NOT EDIT. */");
put("#ifndef PS_SPEC_GEN_H");
put("#define PS_SPEC_GEN_H");
put();
put("/* ---- core VM ---- */");
for (const [name, code] of Object.entries(OP)) def(`OP_${name}`, hex(code));
def("PS_SYSCALL_BASE", hex(SYSCALL_BASE));
def("VM_STACK", VM_STACK);
def("VM_FRAMES", VM_FRAMES);
def("VM_LOCALS", VM_LOCALS);
def("VM_VARS", VM_VARS);
def("VM_FLAGS", VM_FLAGS);
def("VM_BURST", VM_BURST);
def("VAR_SCRATCH_BASE", VAR_SCRATCH_BASE);
def("PS_RNG_SEED", hex(RNG_SEED));
put();
put("/* ---- keys (normalized pad bitmask) ---- */");
for (const [name, v] of Object.entries(KEYS)) def(`PS_KEY_${name}`, hex(v));
put();
put("/* ---- waiting states ---- */");
for (const [name, v] of Object.entries(WAITING)) def(`WAITING_${name}`, v);
put();
put("/* ---- rpg syscalls ---- */");
for (const [name, code] of Object.entries(RPG_OP)) def(`OP_${name}`, hex(code));
def("FACE_SELF", hex(FACE_SELF));
for (const [name, v] of Object.entries(SFX)) def(`SFX_${name}`, v);
put();
put("/* ---- directions / movement ---- */");
for (const [name, v] of Object.entries(DIR)) def(`DIR_${name}`, v);
for (const [name, v] of Object.entries(MOVE)) def(`MOVE_${name}`, v);
def("WANDER_PERIOD", WANDER_PERIOD);
def("WANDER_PHASE", WANDER_PHASE);
def("STEP_PX", STEP_PX);
put();
put("/* ---- text tokens ---- */");
def("TOK_END", hex(TOK_END));
def("TOK_FMT", hex(TOK_FMT));
def("TOK_NEWLINE", hex(TOK_NEWLINE));
def("TOK_ASCII_MIN", hex(TOK_ASCII_MIN));
def("TOK_ASCII_MAX", hex(TOK_ASCII_MAX));
def("FONT_GLYPHS", FONT_GLYPHS);
def("FMT_CELLS", FMT_CELLS);
def("TEXT_ENTRY_SIZE", TEXT_ENTRY_SIZE);
put();
put("/* ---- record layouts ---- */");
def("GAME_TITLE_LEN", GAME_TITLE_LEN);
def("GAME_HEADER_SIZE", GAME_HEADER_SIZE);
def("MAP_HEADER_SIZE", MAP_HEADER_SIZE);
def("ACTOR_SIZE", ACTOR_SIZE);
def("WARP_SIZE", WARP_SIZE);
def("TRIGGER_SIZE", TRIGGER_SIZE);
def("SPRITE_ENTRY_SIZE", SPRITE_ENTRY_SIZE);
def("SPRITE_FACINGS", SPRITE_FACINGS);
def("SPRITE_TILES_PER_FRAME", SPRITE_TILES_PER_FRAME);
for (const [name, v] of Object.entries(ACTOR_F)) def(`ACTOR_F_${name}`, v);
for (const [name, v] of Object.entries(TRIGGER_F)) def(`TRIGGER_F_${name}`, v);
def("SCRIPT_NONE", hex(SCRIPT_NONE));
def("TEXT_NONE", hex(TEXT_NONE));
put();
put("/* ---- debug block ---- */");
for (const [name, off] of Object.entries(DBG)) def(`DBGO_${name}`, hex(off));
def("DEBUG_BLOCK_SIZE", hex(DEBUG_BLOCK_SIZE));
DEBUG_MAGIC_BYTES.forEach((b, idx) => def(`DEBUG_MAGIC_${idx}`, hex(b)));
put();
put("/* ---- per-target ---- */");
const guards = { gba: "PS_TARGET_GBA", gb: "PS_TARGET_GB", nes: "PS_TARGET_NES" } as const;
let first = true;
for (const t of ["gba", "gb", "nes"] as const) {
  const spec = TARGETS[t];
  put(`#${first ? "if" : "elif"} defined(${guards[t]})`);
  first = false;
  def("PS_DEBUG_ADDR", hex(spec.debugAddr));
  def("PS_TEXT_COLS", spec.textCols);
  def("PS_TEXT_LINES", spec.textLines);
  def("PS_MAX_CHOICES", spec.maxChoices);
  def("PS_SCREEN_TILES_W", spec.screenTilesW);
  def("PS_SCREEN_TILES_H", spec.screenTilesH);
  def("PS_TILE_BYTES", spec.tileBytes);
  def("PS_SCROLLS", spec.scrolls ? 1 : 0);
  def("PS_BG_TOTAL_TILES", spec.bgTotalTiles);
  def("PS_BG_CURSOR_TILE", spec.bgTotalTiles - 97);
  def("PS_BG_BOX_TILE", spec.bgTotalTiles - 96);
  def("PS_BG_FONT_BASE", spec.bgTotalTiles - 95);
}
put("#else");
put('#error "define exactly one of PS_TARGET_GBA / PS_TARGET_GB / PS_TARGET_NES"');
put("#endif");
put();
put("#endif /* PS_SPEC_GEN_H */");

const out = join(import.meta.dir, "..", "runtime", "gen", "spec_gen.h");
await Bun.write(out, lines.join("\n") + "\n");
console.log(`wrote ${out} (${lines.length} lines)`);
