[package]
name = "pocketjs-idf-render-rgb565"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
pocketjs-core = { path = "../../../../engine/core" }
pocketjs-idf-abi = { path = "../abi" }
pocketjs-idf-runtime = { path = "../runtime" }
pocketjs-render-rgb565 = { path = "../../../../engine/backends/rgb565" }


[features]
default = ["std"]
std = ["pocketjs-core/std", "pocketjs-idf-runtime/std", "pocketjs-render-rgb565/std"]

[profile.release]
codegen-units = 16
lto = false
opt-level = 3
panic = "abort"

[workspace]
